### ISSUE TITLE
PreSerialization hook is being called when reply payload is null

### ISSUE THREAD

**Issue by gracoes** [fastify/fastify#5053] opened 2023-09-20 16:17 UTC
### Fastify version

4.0.0

### Node.js version

16.19.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Ventura 13.5.2

### Description

Although the Fastify docs say that the`preSerialization` hook will [not be called](https://fastify.dev/docs/latest/Reference/Hooks/#preserialization) when the reply payload is `null`, it is in fact being called.

### Steps to Reproduce

1. Follow the steps in the `Getting Started` section of the README.
2. Add a `preSerialization` hook to the `GET /example` route.
3. Change the route to reply with `null`

```js
// example
'use strict';

module.exports = async function (fastify, opts) {
	fastify.addHook('preSerialization', async (req, reply, payload) => {
		throw new Error(`Should not reach here\npayload: ${payload}`);
	});

	fastify.get('/', async function (request, reply) {
		return null;
	});
};
```

### Expected Behavior

The hook should not be called.

### Notes
I suspect the issue is somewhere around [here](https://github.com/fastify/fastify/blob/f33db238f4eda4602517a6d19f537751b5193395/lib/reply.js#L196).
Maybe it should check that the `payload` is different from null as well?

**Comment by climba03003** [comment] 2023-09-21 04:04
Duplicate of #5003

The issue stated is not the same, but the under-laying cause is the same.

**Closed by climba03003** 2023-09-21 04:04 UTC
Labels: bug
