### ISSUE TITLE
How can i get my image that saved in server?

### ISSUE THREAD

**Issue by galuh1300d** [fastify/fastify#1395] opened 2019-01-16 13:53 UTC
Hello, can i get my image that saved in my server?
so i saved my image at public in root folder, can i get it and show it in my frontend app? 
Thank you

**Comment by cemremengu** [comment] 2019-01-16 13:56
See https://github.com/fastify/fastify-static

**Comment by cemremengu** [comment] 2019-01-16 14:30
Duplicate of https://github.com/fastify/fastify-static/issues/88

**Closed by cemremengu** 2019-01-16 14:30 UTC
Labels: question
