### ISSUE TITLE
Vitest and Decorators of Plugins, not coming down

### ISSUE THREAD

**Issue by Bugs5382** [fastify/fastify#5352] opened 2024-03-08 02:10 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.1

### Plugin version

4.26.1

### Node.js version

20.11

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.4

### Description

Not sure where to put this, so move if needed:

I am using Vitest to do unit testing. One thing I noticed is that Typescript is having a hard time understanding plugin decorators that will be loaded:

<img width="196" alt="image" src="https://github.com/fastify/fastify/assets/12115015/c04ca4d1-ca67-4aa5-9622-bfab0a89504d">

This is the best example I can give is that the server shows that MongoDB (satisfy-MongoDB plugin is being used) can not be found. When the code is run, it's okay and doesn't error run out.

The server is being returned as:

```ts
let server: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>
```

### Steps to Reproduce

Direct Access to Code: https://github.com/JAMS-Project/node-microservice-itil/blob/43a02cc4a23ce07a4261444f7972bb38815d5c53/__tests__/basic.test.ts#L16

**Comment by climba03003** [comment] 2024-03-08 05:27
I am closing the issue since it is expected behavior in `TypeScript`.
`TypeScript` only knows something that is EXPLICITLY `imported` through the runnable code.

That means when you are using `@fastify/autoload`, `TypeScript` do not knows all information since there is no direct `import` through the code.

As a workaround, you need to specify the module you use in `tsconfig.json`. Or import the module one by one.

**Closed by climba03003** 2024-03-08 05:27 UTC

**Comment by Bugs5382** [comment] 2024-03-11 21:57
In case anyone else comes back to this, I changed:

```json
    "include": ["./**/*"]
```

to

```json
    "include": ["./**/*", "../src/**/*"]
```

... and that fixed the issue.
