### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by borodadada** [fastify/fastify#1793] opened 2019-08-10 10:01 UTC
Hello, why my server down, when i use seo scaner site's?
my server http2  "fastify": "^2.7.1"

ERROR

events.js:180
      throw er; // Unhandled 'error' event
      ^

```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:183:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! site@1.0.0 dev: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the site@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-08-10T09_55_23_876Z-debug.log
```

LOG FILE

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.10.2
3 info using node@v12.8.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle site@1.0.0~predev: site@1.0.0
6 info lifecycle site@1.0.0~dev: site@1.0.0
7 verbose lifecycle site@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle site@1.0.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\js\site\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\nodejs\;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Admin\AppData\Roaming\npm
9 verbose lifecycle site@1.0.0~dev: CWD: D:\js\site
10 silly lifecycle site@1.0.0~dev: Args: [ '/d /s /c', 'node server.js' ]
11 silly lifecycle site@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle site@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: site@1.0.0 dev: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:203:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:203:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid site@1.0.0
15 verbose cwd D:\js\site
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v12.8.0
19 verbose npm  v6.10.2
20 error code ELIFECYCLE
21 error errno 1
22 error site@1.0.0 dev: `node server.js`
22 error Exit status 1
23 error Failed at the site@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mcollina** [comment] 2019-08-10 11:00
Can you add an example to reproduce?

Il giorno sab 10 ago 2019 alle 12:01 borodadada <notifications@github.com>
ha scritto:

**Comment by borodadada** [comment] 2019-08-10 11:07
server use COMODO SSL

```
const fastify = require('fastify')({
    logger: false,
    http2: true,
    trustProxy: true,
    https: {
        key: fs.readFileSync(path.join(serverDirectory, '/certificate/site/', 'key.pem')),
        cert: fs.readFileSync(path.join(serverDirectory, '/certificate/site/', 'cert.crt')),
        ca: [
            fs.readFileSync(path.join(serverDirectory, '/certificate/site/', 'USERTrustRSAAddTrustCA.crt')),
            fs.readFileSync(path.join(serverDirectory, '/certificate/site/', 'AddTrustExternalCARoot.crt')),
            fs.readFileSync(path.join(serverDirectory, '/certificate/site/', 'SectigoRSADomainValidationSecureServerCA.crt')), 
        ]
    }
});

fastify.register(require('fastify-favicon'));
fastify.use('/dist', serveStatic(path.join(serverDirectory, '/dist')))
fastify.use('/', serveStatic(path.join(serverDirectory, '/public')))

fastify.get('*', (request, reply) => {
    if( isProd )
        render(request, reply)
    else
        readyPromise.then( ()=> render(request, reply) )
})

fastify.listen(443, '0.0.0.0', (err, address) => {
    if (err) {
        fastify.log.error(err)
        process.exit(1)
    }
    fastify.log.info(`server listening on ${address}`)
})
```

**Comment by mcollina** [comment] 2019-08-10 11:14
how can we reproduce the crash?
Which version of Node are you using?

Il giorno sab 10 ago 2019 alle 13:07 borodadada <notifications@github.com>
ha scritto:

**Comment by borodadada** [comment] 2019-08-10 11:45
any site SEO cheker example
https://www.seotesteronline.com/
Node js 12.7.0, 12.8.0

**Comment by jsumners** [comment] 2019-08-10 12:00
You should really enable logging _somewhere_ so you can see what request is causing the problem

**Comment by borodadada** [comment] 2019-08-10 12:10
fastify logger: true

```
isDev
(node:2392) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
{"level":30,"time":1565438875250,"pid":2392,"hostname":"WIN-DGOJHT1CDMA","msg":"Server listening at https://0.0.0.0:443","v":1}
{"level":30,"time":1565438875251,"pid":2392,"hostname":"WIN-DGOJHT1CDMA","msg":"server listening on https://0.0.0.0:443","v":1}

events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:183:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
...............................
```

**Comment by borodadada** [comment] 2019-08-17 19:44
i tryed use ubuntu 18 but no result, error exist

this is enter point

```
fastify.get('*', (request, reply) => {
    if( isProd )
        render(request, reply)
    else
        readyPromise.then( ()=> render(request, reply) )
})
```

render is
```
function render (request, reply) {
    const context = { url: request.req.url }
    console.log(context)
    reply.send( { a: 123 } )
}
```

site killer https://sitechecker.pro/

i dont understand, wft :)

**Comment by Eomm** [comment] 2019-08-19 06:41
The server crash with some curl requests?
I don't see the require for serveStatic(path.join(serverDirectory

Could you use https://github.com/fastify/fastify-static instead?

**Comment by borodadada** [comment] 2019-08-19 06:55
"The server crash with some curl requests?" - yes
I use serve-static npm, i will try use fastify-static and reply later, thanks man.

**Comment by Eomm** [comment] 2019-09-04 11:53
> Okey, repalce serve-static on fastify-static, test = server equally down.

I think we should investigate then.
It would speed up a lot if you could create a repo with the error so we can dig the root cause

**Comment by DrachovDmytro** [comment] 2019-09-25 18:25
Hey there, basically **ECONNRESET** error means that peer closed connection https://nodejs.org/api/errors.html .

There are might exist a lot of reason why connection could be closed by peer.
Since we don't know how site scanners work it will be difficult to find root of cause.

Basically I've reproduced an issue on local environment:
```
npm --versions
{
  fastify_1793: '1.0.0',
  npm: '6.10.2',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '72',
  napi: '4',
  nghttp2: '1.39.1',
  node: '12.8.0',
  openssl: '1.1.1c',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.30.1',
  v8: '7.5.288.22-node.16',
  zlib: '1.2.11'
}

system_profiler SPSoftwareDataType | grep Version
      System Version: macOS 10.14.6 (18G95)
      Kernel Version: Darwin 18.7.0

cat node_modules/fastify/package.json |grep version
  "version": "2.8.0"

```

I've created self-signed certs with command `openssl req -nodes -new -x509 -keyout server.key -out server.cert`

#### Server Code
```
const fs = require('fs');
const fastify = require('fastify')({
    logger: true,
    http2: true,
    trustProxy: true,
    https: {
        key: fs.readFileSync('server.key'),
        cert: fs.readFileSync('server.cert')
    }
});

fastify.get('*', (request, reply) => {
    reply.code(200).send({'HELLO': 'WORLD'});
});

fastify.listen(443, '0.0.0.0', (err, address) => {
    if (err) {
        fastify.log.error(err)
        process.exit(1)
    }
    fastify.log.info(`server listening on ${address}`)
})

```

#### Client code
```
rp = require('request-promise-native')
rp.get({uri:'https://127.0.0.1',strictSSL:false}).then(console.log, console.log)
rp.get({uri:'https://127.0.0.1',strictSSL:true}).then(console.log, console.log)
```


#### Client output
```
FIRST REQ
{ StatusCodeError: 403 - "Unknown ALPN Protocol, expected `h2` to be available.\nIf this is a HTTP request: The server was not configured with the `allowHTTP1` option or a listener for the `unknownProtocol` event.\n"
    at new StatusCodeError (/Users/dmytro.drachov/Dolby/Services/fastify_1793/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/dmytro.drachov/Dolby/Services/fastify_1793/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/dmytro.drachov/Dolby/Services/fastify_1793/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/dmytro.drachov/Dolby/Services/fastify_1793/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:466:23)
    at Request.<anonymous> (/Users/dmytro.drachov/Dolby/Services/fastify_1793/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:466:23)
    at IncomingMessage.<anonymous> (/Users/dmytro.drachov/Dolby/Services/fastify_1793/node_modules/request/request.js:1083:12)
  name: 'StatusCodeError',
  statusCode: 403,
  message:
   '403 - "Unknown ALPN Protocol, expected `h2` to be available.\\nIf this is a HTTP request: The server was not configured with the `allowHTTP1` option or a listener for the `unknownProtocol` event.\\n"',
  error:
   'Unknown ALPN Protocol, expected `h2` to be available.\nIf this is a HTTP request: The server was not configured with the `allowHTTP1` option or a listener for the `unknownProtocol` event.\n',



SECOND REQ
{ RequestError: Error: self signed certificate
    at new RequestError (/Users/dmytro.drachov/Dolby/Services/fastify_1793/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/dmytro.drachov/Dolby/Services/fastify_1793/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/dmytro.drachov/Dolby/Services/fastify_1793/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/dmytro.drachov/Dolby/Services/fastify_1793/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.onRequestError (/Users/dmytro.drachov/Dolby/Services/fastify_1793/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
  name: 'RequestError',
  message: 'Error: self signed certificate',
  cause:
   { Error: self signed certificate
       at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
       at TLSSocket.emit (events.js:198:13)
       at TLSSocket.EventEmitter.emit (domain.js:466:23)
       at TLSSocket._finishInit (_tls_wrap.js:636:8) code: 'DEPTH_ZERO_SELF_SIGNED_CERT' },
  error:
   { Error: self signed certificate
       at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
       at TLSSocket.emit (events.js:198:13)
       at TLSSocket.EventEmitter.emit (domain.js:466:23)
       at TLSSocket._finishInit (_tls_wrap.js:636:8) code: 'DEPTH_ZERO_SELF_SIGNED_CERT' },
```


#### Server output
```
node index.js
{"level":30,"time":1569435063346,"pid":71800,"hostname":"Dmytros-MBP","msg":"Server listening at https://0.0.0.0:443","v":1}
{"level":30,"time":1569435063346,"pid":71800,"hostname":"Dmytros-MBP","msg":"server listening on https://0.0.0.0:443","v":1}
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:183:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
```


Check your CA.
I advise you to find root of cause using different scenarios without some 3rd party.
- Try http instead of https
- Try http1.1 instead of http2

### NOTE: 
You should know that http2 is experimental in scope fastify.
Take a look https://github.com/fastify/fastify/blob/master/docs/HTTP2.md

**Comment by mcollina** [comment] 2019-09-27 11:11
@DrachovDmytro would you mind pushing all of that in a repo so it's easy to reproduce?

**Comment by DrachovDmytro** [comment] 2019-09-30 11:25
@mcollina For sure. I am going to make more deep investigation.

@borodadada Could please write down concrete version of fustify instead of ^2.7.1?
And as solution for now you could add error handler on server to avoid crash.

**Comment by borodadada** [comment] 2019-10-05 08:32
i use
`
    "fastify": "^2.9.0",
    "fastify-cookie": "^3.1.0",
    "fastify-favicon": "^2.0.0",
    "fastify-static": "^2.5.0",
`

`
fastify.get('*', (request, reply) => {
    reply.code(200).send( {name: 'mongodb', status: 1 } )
})

fastify.listen(443, '0.0.0.0', (err, address) => {
    if( err ){
        fastify.log.error(err)
        process.exit(1)
    }
    fastify.log.info(`server listening on ${address}`)
})
`
Error

![Безымянный](https://user-images.githubusercontent.com/5166757/66252348-46603700-e763-11e9-93f8-aa07ab061d36.png)

WTF? Maximum simple test. site killer seotesteronline.com

![logggg](https://user-images.githubusercontent.com/5166757/66252399-d0100480-e763-11e9-9c72-6e8c2c6eb4cf.png)

**Comment by RafaelGSS** [comment] 2019-10-31 23:46
Hi @borodadada do you have a reproduction code? I would like to see it

**Comment by borodadada** [comment] 2019-11-01 07:18
Hello RafaelGSS, How i can do it? Send full code? Or minimal project example?

**Comment by RafaelGSS** [comment] 2019-11-01 12:45
Just a reproduction example

**Comment by borodadada** [comment] 2019-11-01 14:53
i create simple project, all work = bug work, you need cert's if you want test with seotesteronline.com or google or etc, localhost https include
//zip google disk
https://drive.google.com/file/d/1Mm9VS15hxxt4vSKM16mp9ewGJ6ZtmwX1/view?usp=sharing

**Comment by borodadada** [comment] 2019-12-27 09:13
Work! cool

**Closed** 2020-01-03 07:35 UTC
Labels: bug

**Comment by nhhockeyplayer** [comment] 2020-11-21 01:42
I get this on my tomcat 9 server running http2 and I do not use fastify

```
  Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:213:20)

```
could be from sitting server ?
