### ISSUE TITLE
Support `RouteShorthandOptions` to receive async hooks

### ISSUE THREAD

**Issue by MatanYadaev** [fastify/fastify#4859] opened 2023-06-27 07:53 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Currently, `RouteShorthandOptions` type doesn't allow passing async hooks:

```ts
export interface RouteShorthandOptions<
  // ...
> {
  // ...
  onRequest?: onRequestHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger>
  | onRequestHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger>[];
```

It should be something like that:

```ts
export interface RouteShorthandOptions<
  // ...
> {
  // ...
  onRequest?: onRequestHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger>
  | onRequestHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger>[]
  // Add these two:
  | onRequestAsyncHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger>
  | onRequestAsyncHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger>[];
```

**Comment by mcollina** [comment] 2023-06-27 08:23
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by climba03003** [comment] 2023-06-27 10:04
For anyone who would like to works on this issue.
Please also check #4705

**Comment by Gimnath-Perera** [comment] 2023-07-01 04:26
Hi @mcollina assign this to me

**Comment by BrendenInhelder** [comment] 2023-07-31 18:38
I would like to work on solving this issue with a solution different from #4655 and #4862 to avoid regression.

**Comment by Uzlopak** [comment] 2023-07-31 18:45
Please provide a PR. Reassigning this to you.

**Comment by Uzlopak** [comment] 2023-08-01 09:35
Here is a TS Playground mvce

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMJwDYYEaINbIDeAsAFDIXIAUADnFALYCMAXMgM5hSgDmANMgAmAexAQ2VaFAD8bAKJQowqAEpkAXgB8yAG7DgglWz0GyAXzJlQkWIhQBBdgE8QCImUrU6jVhy68jZAAFJQZgdggAHhNBTXNLUmtoeCRkAHkaMGBRdndySgALYWE8djZ0LFwEAgAfZEcXBHjSMgQcsGQ4NgysnI08zyKSss7nV2QYAFdXXpAvemY1EnyKC1IzZCA

**Comment by Uzlopak** [comment] 2023-08-01 09:37
I asked @webstrand on discord if he could help us.

**Comment by Uzlopak** [comment] 2023-08-01 20:03
Maybe somebody can open a question on stackoverflow? Usually @jcalz also answers there really fast.

**Comment by BrendenInhelder** [comment] 2023-08-01 23:28
Hopefully, this is not repetitive but I wanted to note something (feel free to delete/hide if not beneficial to issue efforts).
With the (reverted) change from #4655 in route.d.ts:
```
  onRequest?: onRequestHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger>
  | onRequestHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger>[]
  | onRequestAsyncHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger>
  | onRequestAsyncHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger>[];
```
Even if we specify the return as a `Promise<void>` in associated test in `hooks.test-d.ts` we still have `any` types. request and reply are any (not recognized):
```
server.get<RouteGenericInterface, CustomContextConfig>('/', {
  onRequest: async (request, reply):Promise<void> => {
    expectType<CustomContextConfigWithDefault>(request.context.config)
    expectType<CustomContextConfigWithDefault>(reply.context.config)
  },
```
And likewise, providing an additional argument will resolve the issue (not really because it is meant to be async) because it recognizes the three args as one that includes a `hookHandlerDoneFunction` parameter no matter what that parameter actually is.

Maybe this is indicative of a complicated issue; I am not an expert on typescript.

**Closed** 2023-12-10 11:28 UTC
Labels: bug, good first issue, typescript
