### ISSUE TITLE
Hooks payload type

### ISSUE THREAD

**Issue by jonathan-roy** [fastify/fastify#4459] opened 2022-11-19 17:30 UTC
#### What are you trying to achieve, or the steps to reproduce?

I'm trying to define a hook with a payload of type `Array<unknown>` rather than the default `unknown` type:

```js
const preSerializationHook: preSerializationAsyncHookHandler<Array<unknown>> = async (request, reply, payload) => {
	return payload;
}

const listResources = (app: FastifyInstance): RouteShorthandOptionsWithHandler => ({
	"handler": handlerListResources,
	"preSerialization": [preSerializationHook],
});
```

#### What was the result you received?

I get the following error saying that `unknown` is not assignable to type `Array<unknown>`:
> Type 'preSerializationAsyncHookHandler<unknown[], Server, IncomingMessage, ServerResponse, RouteGenericInterface, unknown, FastifySchema, FastifyTypeProviderDefault, ResolveFastifyRequestType<...>, FastifyLoggerInstance>' is not assignable to type 'preSerializationHookHandler<unknown, Server, IncomingMessage, ServerResponse, RouteGenericInterface, unknown, FastifySchema, FastifyTypeProviderDefault, ResolveFastifyRequestType<...>, FastifyLoggerInstance>'.
  Types of parameters 'payload' and 'payload' are incompatible.
    Type 'unknown' is not assignable to type 'unknown[]'.ts(2322)

#### What did you expect?

I would like to know how to correctly specify the payload type.

#### Context

* *node version*: 14
* *fastify version*: 4
* *os*: Mac

**Comment by climba03003** [comment] 2022-12-28 06:41
Duplicate of #4376

**Closed by climba03003** 2022-12-28 06:41 UTC
