### ISSUE TITLE
connection.send behaves differently on Fastify v4

### ISSUE THREAD

**Issue by naknode** [fastify/fastify#4057] opened 2022-06-21 03:02 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

3.29.0

#### Other packages

 '@fastify/websocket': 6.0.1
'@fastify/cors': 8.0.0

### Stopped working in version

4.0.0

### Node.js version

18.3.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Fedora 35

### 💥 Regression Report

I have this simple server:

```typescript
const fastify = require("fastify")();
fastify.register(require("@fastify/websocket"));
fastify.register(require("@fastify/cors"));

fastify.get("/", { websocket: true }, (connection) => {
  console.log("Someone connected.");

  connection.socket.send("Hello from the server!");

  connection.socket.on("message", (message) => {
    console.log("Server was pinged: ", message.toString());

    connection.socket.send("Hello Fastify WebSockets");
  });
});

fastify.listen({ port: 9000 }, (err, address) => {
  if (err) {
    console.error(err);
    process.exit(1);
  }
  console.log(`Server listening at: ${address}`);
});
```

I run it using `fastify@3.29.0` and it all works. I upgrade to version 4 and when I visit it on the client (`http://localhost:9000`):

```
{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "connection.socket.send is not a function"
}
```

Same thing when I go to Postman and I connect via it's websocket-type request (`ws://localhost:9000`). It just disconnects.

It seems to have a problem with `connection.socket.send("Hello from the server!");`. My goal is that i try to send some data from the server upon connection. 

This use to work in fastify@3.x.x 

### Steps to Reproduce

1. Run it using `nodemon`
2. Observe terminal
3. Connect to `ws://localhost:9000` on Postman or connect to Client
4. See no activity.
5. Downgrade fastify to version 3.29.0. Observe success.

### Expected Behavior

I expect the server to successfully connect and the fastify route `/` to start accepting socket messages.

**Comment by climba03003** [comment] 2022-06-21 03:08
Please explicitly specify the `host` to either `127.0.0.1` or `::1` to see if it is duplicate of https://github.com/fastify/fastify-websocket/issues/207

**Comment by naknode** [comment] 2022-06-21 04:25
> Please explicitly specify the `host` to either `127.0.0.1` or `::1` to see if it is duplicate of [fastify/fastify-websocket#207](https://github.com/fastify/fastify-websocket/issues/207)

@climba03003 OK, I update it to this line: `fastify.listen({ port: 9000, host: "127.0.0.1" }, (err, address) => {` and now I get: `Server listening at: http://127.0.0.1:9000` while the server sees my connection "Someone connected.", it doesn't work 100% because it immediately closes right after connection. Postman is the same way.

![image](https://user-images.githubusercontent.com/616320/174715471-70cc5b4b-87e1-43b3-9c6c-3359c7084b3a.png)

With I have the config like this: `{ port: 9000 }`, with no `host` specified, the console says: `Server listening at: http://[::1]:9000` and I get that 500 Internal Server Error. 

I still get the `connection.socket.send is not a function` error going to `http://127.0.0.1:9000`

**Comment by climba03003** [comment] 2022-06-21 05:29
I see the problem now.
You must `await` the `fastify.register(require("@fastify/websocket"))`.

**Closed by climba03003** 2022-06-21 05:29 UTC
