### ISSUE TITLE
[Feature request] Custom messages for AJV errors

### ISSUE THREAD

**Issue by KaKi87** [fastify/fastify#2213] opened 2020-04-22 08:59 UTC
Hello,

Instead of an English sentence, I'd like to be able to send custom unlocalized error messages on JAV validation errors, such as : `INVALID_MAIL`, `WEAK_PASSWORD`, etc.

This is a duplicate of #1586 in terms of feature, but I've been asked to post a new issue.

Thanks

**Comment by mcollina** [comment] 2020-04-22 09:13
I do not understand what is needed more thank https://github.com/fastify/example/blob/master/validation-messages/custom-errors-messages.js.

Would you like to send a PR adding some docs about this?

**Comment by KaKi87** [comment] 2020-04-22 09:28
This code allows you to specify an error message for the entire validator but I'd like to specify error messages for each constraint (type, length, range, etc.)

**Comment by mcollina** [comment] 2020-04-22 09:34
https://github.com/epoberezkin/ajv-i18n should do the trick.

**Comment by KaKi87** [comment] 2020-04-22 10:01
How does `fastify` and `ajv-i18n` work together ?

**Comment by mcollina** [comment] 2020-04-22 19:23
It's definitely possible as Fastify embeds Ajv. It's a matter of doing a bit of discovery and documenting it.

**Comment by mcollina** [comment] 2020-04-22 19:44
This can totally be done. I just do not have a snippet for you to copy and paste.

**Comment by KaKi87** [comment] 2020-04-22 19:46
You mean the feature was implemented but not documented ?

**Comment by jsumners** [comment] 2020-04-22 19:47
It would be easiest to supply your AJV instance. https://www.fastify.io/docs/v2.13.x/Validation-and-Serialization/#schema-resolver

**Comment by mcollina** [comment] 2020-04-22 19:49
> You mean the feature was implemented but not documented ?

It does not need to be implemented. Just supply your own instance of Ajv.

**Comment by KaKi87** [comment] 2020-05-04 09:10
Okay, I figured out how to supply my own AJV instance.
However, I didn't figured out how can I specify a custom error message for each validation constraint ?
Thanks

**Comment by mcollina** [comment] 2020-05-04 10:04
This is probably what you need: https://github.com/epoberezkin/ajv-errors.

**Comment by KaKi87** [comment] 2020-05-04 10:17
Yes I did looked at that, but it actually doesn't allow me to provide different error messages for multiple required parameters for exemple.

If I have `required: ['foo', 'bar']`, I must provide the same error message whether `foo` or `bar` is missing.

I need to be able to provide different messages.

Thanks

**Comment by mcollina** [comment] 2020-05-04 10:52
There seems to be a full example about it: https://github.com/epoberezkin/ajv-errors#messages-for-keywords.

**Comment by KaKi87** [comment] 2020-05-04 11:00
Yes, you can set a different error message for each property's contraints, but you cannot set a different message for each missing required property

**Comment by jsumners** [comment] 2020-05-04 11:36
Closing as this is off-topic at this point. If you have issues with AJV, please consult the AJV project.

**Closed by jsumners** 2020-05-04 11:36 UTC
Labels: documentation, good first issue

**Comment by KaKi87** [comment] 2020-05-04 13:33
Okay, here's something on-topic because it's documented on fastify.io : the usage of `ajv.addSchema` specifies that the object contains an `$id` field, and the example value is `urn:schema:foo`. What format is it and how can I use it ? Thanks

**Comment by jsumners** [comment] 2020-05-04 13:48
This is still off-topic for the issue because the issue is about errors. You should open a new issue if you have questions about the documentation. 

Regardless, it is a URI. See https://tools.ietf.org/html/rfc3986
