### ISSUE TITLE
Update documentation for fastify.setDefaultRoute

### ISSUE THREAD

**Issue by joelnet** [fastify/fastify#4457] opened 2022-12-01 22:36 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

An issue is opened per @mcollina's request https://twitter.com/matteocollina/status/1598444249359568908.

It is not recommended to use `fastify.setDefaultRoute`. The method is included for edge case use.

The documentation should be updated to reflect this. The documentation should link to or include the recommended way to setup a default route.

**Comment by SaumyaBhushan** [comment] 2022-12-02 03:13
@joelnet What is the recommended way to set a Default route ?

**Comment by climba03003** [comment] 2022-12-02 03:19
I thought  it is properly explained the mechanism of `default route`.

https://github.com/fastify/fastify/blob/204be5f85720ffdaf83e18071b819c56878d6c36/docs/Reference/Server.md?plain=1#L1026-L1030

`default route` is a fallback function used by `fastify` itself for the `404 handling`. Once you customize your own one, it means that `fastify` will no longer be able to handle `404` like before.

**Comment by climba03003** [comment] 2022-12-02 05:50
Duplicate of https://github.com/fastify/fastify/issues/3977

**Closed by climba03003** 2022-12-02 05:50 UTC
Labels: duplicate

**Comment by joelnet** [comment] 2022-12-02 20:16
> @joelnet What is the recommended way to set a Default route ?

I would not use `fastify.setDefaultRoute` to set a default route and instead would use this:

```javascript
// set as last route.
fastify.get("*", (req, reply) => {
  return { route: "*" }
});
```

**Comment by joelnet** [comment] 2022-12-02 20:23
> I thought it is properly explained the mechanism of `default route`.
> 
> https://github.com/fastify/fastify/blob/204be5f85720ffdaf83e18071b819c56878d6c36/docs/Reference/Server.md?plain=1#L1026-L1030
> 
> `default route` is a fallback function used by `fastify` itself for the `404 handling`. Once you customize your own one, it means that `fastify` will no longer be able to handle `404` like before.
> 
> Refs: #3911

@climba03003, the confusion is `setDefaultRoute` is not recommended to be used as a default route (as per @mcollina). Instead this should be used for a default route:

```javascript
// set as last route.
fastify.get("*", (req, reply) => {
  return { route: "*" }
});
```

There are differences between these two routes.
- `setDefaultRoute` args are `IncomingMessage` and `ServerResponse`, while `fastify.get("*")` args are `FastifyRequest` and `FastifyReply`
- `setDefaultRoute` errors will not be handled by the fastify error handler.

```javascript
// ❌ Errors in setDefaultRoute will not be caught by setErrorHandler
fastify.setDefaultRoute(
  /**
   * @param {import('node:http').IncomingMessage} req
   * @param {import('node:http').ServerResponse} reply
   */
  (req, reply) => {
    throw new Error("SDFOIJ");
  }
);

fastify.setErrorHandler((err, req, reply) => {
  reply.send(`${err}`);
});
```

```javascript
// ✅ Errors are caught by setErrorHandler
fastify.get(
  "*",
  /**
   * @param {import("fastify").FastifyRequest} req
   * @param {import("fastify").FastifyReply} reply
   */
  (req, reply) => {
    throw new Error("UH OH!");
  }
);

fastify.setErrorHandler((err, req, reply) => {
  reply.send(`${err}`);
});
```
