### ISSUE TITLE
Re-throw non-Error is not handled by parent handler

### ISSUE THREAD

**Issue by camsteffen** [fastify/fastify#5214] opened 2023-12-15 15:46 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.25.1

### Node.js version

18.19.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.2

### Description

If a plugin error handler re-throws the error and the error is not an instance of `Error`, then the error does not propagate to the parent context error handler. Instead the error is simply handled by the default error handler.

I understand that throwing a non-Error is not good practice. This behavior caught me off guard when I was writing dummy code just to learn-by-doing how error handlers work. I had [falsely assumed](https://github.com/fastify/fastify/issues/4513#issuecomment-1854226606) that fastify simply doesn't bubble up errors based on my test.

### Steps to Reproduce

```js
const app = require("fastify")({ logger: true });

app.setErrorHandler((error, request, reply) => {
  console.log("parent");
  reply.status(500).send({ ok: false });
});

app.register((app, opts, next) => {
  app.setErrorHandler((error, request, reply) => {
    console.log("child");
    throw error;
  });

  app.get("/bad", async () => {
    // this error skips over the parent error handler
    throw "garbage";
  });
  app.get("/good", async () => {
    throw new Error("party");
  });

  next();
});

app.listen({ port: 8080 });
```

### Expected Behavior

The parent error handler sees the non-Error error.

**Comment by metcoder95** [comment] 2023-12-17 11:02
👋 
I can confirm I can reproduce the issue, although I'm not sure if this was the expected intention of the original design.

So far the error handling works as expected, I tried to narrow down to exactly the place that might be swallowing this error but haven't found it yet, I belive is somewhere near where we call the child error handling that we are ignoring the error thrown.

I'll try to revisit this later on.

**Comment by mcollina** [comment] 2023-12-17 11:39
This is expected and by design. It's not something we can easily change, as it might require a significant semver major refactor and possibly a drop in performance.

**Comment by metcoder95** [comment] 2023-12-17 15:55
Kind of imagined that, specially as it was pretty specific.

Should we document this behaviour?
It's kind of "_implied_" that people should be outside `throw`ing everything that is not an error; might be worth it as a common recommendation?

**Comment by mcollina** [comment] 2023-12-18 11:43
+1 on the documentation approach

**Comment by casantosmu** [comment] 2024-05-09 19:48
This PR (https://github.com/fastify/fastify/pull/5265) has successfully added the necessary clarification to the documentation.

**Comment by Uzlopak** [comment] 2024-05-09 20:00
Thanks for the report 

Closing ;)

**Closed by Uzlopak** 2024-05-09 20:00 UTC
Labels: documentation, good first issue
