### ISSUE TITLE
Can't resolve reference when schema includes both ref and anyOf

### ISSUE THREAD

**Issue by asafkotzer** [fastify/fastify#4404] opened 2022-11-07 10:06 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.9.2 (main)

### Node.js version

18.6.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

Hi fastify team!

Found this issue where if a response schema has both a reference and anyOf fails to resolve the reference.

Thanks in advance!

### Steps to Reproduce

The following test fails with "can't resolve reference UUID from id Entity":
```js
const { test } = require('tap')
const Fastify = require('../fastify')
test('ref and anyOf in the same response schema', t => {
  t.plan(2)
  const fastify = Fastify()

  fastify.addSchema({
    format: 'uuid',
    $id: 'UUID',
    type: 'string'
  })

  fastify.addSchema({
    $id: 'Entity',
    type: 'object',
    properties: {
      id: {
        $ref: 'UUID'
      },
      name: {
        anyOf: [
          {
            type: 'string'
          }
        ]
      }
    },
    required: ['id', 'name']
  })

  fastify.get('/', {
    schema: {
      response: { 200: { $ref: 'Entity' } }
    },
    handler: (req, reply) => {
      reply.send({ id: '16a375af-3a92-4d95-8745-660d06601594', name: 'foo' })
    }
  })

  fastify.inject({
    method: 'GET',
    url: '/'
  }, (err, res) => {
    t.error(err)
    t.same(res.json(), { id: '16a375af-3a92-4d95-8745-660d06601594', name: 'foo' })
  })
})

```

if I change the code as follows (just remove the anyOf), it works fine:
```js
const { test } = require('tap')
const Fastify = require('../fastify')
test('ref and anyOf in the same response schema', t => {
  t.plan(2)
  const fastify = Fastify()

  fastify.addSchema({
    format: 'uuid',
    $id: 'UUID',
    type: 'string'
  })

  fastify.addSchema({
    $id: 'Entity',
    type: 'object',
    properties: {
      id: {
        $ref: 'UUID'
      },
      name: {
        type: 'string'
      }
    },
    required: ['id', 'name']
  })

  fastify.get('/', {
    schema: {
      response: { 200: { $ref: 'Entity' } }
    },
    handler: (req, reply) => {
      reply.send({ id: '16a375af-3a92-4d95-8745-660d06601594', name: 'foo' })
    }
  })

  fastify.inject({
    method: 'GET',
    url: '/'
  }, (err, res) => {
    t.error(err)
    t.same(res.json(), { id: '16a375af-3a92-4d95-8745-660d06601594', name: 'foo' })
  })
})

```

### Expected Behavior

The test should pass, and the reference should resolve

**Comment by climba03003** [comment] 2022-11-07 10:10
Duplicate of https://github.com/fastify/fastify/issues/4390, https://github.com/fastify/fast-json-stringify/issues/555

**Closed by climba03003** 2022-11-07 10:10 UTC

**Comment by climba03003** [comment] 2022-11-07 10:16
It is current pending for release. Please be patient.
