### ISSUE TITLE
new scope for fastify plugin

### ISSUE THREAD

**Issue by pc-jedi** [fastify/fastify#1970] opened 2019-12-08 15:08 UTC
## 💬 Questions and Help

I try to encapsule the rate-limit plugin to its own fastify instance.

```js
const fastify = require("fastify");
const fastifyRateLimit = require("fastify-rate-limit");
const ioredis_1 = require("ioredis");
const server = fastify();
const start = async () => {
    server.get('/', async (request, response) => {
        return { hello: 'world' };
    });
    server.register(async (instance, opts) => {
        instance.register(fastifyRateLimit, {
            max: 1,
            timeWindow: 10 * 1000,
            redis: new ioredis_1.default()
        });
        instance.get('/limit1', async (request, response) => {
            return { limit: 1 };
        });
        instance.get('/limit2', async (request, response) => {
            return { limit: 2 };
        });
    });
    server.get('/broken', async (request, response) => {
        return { broken: true };
    });
    await server.listen(3000);
};
start()
    .catch((e) => {
    throw e;
});
```

## Expected behavior

Only the routes `/limit1` and `/limit2` should have the rate-limit plugin "attached".
But currently the route `/broken` is also limited by the rate-limiter, while the `/` is without any rate-limit.

As far as I understood the `.register` function it shall gave you a new scope of fastify that you can modify without effecting the "outer" fastify instance.

## Your Environment

- *node version*: 13.3.0
- *fastify version*: 2.11.0
- *fastify-rate-limit version*: 3.0.1
- *os*: Linux

**Comment by mcollina** [comment] 2019-12-08 21:06
I’ve transfered the issue on the fastify repo as this looks like a bug in the “onRoute” logic, which seems not encapsulated.

**Comment by delvedor** [comment] 2019-12-09 08:25
Confirmed, `onRoute` is not encapsulated:
https://github.com/fastify/fastify/blob/9b53f9a554514f0555da4bf2e2ad5126df4fcbeb/lib/hooks.js#L48-L59

Also `onClose` and `onRegister` are not encapsulated.
For `onClose` it's fine, but probably `onRegister` should be encapsulated as well.  What do you think?

**Comment by delvedor** [comment] 2019-12-09 09:14
Hello! I've opened https://github.com/fastify/fastify/pull/1971 with a fix for this issue. Unfortunately, this will be a breaking change so that the fix will land only in v3.

**Comment by Eomm** [comment] 2019-12-10 21:46
I'm not sure this is a bug since `onRoute` is an application hook [as documented](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#application-hooks):

> You can hook into the application-lifecycle as well. It's important to note that these hooks aren't fully encapsulated. The this inside the hooks are encapsulated but the handlers can respond to an event outside the encapsulation boundaries.

**Comment by delvedor** [comment] 2019-12-27 16:03
Closed in https://github.com/fastify/fastify/pull/2004.

**Closed by delvedor** 2019-12-27 16:03 UTC
Labels: bug, v2.x
