### ISSUE TITLE
Typescript error This expression is not callable.

### ISSUE THREAD

**Issue by sinai-doron** [fastify/fastify#2404] opened 2020-07-11 18:32 UTC
## 🐛 Bug Report
I am getting the following error even when using fastify examples from the documentation.
`src/dist-server.ts:3:16 - error TS2349: This expression is not callable.
  Type 'typeof import("/Users/......./node_modules/fastify/fastify")' has no call signatures.`

## To Reproduce

Try running a fastify app with typescript 3.9.6

tsconfig.json
```js
{
    "compilerOptions": {
      "allowSyntheticDefaultImports": false,
      "baseUrl": "./src",
      "esModuleInterop": false,
      "importHelpers": true,
      "lib": [
        "dom",
        "esnext"
      ],
      "module": "commonjs",
      "moduleResolution": "node",
      "noImplicitAny": true,
      "noUnusedLocals": true,
      "noUnusedParameters": true,
      "outDir": "./dist",
      "preserveConstEnums": true,
      "removeComments": true,
      "sourceMap": true,
      "target": "ES2017",
      "traceResolution": false,
      "typeRoots": ["types", "node_modules/@types"],
      "experimentalDecorators": true /* Enables experimental support for ES7 decorators. */,
      "emitDecoratorMetadata": true /* Enables experimental support for emitting type metadata for decorators. */
    },
    "include": [
      "./src/**/*",
      "./src/*"
    ],
    "exclude": [
      "./node_modules/**/*",
      "**/*.spec.ts"
    ]
  }
  
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *node version*: 13.7.0
- *fastify version*: 3
-typescript 3.9.6
- *os*: Mac
- *any other relevant information*

**Comment by mcollina** [comment] 2020-07-11 18:39
We'll need a script to reproduce to help you.

**Comment by sinai-doron** [comment] 2020-07-12 05:57
I opened a git repo:
https://github.com/sinai-doron/fastify-typescript

I am getting the following errors when running `npm run build`:

```
src/index.ts:7:82 - error TS2349: This expression is not callable.
  Type 'typeof import("/Users/doronsinai/workspaces/test-typescript/node_modules/fastify/fastify")' has no call signatures.

7 const server: fastify.FastifyInstance<Server, IncomingMessage, ServerResponse> = fastify({})
                                                                                   ~~~~~~~

src/index.ts:25:21 - error TS2339: Property 'res' does not exist on type 'FastifyReply<Server, IncomingMessage, ServerResponse, RequestGenericInterface, unknown>'.

25   console.log(reply.res) // this is the http.ServerResponse with correct typings!
```

**Comment by fox1t** [comment] 2020-07-12 07:58
HI @sinai-doron! I've just checked your repository and you have to rewrite the import like this:
```typescript
import fastify, { FastifyInstance, RouteShorthandOptions } from "fastify";
import { Server, IncomingMessage, ServerResponse } from "http";

// Create a http server. We pass the relevant typings for our http version used.
// By passing types we get correctly typed access to the underlying http objects in routes.
// If using http2 we'd pass <http2.Http2Server, http2.Http2ServerRequest, http2.Http2ServerResponse>
const server: FastifyInstance<
  Server,
  IncomingMessage,
  ServerResponse
> = fastify({});

const opts: RouteShorthandOptions = {
  schema: {
    response: {
      200: {
        type: "object",
        properties: {
          pong: {
            type: "string",
          },
        },
      },
    },
  },
};

server.get("/ping", opts, (_request, reply) => {
  console.log(reply.raw); // this is the http.ServerResponse with correct typings!
  reply.code(200).send({ pong: "it worked!" });
});
```

However, I have a question for @Ethan-Arrowood: are we sure that we want to drop the use of `export =` as the entry point for fastify module? Removing it signals TypeScript that it is not a CommonJS module and therefore it makes it unsusable by `import * as fastify from 'fastify'`. Is this a wanted behavior?

**Comment by fox1t** [comment] 2020-07-12 08:00
@sinai-doron I have another question: why are you setting `allowSyntheticDefaultImports` and `esModuleInterop` both to false?

**Comment by sinai-doron** [comment] 2020-07-12 08:10
@fox1t Thank you for the fast reply, that did solve the issue.

In this case the documentation needs an update.

To your question, there is no reason, probably a leftover from trying to figure the issue.

**Comment by fox1t** [comment] 2020-07-12 08:14
Nice! I agree that that docs need an update for TS users only. 

Speaking about `esModuleInterop`, I highly encourage everyone to always enable it (you don't need to use `allowSyntheticDefaultImports` explicitly since esModuleInterop activates it) because makes life easier and has not any downsides (usually).

**Comment by mcollina** [comment] 2020-07-12 08:18
Would you like to send a Pull Request to add this to the docs?

**Comment by sinai-doron** [comment] 2020-07-12 08:20
> Would you like to send a Pull Request to add this to the docs?

Sure, I'll be glad

**Comment by fox1t** [comment] 2020-07-12 08:21
Actually the docs are correct: https://github.com/fastify/fastify/blob/master/docs/TypeScript.md

Maybe we can put an additional "alert" to point this out?

**Comment by mcollina** [comment] 2020-07-12 18:29
I would add a sample `tsconfig.json` file at the top.

**Comment by Ethan-Arrowood** [comment] 2020-07-13 15:55
> However, I have a question for @Ethan-Arrowood: are we sure that we want to drop the use of export = as the entry point for fastify module? Removing it signals TypeScript that it is not a CommonJS module and therefore it makes it unsusable by import * as fastify from 'fastify'. Is this a wanted behavior?

No I'd like to not break that at this time. I'm still trying to catch up with all the new issues; is this a proposed change?

**Comment by Ethan-Arrowood** [comment] 2020-07-13 15:58
We at least tried to solve most of the import scenarios at the beginning of the work on v3. This part of the documentation covers whats available: https://github.com/fastify/fastify/blob/master/docs/TypeScript.md#how-to-import

If something is wrong here lets identify it and try to solve it

**Comment by fox1t** [comment] 2020-07-14 22:00
Ok, I get it. What I was trying to point out is that since Fastify exports a CJS namespace that is also callable the correct way to express it in TS is with export =. All of the other ways of doing it can't cover 100% cases that are possible with CJS. On the other hand we can "force" TS users to always import without *.

**Comment by fox1t** [comment] 2020-07-14 22:01
> > However, I have a question for @Ethan-Arrowood: are we sure that we want to drop the use of export = as the entry point for fastify module? Removing it signals TypeScript that it is not a CommonJS module and therefore it makes it unsusable by import * as fastify from 'fastify'. Is this a wanted behavior?
> 
> 
> 
> No I'd like to not break that at this time. I'm still trying to catch up with all the new issues; is this a proposed change?

No it is not. It was just me making a suggestion on how to support imports with *. Sorry for the confusion! 🙏

**Comment by mcollina** [comment] 2020-07-31 06:49
what's the conclusion on this? There are more and more reports about this problem with ts on our modules.

What is the fix that we should apply everywhere?

**Comment by mfpopa** [comment] 2020-07-31 11:57
The fix is `export = fastify` and `export = fastifyCookie` and so on.

I see it has been suggested to use the `"esModuleInterop": true` flag, but I don't see the advantage. Actually, I have never built or worked on a code base where the flag has been set to true. I am curious why I would ever want to enable the flag, since it is disabled by default.

I think not supporting the **star** import makes it more difficult to upgrade from fastify v2 to v3, like I am trying to do now with a production web application.

**Comment by mcollina** [comment] 2020-08-01 10:46
Can somebody make me an example on how to fix `fastify-websocket` for example? https://github.com/fastify/fastify-websocket/issues/72. I have tried a few things and _nothing_ works, there are always errors.

**Comment by mfpopa** [comment] 2020-08-02 04:53
I just realised that the fastify function is a named export, so doing `import { fastify, FastifyInstance } from 'fastify'` will work fine regardless if the `esModuleInterop` flag is on or off.

To solve my problem, I chose to turn on the `esModuleInterop` flag and refactor all other library imports where necessary. There are still some fastify plugins that have not been upgraded to v3 (e.g. SerayaEryn/fastify-session#115). For these I had to copy and modify the types myself in the code base.

---

Looking at the ES6 specification on [star imports](http://www.ecma-international.org/ecma-262/6.0/#sec-imports) and reading [this article](https://itnext.io/great-import-schism-typescript-confusion-around-imports-explained-d512fc6769c2) about the TS star import issue, I have learnt that that the star import is meant for modules where there is no default export or the default export is not a function. TypeScript messed this up by allowing the start import to be callable, so `import * as fastify from 'fastify'` allows then to do this: `const app = fastify()`. To fix this issue, the TS team has introduced the `esModuleInterop` flag to enable compliance with the ES spec.

As things are now, the fastify plugins that have been upgraded to v3 do not work with `"esModuleInterop": false`. To allow developers to use these plugins regardless of whether `esModuleInterop` is true or false in their code base, I think each plugin needs to use both these export forms: `export default` and `export =`.

For example:

```TypeScript
...
export default fastifyStatic
export = fastifyStatic
```

**Comment by mcollina** [comment] 2020-08-02 15:02
Can both things be used at the same time? Last time I tried I was getting errors.

**Comment by mcollina** [comment] 2020-08-02 17:08
If I write the following code:


<details>

```ts
/// <reference types="node" />
import { IncomingMessage, ServerResponse, Server } from 'http';
import { FastifyPlugin, FastifyRequest, RawServerBase, RawServerDefault, RawRequestDefaultExpression, RawReplyDefaultExpression, RequestGenericInterface, ContextConfigDefault, FastifyInstance } from 'fastify';
import * as WebSocket from 'ws';
import { Duplex } from 'stream';

declare module 'fastify' {
  interface RouteShorthandOptions<
    RawServer extends RawServerBase = RawServerDefault
  > {
    websocket?: boolean;
  }

  interface FastifyInstance<RawServer, RawRequest, RawReply> {
    get: RouteShorthandMethod<RawServer, RawRequest, RawReply>
    websocketServer: WebSocket.Server,
  }

  interface RouteShorthandMethod<
    RawServer extends RawServerBase = RawServerDefault,
    RawRequest extends RawRequestDefaultExpression<RawServer> = RawRequestDefaultExpression<RawServer>,
    RawReply extends RawReplyDefaultExpression<RawServer> = RawReplyDefaultExpression<RawServer>,
  > {
    <RequestGeneric extends RequestGenericInterface = RequestGenericInterface, ContextConfig = ContextConfigDefault>(
      path: string,
      opts: RouteShorthandOptions<RawServer, RawRequest, RawReply, RequestGeneric, ContextConfig> & { websocket: true }, // this creates an overload that only applies these different types if the handler is for websockets
      handler?: WebsocketHandler
    ): FastifyInstance<RawServer, RawRequest, RawReply>;
  }

  export type WebsocketHandler = (
    this: FastifyInstance<Server, IncomingMessage, ServerResponse>,
    connection: websocketPlugin.SocketStream,
    request: IncomingMessage,
    params?: { [key: string]: any }
  ) => void | Promise<any>;
}

declare const websocketPlugin: FastifyPlugin<websocketPlugin.WebsocketPluginOptions>;

declare module websocketPlugin {
  interface SocketStream extends Duplex {
    socket: WebSocket;
  }

  interface WebsocketPluginOptions {
    handle?: (this: FastifyInstance, connection: SocketStream) => void;
    options?: WebSocket.ServerOptions;
  }
}

export default websocketPlugin;
export = websocketPlugin;
```

</details>

I get:

```
  ✖  53:0  An export assignment cannot be used in a module with other exported elements.
```

This does not seem to be possible.

**Comment by mcollina** [comment] 2020-08-02 17:17
Can any of you check if https://github.com/fastify/avvio/pull/120 would resolve the problem?

**Comment by mfpopa** [comment] 2020-08-03 03:03
> Can both things be used at the same time? Last time I tried I was getting errors.

Hmm, not sure why this did not flag up until I tried both export forms on `fastify-websocket`. Funny that VSCode does not flag this issue up when it comes to other plugins; e.g. `fastify-static`

![image](https://user-images.githubusercontent.com/1562939/89136992-3f928400-d52e-11ea-87b6-eeabc42541b6.png) ![image](https://user-images.githubusercontent.com/1562939/89137008-520cbd80-d52e-11ea-96d7-0430e91bd163.png)

So it looks like the rule is this:

- `export default` should be used for ESM default exports.
- `export =` should be used for CJS default exports.

I have created the following repository to look at how types work when `esModuleInterop` is either true or false: https://github.com/mfpopa/fastify-faux-modules

---

My conclusion is that if you want to force people to use ESM imports (`"esModuleInterop": true`), then you use the `export default` form. If you want to support `esModuleInterop` being either true or false, then use the `export =` form, like it was the case with fastify v2.

---

One last note, when using the `export =` form, there should be no other export in the file. Any other export needs to be put inside a `declare module` or `declare namespace`.

For example, if we look at the types of `fastify-websocket` v2.0.6, when changing `export default websocketPlugin` to `export = websocketPlugin`, we also need to move the `SocketStream` and `WebsocketPluginOptions` interfaces inside `declare module websocketPlugin {...}`, plus update references to these interfaces to use the `websocketPlugin.` prefix:

- `connection: SocketStream,` ==> `connection: websocketPlugin.SocketStream,` inside the `WebsocketHandler` type.
- `declare const websocketPlugin: FastifyPlugin<WebsocketPluginOptions>;` ==> `declare const websocketPlugin: FastifyPlugin<websocketPlugin.WebsocketPluginOptions>;`

I hope this all helps.

**Comment by mcollina** [comment] 2020-08-03 07:46
I have released `avvio@7.2.0`, it supports passing in objects with a `default` properties as plugins. Can somebody check if this is still an issue? Thanks.

**Comment by fox1t** [comment] 2020-08-10 10:28
@mfpopa in order to be independent of `esModuleInterop` setting we can export the plugins like this:
https://github.com/fastify/fastify-swagger/pull/282

It supports all the contexts: CJS, ESM (only for default namespace import), and TS.

**Comment by mcollina** [comment] 2020-08-10 10:30
I definitely think we can add it as a part of our docs.

**Comment by fox1t** [comment] 2020-08-11 08:04
I think we can consider this issue as resolved. @mfpopa and @sinai-doron do you still have any issues?

Speaking of the documentation part, we need to fix these chapters:
- https://www.fastify.io/docs/latest/TypeScript/#creating-a-typescript-fastify-plugin
- https://www.fastify.io/docs/latest/TypeScript/#creating-type-definitions-for-a-fastify-plugin

**Comment by mcollina** [comment] 2020-08-11 08:05
I would prefer to close this after we land the docs change.

(Good work everbody!)

**Comment by fox1t** [comment] 2020-08-12 17:06
This can be closed now.

**Closed** 2020-08-12 17:24 UTC
Labels: discussion, documentation, typescript, v3.x

**Comment by vgmadhu** [comment] 2021-09-14 16:34
I have this same issue with fastify: 3.20.2

```
index.ts:7:11 - error TS2349: This expression is not callable.
  Type 'typeof import("fastify")' has no call signatures.

  const f = fastify();
```

Here's my tsconfig.json
```json
{
  "compilerOptions": {
    "declaration": true,
    "moduleResolution": "node",
    "module": "commonjs",
    "baseUrl": ".",
    "outDir": "./built",
    "allowJs": true,
    "target": "es5",
    "esModuleInterop": true,
    "sourceMap": true,
    "traceResolution": false,
    "lib": [
      "dom",
      "esnext"
    ],
    "paths": {
      "*": ["./@types/*"]
    },
    "typeRoots": ["@types", "node_modules/@types"]
  },
  "include": ["./**/*"],
  "exclude": ["./node_modules/**/*", "**/*.spec.ts", "./built/**/*"]
}
```

**Comment by lovejlc2008** [comment] 2022-03-25 06:43
If you use 
import { Component } from 'vue-class-component'
There will give you a bug: Module '"vue-class-component"' has no exported member 'Component'.

But use
import { Options } from 'vue-class-component'
and
@Options({
  beforeRouteEnter (to: any, from: any, next: () => void) {
    console.log('beforeRouteEnter ')
    next()
  }
})
Oh, it's working

**Comment by lovejlc2008** [comment] 2022-03-25 06:45
If you use
`import { Component } from 'vue-class-component'`
There will give you a bug: 
Module '"vue-class-component"' has no exported member 'Component'.

But use
`import { Options } from 'vue-class-component'`
and
```
@options({
  beforeRouteEnter (to: any, from: any, next: () => void) {
    console.log('beforeRouteEnter ')
    next()
  }
})
```
Oh, it's working

**Comment by lovejlc2008** [comment] 2022-03-25 06:46
If you use
`import { Component } from 'vue-class-component'`
There will give you a bug:
Module '"vue-class-component"' has no exported member 'Component'.

But use
`import { Options } from 'vue-class-component'`
and
```
@Options({
  beforeRouteEnter (to: any, from: any, next: () => void) {
    console.log('beforeRouteEnter ')
    next()
  }
})
```
Oh, it's working

**Comment by Igloczek** [comment] 2023-03-01 13:23
Doing `import { fastify } from 'fastify'` solved the problem for me in TS project.

Kudos to https://github.com/fastify/fastify/issues/2404#issuecomment-667627284
