### ISSUE TITLE
Incorrect usage of the Error class

### ISSUE THREAD

**Issue by slavafomin** [fastify/fastify#4998] opened 2023-08-26 15:36 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

Latest

### Node.js version

Any

### Operating system

Any

### Operating system version (i.e. 20.04, 11.3, 10)

Any

### Description

When working with errors (for example during validation), fastify incorrectly uses the `Error` class instances by specifying the additional properties that doesn't belong to the class. See here: https://github.com/fastify/fastify/blob/main/lib/validation.js#L222-L224

The `Error` interface is defined this way:

```
interface Error {
    name: string;
    message: string;
    stack?: string;
}
```

Adding any other properties to it directly should be considered a mistake.

This causes an inconvenience and a type safety violation when working on the application code. Consider this custom error handler:

![Screenshot_2023-08-26_18-25-00](https://github.com/fastify/fastify/assets/1702725/0fe4ff5c-8a13-4172-a2c2-d89c047194b6)

You can't just access the added properties in your TypeScript code due to the violation of the Error class interface. So in order to use this property, you either need to cast `Error` to `any` first or use the `in` operator:

![Screenshot_2023-08-26_18-38-35](https://github.com/fastify/fastify/assets/1702725/3df4e4f1-373e-42a2-86b8-ab7e1a4a7b6a)

However this defeats the purpose of the type safety.

### Steps to Reproduce

Just try to access any additional properties added to the `Error` instance in your TypeScript user code.

### Expected Behavior

The much better solution would be to create a custom error classes that would extend the `Error` class and would add any additional properties/methods or behavior:

```typescript

export class HttpError extends Error {
  statusCode = 500;
  // etc …
}

export class ValidationError extends HttpError {
  statusCode = 400;
  // etc …
  constructor(validation) {
    this.validation = validation;
    // etc …
  }
}

```

Not only this will provide a sound type safety, but it will also simplify the code, because you won't be needing the "error codes" (like `FST_ERR_VALIDATION`) anymore, because the class will identify the error directly.

So the user code could be simplified as:

```typescript
if (error instanceof ValidationError) {
  console.log(error.validation);
}
```

**Comment by mcollina** [comment] 2023-08-27 11:54
Thanks for your reporting. It shows a real problem when implementing a setErrorHandler with typescript.

However, your post is full of full of incorrect assumptions about JavaScript and Node.js.

The first reason why we use error codes is (among others) the fact that they are basic strings. Given that Node.js does not guarantee (for good reasons) that two instances of the same module are identical (they can even be different versions), you cannot rely on `instanceof` across different packages.

The second reason is that error codes are unique and easy to google. The code property is also defined in _all_ Node.js core errors, and we follow their example.

The third reason is that types are just sugar. There is no incorrect usage in _adding a property_ in JavaScript. It's what makes this language special.

Having said all of that, I think we should re-evaluate how to improve the typings in this case.

**Comment by climba03003** [comment] 2023-08-27 19:01
> Having said all of that, I think we should re-evaluate how to improve the typings in this case.

There is nothing wrong in our types.
The only problem is the author explicitly type it as `unknown` and want TypeScript to identify the types correctly using `instanceof`.

So, I will close it since it is a TypeScript question, not fastify question.

**Comment by slavafomin** [comment] 2023-08-28 12:48
> Thanks for your reporting. It shows a real problem when implementing a setErrorHandler with typescript.
> 
> However, your post is full of full of incorrect assumptions about JavaScript and Node.js.

They are not assumptions about JS or Node specifically. My remarks are just based on the best practices of modern software development, which can't be achieved without a static code analysis :)


> The first reason why we use error codes is (among others) the fact that they are basic strings. Given that Node.js does not guarantee (for good reasons) that two instances of the same module are identical (they can even be different versions), you cannot rely on `instanceof` across different packages.

That could be a valid point, however, if the dependencies system is used correctly, there is no way for two different packages to be used at the same time. And even if this happens, there could be a much serious implications than error classes mismatch :)

> The second reason is that error codes are unique and easy to google. The code property is also defined in _all_ Node.js core errors, and we follow their example.

I don't really think that Node.js codebase is a good place to take examples from :)

> The third reason is that types are just sugar. There is no incorrect usage in _adding a property_ in JavaScript. It's what makes this language special.

I really love the JavaScript, but this doesn't make it "special", it just makes it awful and very dangerous :)

> Having said all of that, I think we should re-evaluate how to improve the typings in this case.

I'm not really against using strings to identify the error types, however, it limits the expressiveness of your errors if you are using a single error class for all possible errors. You could use both: just define a root error class like `FastifyError`, add `code` property to it and make sure to throw it everywhere in the codebase. Then you could create a sub-classes when you need to add extra properties, like `ValidationError extends FastifyError` with additional `validation` property. It will work well both for JS and the TypeScript and it will be backward-compatible.

**Comment by jsumners** [comment] 2023-08-28 12:53
> there is no way for two different packages to be used at the same time.

Not true. See https://github.com/fastify/fastify-error/pull/86#issuecomment-1301466407

**Comment by slavafomin** [comment] 2023-08-28 13:00
> [](https://github.com/fastify/fastify-error/pull/86#issuecomment-1301466407)

You've omitted an important part of my sentence, what I said is:
> **if the dependencies system is used correctly**, there is no way for two different packages to be used at the same time

The provided example is contrived. Of course you will get two different classes if you would load it from different `node_modules` directories. This doesn't contradict what I've said above. I don't know what case you were trying to show, it looks like monorepo example of sorts. If so, you would need a proper tool to manage your monorepo, like `pnpm`. It will deduplicate your dependencies and it will work correctly.

**Comment by jsumners** [comment] 2023-08-28 13:13
It is not contrived. It is a minimal reproduction of modules and how their dependencies are installed by package managers.

> you would need a proper tool

Please stop asserting that your preferences are the only "correct" ones.

**Comment by slavafomin** [comment] 2023-08-28 13:20
> The only problem is the author explicitly type it as `unknown` and want TypeScript to identify the types correctly using `instanceof`.

You actually have to type it as `uknown`, because in the `catch` handler you don't know what you are catching, it could be anything. In some weird cases it could even be a `string` instead of `Error`. After that you need to narrow the types by applying some conditions and the `instanceof` operator is a best way to provide this type narrowing because it will filter errors at runtime and it will provide a correct type at compilation time.

**Comment by climba03003** [comment] 2023-08-28 13:34
> You actually have to type it as uknown, because in the catch handler you don't know what you are catching, it could be anything. In some weird cases it could even be a string instead of Error.

Actually, we always throwing `Error` in the same structure.
If there is something not in `Error`, it should be either user planned to do so or some package they are using doing it.
It can be solved by wrapping in `try-catch` for the third party packages.

Anyway, all the above conversation is telling the user to prevent using `instanceof`.
So, the proper way for TypeScript should be using helper function.
```ts
function isFastifyErrorLike(err: unknown): err is FastifyError {
  return err !== null && typeof err === 'object' && 'code' in err && typeof err.code === 'string'
}
```

**Comment by slavafomin** [comment] 2023-08-28 13:35
> No, I ignored the "I know better than everyone" nonsense.
> Please stop asserting that your preferences are the only "correct" ones.

There is nothing opinionated about the things that I'm saying. All my suggestions are based on the real properties of the systems in question and the industry standards. However, your behavior look undeservedly aggressive for no reason.

> It is not contrived. It is a minimal reproduction of modules and how their dependencies are installed by package managers.

Using `file://` scheme to reference dependencies in your `package.json` IS contrived (and unprofessional). The accepted industry standard is to use monorepo managers for such cases, it's not "my preferences", it's approach used by Facebook, Microsoft and a lot of other serious companies.

If you would use a right tool for the job (`pnpm`, `rush`, `lerna` etc) and a correct dependency specifications (like `peerDependencies`) than everything will be OK. Trying to solve the problem for a user who has bad dependency management practices is a lost cause, because you won't be able to do it properly and it will make things worse in the long run.

**Comment by slavafomin** [comment] 2023-08-28 13:44
And, by the way, if the user is afraid of such class identity mismatch she could always do something like this:

```js
if (error.constructor.name === 'ValidationError') {
}
```

It will work even for the case that @jsumners has mentioned.

**Comment by slavafomin** [comment] 2023-08-28 14:04
> ```ts
> function isFastifyErrorLike(err: unknown): err is FastifyError {
>   return err !== null && typeof err === 'object' && 'code' in err && typeof err.code === 'string'
> }
> ```

Sure, a good type guard workaround.

I would've added the `startsWith('FST_ERR_')` there to be even more selective :)

However, having each TS developer to write this boilerplatish code is not very nice DX, it should be much simpler.

**Comment by slavafomin** [comment] 2023-08-28 14:23
I will probably stop bugging you with my undesired opinion, sorry for that :)

I will just leave it here for someone who will be in my shoes:

```ts
import { FastifyError, FastifyErrorCodes } from 'fastify';

export function isFastifyError(
  error: unknown,
  code?: (keyof FastifyErrorCodes)

): error is FastifyError {

  return (
    (typeof error === 'object') &&
    (error !== null) &&
    ('code' in error) &&
    (typeof error.code === 'string') &&
    error.code.startsWith('FST_ERR_') &&
    (code ? (error.code === code) : true)
  );

}
```

**Usage:**

```ts
if (isFastifyError(error) {
  // @todo handle generic error
}

if (isFastifyError(error, 'FST_ERR_VALIDATION')) {
  // @todo handle validation error
}
```

This will work with the strictest TypeScript settings and will ensure error code type safety.

**Comment by mcollina** [comment] 2023-08-28 14:38
> If so, you would need a proper tool to manage your monorepo, like pnpm. It will deduplicate your dependencies and it will work correctly.

Only in the happy path scenario and by using _a lot_ of peerDependencies. The success of npm comes from allowing multiple version of the same library to be installed at the same time. Breaking that assumption creates so much friction and problems.

**Comment by Uzlopak** [comment] 2023-08-28 14:40
Imho move this issue to fastify/help and discuss it further if you feel it needs more elaboration.

**Comment by sergburn** [comment] 2023-09-01 13:23
Well, IMHO the following much simpler check is enough:

```ts
function isFastifyError(err: unknown): err is FastifyError {
  return err instanceof Error && err.name === 'FastifyError';
}
```
The first condition covers the trivia. Then, it is unlikely that there is another package in a project, which also creates "FastifyError" errors, but even if so, no other checks (even `code.startsWith('FST_')`) provide any more safety guarantees. 

I see no point in checking `.code` property in the type guard at all, because in typical scenario one uses it as some kind of decision-making value and absent `code` in the end is equivalent to unknown one. 

```ts
try {
  // ...
} catch (err) { // unknown
  if (isFastifyError(err)) {
    if (err.code === 'FST_ERR_CTP_EMPTY_JSON_BODY') {
      throw new MyError(myTextForEmptyBody, { cause: err });
    } else {
      // also in case when `.code` doesn't exist
      throw new MyError(myTextForAllOtherCases, { cause: err });
    }
```

Please correct me if I'm wrong.

**Comment by Uzlopak** [comment] 2023-09-01 14:53
@sergburn 
I agree with your assessment. Your isFastifyError seems to be the best one I saw for now.

**Comment by pozorfluo** [comment] 2024-01-26 09:59
> Well, IMHO the following much simpler check is enough:
> 
> ```ts
> function isFastifyError(err: unknown): err is FastifyError {
>   return err instanceof Error && err.name === 'FastifyError';
> }

Hi,

it seems that `err.name` isn't always set to `FastifyError`, e.g. when some query parameters fails validation, I'm getting some plain Error and `err.name` is `Error` unfortunately.

**Comment by Uzlopak** [comment] 2024-01-26 10:31
To detect it somehow reliable, you would need to do something like

function isFastifyError(err: unknown): err is FastifyError {
  return err && Object.prototype.toString(err) === '[object FastifyError]';
}

**Comment by sergburn** [comment] 2024-01-27 09:56
I'd say it's a bug somewhere.

@pozorfluo , could you check `error.stack` to find out where this improperly created exception is thrown from?

**Comment by pozorfluo** [comment] 2024-01-29 08:56
@sergburn 


Here is the error name and stack :

```
    error name : 
     Error

    error stack : 
     Error: querystring must have required property 'someKey'
        at defaultSchemaErrorFormatter (/Users/spagbol/_source/demo-fastify/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/context.js:114:10)
        at wrapValidationError (/Users/spagbol/_source/demo-fastify/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/validation.js:228:17)
        at validate (/Users/spagbol/_source/demo-fastify/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/validation.js:157:16)
        at preValidationCallback (/Users/spagbol/_source/demo-fastify/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/handleRequest.js:91:25)
        at handler (/Users/spagbol/_source/demo-fastify/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/handleRequest.js:75:7)
        at handleRequest (/Users/spagbol/_source/demo-fastify/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/handleRequest.js:24:5)
        at runPreParsing (/Users/spagbol/_source/demo-fastify/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/route.js:593:5)
        at Object.routeHandler [as handler] (/Users/spagbol/_source/demo-fastify/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/lib/route.js:514:7)
        at Router.callHandler (/Users/spagbol/_source/demo-fastify/node_modules/.pnpm/find-my-way@7.7.0/node_modules/find-my-way/index.js:548:14)
        at Router.lookup (/Users/spagbol/_source/demo-fastify/node_modules/.pnpm/find-my-way@7.7.0/node_modules/find-my-way/index.js:526:17)
        at preRouting (/Users/spagbol/_source/demo-fastify/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/fastify.js:868:14)
        at /Users/spagbol/_source/demo-fastify/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/fastify.js:561:11
        at /Users/spagbol/_source/demo-fastify/node_modules/.pnpm/fastify@4.25.2/node_modules/fastify/fastify.js:595:44
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Here is the route configuration used :

```js
  app.route({
    method: 'GET',
    url: '/',
    schema: {
      querystring: {
        type: 'object',
        properties: {
          someKey: { type: 'string' },
        },
        required: ['someKey'],
      },
    },
    handler: async function get(request, reply) {
      return { someResult: 'ok' };
    },
  });
```


As a workaround I'm setting a custom SchemaErrorFormatter, e.g. `defaultSchemaErrorFormatter`
but setting err.name to 'FastifyError' :

```js
export const schemaErrorFormatter: SchemaErrorFormatter = function (errors, dataVar) {
  let text = '';
  const separator = ', ';

  for (let i = 0; i !== errors.length; ++i) {
    const e = errors[i];
    text += dataVar + (e.instancePath || '') + ' : ' + e.message + separator;
  }

    const err = new Error(text.slice(0, -separator.length));
    err.name = 'FastifyError';
    return err;
};
```

**Comment by Uzlopak** [comment] 2024-01-29 09:01
Reopening. Needs further investigation.

**Comment by climba03003** [comment] 2024-01-29 09:13
> Reopening. Needs further investigation.

I don't think it needs investigation. 
We never claim the `Error` must be `FastifyError` if it is throw by `fastify`.
Re-creation of `Error` all the time is slow (due to stack trace capturing), instead we modify the property of existing error.
It should be a guarantee the error thrown by `fastify` provide `.code` and start with `FST_`

**Closed** 2024-01-30 20:51 UTC
