### ISSUE TITLE
fastify behind haproxy results into "read ECONNRESET" errors

### ISSUE THREAD

**Issue by xpender** [fastify/fastify#2036] opened 2020-01-09 08:31 UTC
## 🐛 Bug Report

As mentioned in https://github.com/fastify/fastify/blob/master/docs/Recommendations.md we would like to run fastify behind haproxy (for TLS termination and load balancing)

After processing an request proxied over haproxy it throws an ECONNRESET error:

```
{"level":30,"time":1578524093038,"pid":16376,"hostname":"ip-10-64-1-175","reqId":1,"req":{"method":"GET","url":"/check","hostname":"localhost","remoteAddress":"127.0.0.1","remotePort":42838},"msg":"incoming request","v":1}
{"level":30,"time":1578524093045,"pid":16376,"hostname":"ip-10-64-1-175","reqId":1,"res":{"statusCode":200},"responseTime":5.577713999897242,"msg":"request completed","v":1}
{"level":20,"time":1578524093046,"pid":16376,"hostname":"ip-10-64-1-175","err":{"type":"Error","message":"read ECONNRESET","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:200:27)","errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"},"msg":"client error","v":1}
{"level":30,"time":1578524101311,"pid":16376,"hostname":"ip-10-64-1-175","reqId":2,"req":{"method":"GET","url":"/check","hostname":"localhost","remoteAddress":"127.0.0.1","remotePort":42842},"msg":"incoming request","v":1}
{"level":30,"time":1578524101311,"pid":16376,"hostname":"ip-10-64-1-175","reqId":2,"res":{"statusCode":200},"responseTime":0.34771000035107136,"msg":"request completed","v":1}
{"level":20,"time":1578524101311,"pid":16376,"hostname":"ip-10-64-1-175","err":{"type":"Error","message":"read ECONNRESET","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:200:27)","errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"},"msg":"client error","v":1}
``` 

If I bypass haproxy and call directly the NodeJS process this is not happening:

```
{"level":30,"time":1578524117357,"pid":16376,"hostname":"ip-10-64-1-175","reqId":3,"req":{"method":"GET","url":"/check","hostname":"localhost:8337","remoteAddress":"127.0.0.1","remotePort":42850},"msg":"incoming request","v":1}
{"level":30,"time":1578524117357,"pid":16376,"hostname":"ip-10-64-1-175","reqId":3,"res":{"statusCode":200},"responseTime":0.4655680004507303,"msg":"request completed","v":1}
{"level":30,"time":1578524120839,"pid":16376,"hostname":"ip-10-64-1-175","reqId":4,"req":{"method":"GET","url":"/check","hostname":"localhost:8337","remoteAddress":"127.0.0.1","remotePort":42852},"msg":"incoming request","v":1}
{"level":30,"time":1578524120840,"pid":16376,"hostname":"ip-10-64-1-175","reqId":4,"res":{"statusCode":200},"responseTime":0.3121840003877878,"msg":"request completed","v":1}
```

Error is triggered via HTTP.Server 'clientError' - logged at https://github.com/fastify/fastify/blob/master/fastify.js#L417 - also I would ask why errors are just logged as "debug" severity?

## To Reproduce

To exclude other possible errors like network issues node and haproxy are running on the same machine.

As HTTP client for testing I used cmd line CURL on same machine. I could reproduce the same also with links & lynx browser on CMD line. Also it was reproducible from remote.

1. Node with fastify on Port 8337 (simple.ts)
2. Haproxy with haproxy.cfg on Port 80
3. "curl http://localhost/check" (over haproxy, causes that issue)
4. "curl http://localhost:8337/check" (directly NodeJS, no issue)

(Error is only logged on logger level >= debug)

*simple.ts*
```js
import * as fastify from 'fastify';

const app = fastify({
    logger: {
        level: 'trace',
    },
    trustProxy: true,
});

app.get('*', (_req, reply) => {
    reply.send('foo');
});

app.listen(8337, '0.0.0.0');
```

*haproxy.cfg* (reduced version out of Recommendations.md)
```haproxy
global
  log /dev/log syslog
  maxconn 4096
  chroot /var/lib/haproxy
  user haproxy
  group haproxy

defaults
  log   global
  mode  http
  option        httplog
  option        dontlognull
  option forwardfor
  retries       3
  option redispatch
  maxconn       2000
  timeout connect 5000
  timeout client 50000
  timeout server 50000

frontend proxy
  bind 0.0.0.0:80
  default_backend fastify

backend fastify
  server local 127.0.0.1:8337
```

## Expected behavior

I also tested if this also occurs with just node HTTP.server implementation, I couldn't reprodue it. Also I couldn't see this behavior with express.js.

There should be no "Error: read ECONNRESET\n    at TCP.onStreamRead"

Looks for me if something is trying to read on a already ended connection?

## Your Environment

- *node version*: 12.14.1
- *fastify version*: 2.11.0
- *os*: Linux, debian buster - also reproduced on Mac
- *haproxy version*: 1.8.19-1+deb10u1
- *curl version*: 7.64.0
- *any other relevant information*

**Comment by mcollina** [comment] 2020-01-09 09:49
That is a debug error because it happens on a truncated socket. Your HAPRoxy is maintaining a live connection to the server which times out at 50s (from your config), which results in `clientError` to be emitted and that error logged at debug level - it's not a real error, but something that you might want to triage/diagnose.

You can get the same value from express or node core by listening to the `'clientError'` event.

**Comment by jsumners** [comment] 2020-01-09 12:48
You probably want to add `option http-server-close` to the `defaults` section. This should also be added to the example config in the recommendations doc. Would you care to send a PR @xpender?

**Comment by gtolarc** [comment] 2020-04-28 10:04
I am having the same issue. However, in my case, this problem occurs when a fastify server is uploaded to kubernetes on the cloud as pod, not on the local haproxy.

The following article may be little related, and the problem is that this happens when the fastify server runs behind proxy. (Of course, I'm using a version of kubernetes where the following issue is resolved.)
https://kubernetes.io/blog/2019/03/29/kube-proxy-subtleties-debugging-an-intermittent-connection-reset/

And if I change the coding to the express server in the same environment, I don't get an error. I want to know what the exact reason is. @mcollina

**Comment by mcollina** [comment] 2020-04-28 10:31
@gtolarc Are you trying to capture the `'clientError'` in express? Can you confirm that is not emitted? Uploading the express vs fastify code would be interesting.

---

To provide a bit more context

>  also I would ask why errors are just logged as "debug" severity?

Because this is not an error. Essentially there is nothing a developer can do as the socket get truncated for whatever reason. Increasing the level will be confusing for most people.

**Comment by gtolarc** [comment] 2020-04-28 10:55
I didn't know that express doesn't listen for clientError events by default.
I just modified the basic example of each framework and put it back on kubernetes.

```
const express = require('express');
const http = require('http');
const app = express();
const port = 3000;
const server = http.createServer(app);
server.on('clientError', function (err) {
  console.error('on clientError handler');
  console.error(err);
});
app.get('/', (req, res) => res.send('Hello World!'));
server.listen(port, () => console.log(`Example app listening at http://localhost:${port}`));
```
```
const fastify = require('fastify')({logger: { level: debug }})
fastify.get('/', (request, reply) => {
  reply.send({ hello: 'world' })
})
fastify.listen(3000, (err, address) => {
  if (err) throw err
  fastify.log.info(`server listening on ${address}`)
})
```

Oh.. as you said, I saw the same error on express.
If these socket disconnection errors are common on the proxy, I think it's probably right to fastify to ignore those errors by default. What do you think? @mcollina

**Comment by gtolarc** [comment] 2020-04-28 11:00
In fact, there are a lot of places that use Kubernetes these days, and even during development, debug logs are turned on and put on the cloud for testing. People like me who are trying to fastify for the first time will be confused from the beginning..

**Comment by mcollina** [comment] 2020-04-28 11:13
The problem is that it’s impossible to know if those are legit problems or not without looking at them. If there are a lot, they imply that there is something to be fixed in the proxy. Even if they happen, they are not really causing production issues.

Fastify is doing the correct thing in logging these out.

**Comment by gtolarc** [comment] 2020-04-28 11:23
I am using ali cloud's managed kubernates service, and even if I create a new kubernates cluster and upload the basic example of the fastify server as pod, the ECONNRESET error occurs immediately in large quantities.

There may be problems with the proxy, so detecting clientError events by default seems to confuse users like me.

**Comment by mcollina** [comment] 2020-04-28 11:35
I think we should move that log messages to the `.trace` level, and then investigate what config needs to be placed in Kubernetes to avoid this.

**Comment by wopol** [comment] 2020-04-29 17:51
I had very similar problem with my application behind ingress-controller. I succesded found problem thank to express.js. Fastify on clientError returns always 400 response code, but we have two options in this case: 400 or 431 http code (https://nodejs.org/api/http.html#http_event_clienterror).

@xpender please try to add ``--max-http-header-size`` flag to node, probably in your case haproxy adds some headers to request and node.js isn't able to handle this request because headers size is to big.

**Comment by mcollina** [comment] 2020-04-30 18:22
Thanks @wopol! I think it makes things pretty clear if increasing the headers make it reliable. We should just document why this is happening and how to fix (increase the headers limit).

**Comment by jsumners** [comment] 2020-04-30 19:21
I have this issue saved to my notifications to address with a PR to the recommendation doc. I _might_ get to it this weekend.

**Comment by ShogunPanda** [comment] 2020-05-08 07:22
While debugging this issue, I think the problem is actually in Node.js itself.

I've tried executing this sample server:

```javascript
const { createServer } = require('http');

const server = createServer((req, res) => {
    res.writeHead(200, {'Content-Length': 2}).end('OK');
})

server.on('clientError', (err, socket) => {
    console.log('CLIENT ERROR');
    socket.end('HTTP/1.1 400 Bad Request\r\n\r\n');
});

server.listen(8331);
```

With the following haproxy configuration:

```
global
  log stdout format raw local1
  maxconn 4096

defaults
  log   global
  mode  http
  option        httplog
  option        dontlognull
  option forwardfor
  retries       3
  option redispatch
  maxconn       2000
  timeout connect 5000
  timeout client 50000
  timeout server 50000

frontend proxy
  bind 0.0.0.0:8330
  default_backend fastify

backend fastify
  server local 127.0.0.1:8331
````

And this the tcpdump output I get:

```
09:09:15.258155 IP localhost.56921 > localhost.8331: Flags [S], seq 92260053, win 65535, options [mss 16344,nop,wscale 6,nop,nop,TS val 1497036589 ecr 0,sackOK,eol], length 0
09:09:15.258207 IP localhost.8331 > localhost.56921: Flags [S.], seq 383291530, ack 92260054, win 65535, options [mss 16344,nop,wscale 6,nop,nop,TS val 1497036589 ecr 1497036589,sackOK,eol], length 0
09:09:15.258214 IP localhost.56921 > localhost.8331: Flags [.], ack 1, win 6379, options [nop,nop,TS val 1497036589 ecr 1497036589], length 0
09:09:15.258219 IP localhost.8331 > localhost.56921: Flags [.], ack 1, win 6379, options [nop,nop,TS val 1497036589 ecr 1497036589], length 0
09:09:15.258243 IP localhost.56921 > localhost.8331: Flags [P.], seq 1:145, ack 1, win 6379, options [nop,nop,TS val 1497036589 ecr 1497036589], length 144
09:09:15.258249 IP localhost.8331 > localhost.56921: Flags [.], ack 145, win 6377, options [nop,nop,TS val 1497036589 ecr 1497036589], length 0
09:09:15.258610 IP localhost.8331 > localhost.56921: Flags [P.], seq 1:102, ack 145, win 6377, options [nop,nop,TS val 1497036589 ecr 1497036589], length 101
09:09:15.258620 IP localhost.56921 > localhost.8331: Flags [.], ack 102, win 6378, options [nop,nop,TS val 1497036589 ecr 1497036589], length 0
09:09:15.788795 IP localhost.56925 > localhost.8331: Flags [S], seq 3604383163, win 65535, options [mss 16344,nop,wscale 6,nop,nop,TS val 1497037110 ecr 0,sackOK,eol], length 0
09:09:15.788833 IP localhost.8331 > localhost.56925: Flags [S.], seq 2928642173, ack 3604383164, win 65535, options [mss 16344,nop,wscale 6,nop,nop,TS val 1497037110 ecr 1497037110,sackOK,eol], length 0
09:09:15.788841 IP localhost.56925 > localhost.8331: Flags [.], ack 1, win 6379, options [nop,nop,TS val 1497037110 ecr 1497037110], length 0
09:09:15.788846 IP localhost.8331 > localhost.56925: Flags [.], ack 1, win 6379, options [nop,nop,TS val 1497037110 ecr 1497037110], length 0
09:09:15.788860 IP localhost.56925 > localhost.8331: Flags [P.], seq 1:145, ack 1, win 6379, options [nop,nop,TS val 1497037110 ecr 1497037110], length 144
09:09:15.788874 IP localhost.8331 > localhost.56925: Flags [.], ack 145, win 6377, options [nop,nop,TS val 1497037110 ecr 1497037110], length 0
09:09:15.789181 IP localhost.8331 > localhost.56925: Flags [P.], seq 1:102, ack 145, win 6377, options [nop,nop,TS val 1497037110 ecr 1497037110], length 101
09:09:15.789224 IP localhost.56925 > localhost.8331: Flags [.], ack 102, win 6378, options [nop,nop,TS val 1497037110 ecr 1497037110], length 0
09:09:16.857934 IP localhost.56929 > localhost.8331: Flags [S], seq 1133802845, win 65535, options [mss 16344,nop,wscale 6,nop,nop,TS val 1497038171 ecr 0,sackOK,eol], length 0
09:09:16.858010 IP localhost.8331 > localhost.56929: Flags [S.], seq 985407293, ack 1133802846, win 65535, options [mss 16344,nop,wscale 6,nop,nop,TS val 1497038171 ecr 1497038171,sackOK,eol], length 0
09:09:16.858016 IP localhost.56929 > localhost.8331: Flags [.], ack 1, win 6379, options [nop,nop,TS val 1497038171 ecr 1497038171], length 0
09:09:16.858036 IP localhost.8331 > localhost.56929: Flags [.], ack 1, win 6379, options [nop,nop,TS val 1497038171 ecr 1497038171], length 0
09:09:16.858063 IP localhost.56929 > localhost.8331: Flags [P.], seq 1:145, ack 1, win 6379, options [nop,nop,TS val 1497038171 ecr 1497038171], length 144
09:09:16.858091 IP localhost.8331 > localhost.56929: Flags [.], ack 145, win 6377, options [nop,nop,TS val 1497038171 ecr 1497038171], length 0
09:09:16.858938 IP localhost.8331 > localhost.56929: Flags [P.], seq 1:102, ack 145, win 6377, options [nop,nop,TS val 1497038172 ecr 1497038171], length 101
09:09:16.858975 IP localhost.56929 > localhost.8331: Flags [.], ack 102, win 6378, options [nop,nop,TS val 1497038172 ecr 1497038172], length 0
09:09:16.862716 IP localhost.56929 > localhost.8331: Flags [R.], seq 145, ack 102, win 6378, length 0
```

As you can see, neither haproxy neither node are sending a FIN packet. Haproxy instead sends a RST which results in the client error on the node side.

I've filed the following issue in Node to address the problem: https://github.com/nodejs/node/issues/33302

Hope this helps!

**Closed** 2020-05-08 13:05 UTC
Labels: documentation, good first issue
