### ISSUE TITLE
Redirect http to https

### ISSUE THREAD

**Issue by borodadada** [fastify/fastify#1556] opened 2019-03-27 07:34 UTC
Hello, how create redirect http to https? My site use https only.

**Comment by Ethan-Arrowood** [comment] 2019-03-27 15:02
When you create your Fastify server instance you can enable `https` with the `https` option. See our [documentation](https://www.fastify.io/docs/latest/Server/#https) for more details.

**Comment by borodadada** [comment] 2019-03-27 15:31
This my server
`
const fastify = require('fastify')({
    logger: false,
    http2: true,
    https: {
        key: fs.readFileSync(path.join(serverDirectory, '/certificate/', 'key.pem')),
        cert: fs.readFileSync(path.join(serverDirectory, '/certificate/', 'cert.pem'))
    }
});
`
Chrome Audit said - Does not redirect HTTP traffic to HTTPS
Whats my problem?

**Comment by jsumners** [comment] 2019-03-27 16:20
There is no way we can answer your question because we do not know what your infrastructure looks like. I can tell you what I would have done in my days as a system admin: perform the redirect at the proxy server; specifically via HAProxy.

**Comment by mcollina** [comment] 2019-03-27 16:24
I think we can do a fastify plugin that intercepts all http requests and redirect them to https. It should be simple to write.

**Comment by jsumners** [comment] 2019-03-27 19:14
I don't see how. You'd have to listen on two ports at once: one for HTTP and one for HTTPS. You can't receive a normal HTTP request on an HTTPS enabled server because the TLS handshake must occur before you would ever get to any code that could inspect headers. And if you _do_ start up a separate HTTP server to do the forwarding, well, you'd still have to have some proxy server in place to manage the requests to the two servers.

**Comment by mcollina** [comment] 2019-03-27 19:33
You have to listen to both ports, and check if `req.connection` is a TLS socket. If that's the case you issue a redirect adding an `https` to the domain in the `Host` header.

Now, fastify can only listen to a single port.

---

However I don't think this is the case. Specifically because the server in https://github.com/fastify/fastify/issues/1556#issuecomment-477211048 should only listen to https. So, there is _no way_ it can receive non-encrypted content in the browser.

@borodadada can you please provide the steps to reproduce?

**Comment by Ezeon** [comment] 2019-03-31 15:35
@borodadada 

I do something similar in my app my running two fastify instances, one on port 80 and one on port 443. You could dedicate the fastify instance on port 80 to just redirect to https.

Code would look like this:
`const fastify = require('fastify')({
    logger: false,
    http2: true,
    https: {
        key: fs.readFileSync('/path/key.pem'),
        cert: fs.readFileSync('/path/cert.pem')
    }
});
fastify.listen(443);
const fastify2 = fastify();
fastify2.listen(80);
`

**Comment by borodadada** [comment] 2019-03-31 16:10
i understand need server 2 + redirect? thanks

**Comment by tomsvogel** [comment] 2019-10-16 23:15
@mcollina can you take a look at ? https://github.com/tomsvogel/fastify-https-redirect

**Comment by mcollina** [comment] 2019-10-17 10:54
Fastify does not offer to listen to multiple ports. If we want to support http -> https redirects, we would need to support multiple ports, one for http and one for https.
I think the plugin should support an “httpPort” option, and it should start another sub-server listening on that port with the sole logic to send that redirect.

**Comment by tomsvogel** [comment] 2019-10-17 11:56
so the plugin should add the second fastify server not the developer starts a second server with the plugin for the redirect ?

**Comment by mcollina** [comment] 2019-10-17 12:27
I would say so, yes. I think you might use pure Node core as well.

Il giorno gio 17 ott 2019 alle 13:56 Thomas Vogel <notifications@github.com>
ha scritto:

**Comment by tomsvogel** [comment] 2019-10-21 22:24
@mcollina i did a fixup... https://github.com/tomsvogel/fastify-https-redirect

**Comment by mcollina** [comment] 2019-10-23 08:23
Perfect! Would you mind sending a PR to add it to the ecosystem list?

**Comment by tomsvogel** [comment] 2019-10-23 09:18
yes.

**Comment by tomsvogel** [comment] 2019-10-28 07:11
close this?

**Comment by mcollina** [comment] 2019-10-28 07:29
yes, thanks

**Closed** 2019-10-28 07:28 UTC
Labels: good first issue, plugin suggestion
