### ISSUE TITLE
Support passing `Promise<{ default: RouteHandler }>` to register routes

### ISSUE THREAD

**Issue by u3u** [fastify/fastify#4650] opened 2023-03-30 14:45 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Just like registering plugins with `fastify.register`

```ts
server.register(import('./routes'))
```

Example:

```ts
import { type FastifyPluginAsync } from 'fastify'

export const routes: FastifyPluginAsync = async (server) => {
  server.get('/ping', import('./ping'))
  server.get('/test-openai', import('./test-openai'))
}

export default routes

```

### Motivation

I hope to organize routes according to single files, and use the routing plugin only to register route addresses and then reference the corresponding route methods. Because each route method has its own interface definition, it is too messy and not conducive to reuse if all are written in the routing plugin. I suggest that this approach should also be recommended in the official documentation with examples provided, which can avoid beginners writing spaghetti code.

Now you can use it like this as well, but it looks a bit long and requires writing a lot of repetitive code (although vscode can handle it automatically).

**routes/index.ts**

```ts
import { type FastifyPluginAsync } from 'fastify'

export const routes: FastifyPluginAsync = async (server) => {
  server.get('/ping', (await import('./ping')).default)
  server.get('/test-openai', (await import('./test-openai')).default)
}

export default routes

```

**routes/test-openai.ts**

```ts
import { testOpenAI } from '../api'
import { type RouteGenericInterface, type RouteHandler } from 'fastify'

export interface TestOpenAIQuerystring {
  s?: string
}

export interface TestOpenAIRoute extends RouteGenericInterface {
  Querystring: TestOpenAIQuerystring
}

export const testOpenAIRoute: RouteHandler<TestOpenAIRoute> = async (req, res) => {
  const data = await testOpenAI(req.query.s)
  res.status(data.code)

  return data
}

export default testOpenAIRoute
```

**Comment by mcollina** [comment] 2023-04-02 08:16
This is already supported in Fastify, but it looks like it's not defined in the types. Would you like to send a PR?

**Comment by u3u** [comment] 2023-04-03 05:31
@mcollina Hi, I can submit a type definition PR. But I tested it, and it seems that Fastify does not support it now. 🤔

```ts
import { type FastifyPluginAsync } from 'fastify'

export const routes: FastifyPluginAsync = async (server) => {
  server.get('/ping', import('./ping'))
}

export default routes

```

```
FastifyError [Error]: Missing handler function for "GET:/ping" route.
```

**Comment by mcollina** [comment] 2023-04-03 05:51
Ah, sorry! I totally misread this issue and I thought you were referring to loading plugins with import.

We currently does not support loading the routes handlers via import because we follow the principle of "code the change together should stay together". Splitting a single route definition in multiple files will only make your code harder to maintain.

**Comment by erfanium** [comment] 2023-04-16 12:26
@u3u 
I know it's possible to register a plugin by passing a `Promise` but I really suggest it. I think it's **your** job to await a promise. the code may look a little messy but it's more correct to me.

**Comment by paul-jolimoi** [comment] 2023-04-20 10:55
We are doing something like this in my company, to achieve separation of route declaration and controller definition.

```typescript
// moduleControllers.ts
import type { FastifyRequest, FastifyReply } from 'fastify'

export const someController = async (_request: FastifyRequest, reply: FastifyReply) => {
  // do something

  return reply.send({ success: true })
}
```

```typescript
// moduleRoutes.ts

import * as moduleControllers from './moduleControllers'
import type { RouteOptions } from 'fastify'

const moduleRoutes = [
  {
    method: 'GET',
    url: '/my_route/',
    handler: moduleControllers.someController,
  },
] as RouteOptions[]

export default moduleRoutes
```

```typescript
// router.ts

import moduleRoutes from './moduleRoutes'
import type { FastifyInstance, FastifyPluginCallback, RouteOptions } from 'fastify'

const routes = [
  ...moduleRoutes,
] as RouteOptions[]

const router: FastifyPluginCallback = (fastify: FastifyInstance, _opts, done) => {
  routes.forEach(route => fastify.route(route))
  done()
}

export default router
```

```typescript
// app.ts

import fastify from 'fastify'
import type { FastifyInstance as FastifyApp } from 'fastify/types/instance'

import router from './router'

export function app(): FastifyApp {
  const app = fastify()

  void app.register(router)

  return app
}
```

@mcollina You wouldn't recommend separating route definition from its controller ?

**Comment by mcollina** [comment] 2023-04-20 11:26
No, because code that changes together should stay together.

**Comment by Shibn2** [comment] 2023-07-27 04:41
If the issue is still not resolved, I 'd like to contribute. @mcollina

**Comment by mcollina** [comment] 2023-07-28 09:04
After taking a second look, this does not look like a good first issue but rather quite a substantial change.

Actually, I don't think we have the bandwidth to implement this change, and it can easily be solved by the user, so I'm closing this.

**Closed by mcollina** 2023-07-28 09:04 UTC
Labels: help wanted
