### ISSUE TITLE
Automatic Generics TS support for JSON Schema

### ISSUE THREAD

**Issue by PhilipWee** [fastify/fastify#3367] opened 2021-10-13 09:08 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Right now when using typescript you have to specify the type of the request/response twice, first for getting strict types in the handler and second in the json schema

Can we instead just derive the request/response types from the json schema?

I'm not sure if there are any limitations to this/reasons it is not implemented

### Motivation

Keep code dry, seems repetitive to define the schema twice, or having to install something like json2ts to generate the schema

### Example

Current Code, manually specifying generic type, even though it is already specified in schema
```const app = fastify();

 app.post<{ Body: UserType; Reply: UserType }>(
   "/",
   {
     schema: {
       body: User,
       response: {
         200: User,
       },
     },
   },
   (req, rep) => {
     const { body: user } = req;
     rep.status(200).send(user);
   }
 );```

With feature, no need to specify generic type, keeping code DRY
```const app = fastify();

 app.post(
   "/",
   {
     schema: {
       body: User,
       response: {
         200: User,
       },
     },
   },
   (req, rep) => {
     //Same typescript support here
     const { body: user } = req;
     rep.status(200).send(user);
   }
 );```

**Comment by climba03003** [comment] 2021-10-13 14:30
Duplicate of #3178

The reason is that it cannot provide a good experience to achieve what you mention.
See my comment here https://github.com/fastify/fastify/issues/3178#issuecomment-873940875

Instead of getting a broken experience, I will go for keep the current behavior.

**Closed as completed by climba03003** 2021-10-13 14:30 UTC
