### ISSUE TITLE
ajv options?

### ISSUE THREAD

**Issue by wpbjiuy** [fastify/fastify#2812] opened 2021-01-21 06:21 UTC
https://www.fastify.io/docs/latest/Validation-and-Serialization/ -> Ajv Plugins -> Refer to ajv options to check plugins format

**Comment by salesh** [comment] 2021-01-26 23:26
This basically not working for every page where there is a link to another .md file with an anchor for that file.
Because the way how the website is built https://github.com/fastify/website


```
Refer to [`ajv options`](Server.md#ajv) to check plugins format

```

Anchor disappear from a link on the building website from Markdown with Metalsmith so it will be like this 

```
<p>Refer to <a href=/docs/v3.11.x/Server><code>ajv options</code></a> to check plugins format</p>
```

I believe that this has something with Metalsmith/Markup https://github.com/github/markup/blob/master/README.md#github-markup
filtering/sanitizing stuff.

Couldn't find some solution for this will try to look for something more...

**Comment by mcollina** [comment] 2021-01-27 09:17
cc @lmammino

**Comment by lmammino** [comment] 2021-01-27 09:46
Thanks a lot, @salesh. I'll look into that shortly!

**Comment by salesh** [comment] 2021-01-29 20:16
We can close this one same, the issue is resolved

**Closed** 2021-01-29 20:20 UTC
Labels: bug, documentation, good first issue
