### ISSUE TITLE
Response filtering not working properly with schemas using allOf

### ISSUE THREAD

**Issue by SkeLLLa** [fastify/fastify#1045] opened 2018-07-16 11:21 UTC
Response filter doesn't respect fields that are set through schemas using `allOf` when there is 3 or more interherence levels. Possibly related issue: #922

Steps to reproduce:
1. Code:
```js
const fastify = require('fastify');
const app = fastify({
  logger: {
    level: 'info',
    prettyPrint: true,
  },
  ignoreTrailingSlash: true,
});
app.addSchema({
  $id: 'first',
  type: 'object',
  properties: {
    first: {
      type: 'number',
    },
  },
});

app.addSchema({
  $id: 'second',
  type: 'object',
  allOf: [
    {
      type: 'object',
      properties: {
        second: {
          type: 'number',
        },
      },
    },
    'first#',
  ],
});
app.addSchema({
  $id: 'third',
  type: 'object',
  allOf: [
    {
      type: 'object',
      properties: {
        third: {
          type: 'number',
        },
      },
    },
    'second#',
  ],
});

app.get(
  '/',
  {
    schema: {
      description: `get`,
      response: {
        200: 'third#',
      },
    },
  },
  async function(request, reply) {
    return {first: 1, second: 2, third: 3, extra: 4};
  }
);

(async () => {
  try {
    await Promise.all([
      app.listen(3333),
      app.ready(),
    ]);
  } catch (ex) {
    console.log(ex);
    process.exit(1);
  }
})();
```

2. Send request:
```
curl -X GET http://127.0.0.1:3333/
```

**Expected result**: 
Returns object:
```js
{first: 1, second: 2, third: 3}
```

**Actual result**:
```js
{third: 3}
```

* *node version*: 9
* *fastify version*: 1.8.0

**Comment by mcollina** [comment] 2018-07-16 11:30
this looks like a bug between fastify and fast-json-stringify. Would you like to send a PR with a fix?

**Comment by SkeLLLa** [comment] 2018-07-16 11:50
@mcollina Yes, it's seems that bug is in fast-json-stringify and probably caused by https://github.com/fastify/fast-json-stringify/pull/94 or at least related to it.

However now I'm working on fastify-swagger adding OAS-3 support, so I don't have enough time for now investigating and fixing this issue. Probably later, if noone will take this.

**Comment by delvedor** [comment] 2018-07-16 12:30
Could also be a bug caused by how we traverse the schemas while resolving the refs.
https://github.com/fastify/fastify/blob/master/lib/schemas.js

**Comment by delvedor** [comment] 2018-07-22 16:42
Given your schemas, our internal refs resolver builds the following object:
```
{
  "200": {
"$id": "third",
"type": "object",
"allOf": [
  {
    "type": "object",
    "properties": {
      "third": {
        "type": "number"
      }
    }
  },
  {
    "$id": "second",
    "type": "object",
    "allOf": [
      {
        "type": "object",
        "properties": {
          "second": {
            "type": "number"
          }
        }
      },
      {
        "$id": "first",
        "type": "object",
        "properties": {
          "first": {
            "type": "number"
          }
        }
      }
    ]
  }
]
  }
}
```

It is not related to https://github.com/fastify/fast-json-stringify/pull/94 since we are always passing to `fast-json-stringify`a full object.
Does the above object looks good to you? If so, then the issue is in `fast-json-stringify` and should be fixed there.

**Comment by delvedor** [comment] 2018-07-23 11:18
> However now it's clear why it doesn't work. Package fast-json-strinigfy searches for allOf only in schema root fastify/fast-json-stringify:index.js@db2fa85#L469

Feel free to send a pr!

Regarding the massive use of `allOf` I don't know if in this case `fast-json-stringify` is still faster than `JSON.stringify`. @mcollina what do you think?

**Comment by SkeLLLa** [comment] 2018-07-23 13:29
If using `allOf` will result in performance degradation probably it's better just to add that note to the docs and recommend users to use alternative approach like defining schemas in js objects, and if they to create a new schema from existing then just do `Object.assign` and pass new object to `addSchema` method.

**Comment by mcollina** [comment] 2018-07-23 13:32
We would need to write a benchmark for it. We never did. @SkeLLLa would you like to contribute one to https://github.com/fastify/fast-json-stringify?

**Comment by delvedor** [comment] 2018-07-23 13:36
@SkeLLLa we should write a benchmark, I fear that a massive use (many nested *allOf*) **could** not be that fast.

Actually the use of *allOf* is not needed given how `fast-json-stringify` works, because if a key is declared in the schema and that key is not present in the object to serialize, it will not be present in the final string :)

**Comment by SkeLLLa** [comment] 2018-07-24 07:31
Yes. I'll submit PR.

**Closed** 2018-07-25 21:21 UTC
Labels: bug
