### ISSUE TITLE
Support rawBody or override JSON parser

### ISSUE THREAD

**Issue by rpedela** [fastify/fastify#707] opened 2018-01-23 19:33 UTC
In #643, it was decided to have a separate discussion/PR for supporting ```rawBody```. I would like to start that discussion. An alternative that doesn't increase memory usage is having an option to override the JSON parser for specific routes. I know the fastify community has done a lot of work to make JSON parsing fast which is awesome, but sometimes you just need to do it yourself. Why? Int64 and big decimals.

I am working on a JSON API which supports any number regardless of size for specific routes. That number is either stored in Postgres directly or it is used in a SELECT. Either way, Javascript's rounding can screw it up. I also have a use case for storing the raw JSON from the client in the database. I use a custom C/C++ JSON parser to handle the large numbers.

Personally I would prefer ```rawBody``` because then I can still use schema validation, etc on the routes. Having to explicitly enable it also makes sense to me since it would increase memory usage.

**Comment by mcollina** [comment] 2018-02-08 09:37
Yes, definitely.

`rawBody`  is not feasible, due to increased memory usage I am very against exposing this.
I'm very open to add a way to skip the default JSON parsing completely, both as route-level option and as an encapsulatable plugin option. 

If it does not cause significant performance regressions I'm also ok in _removing_ the inlined json parsing, and just setup a contentTypeParser for JSON (which would be overridable). Ideally this would be the preferred course of action, but the overhead might be too high.

Would you like to send a PR?

**Comment by rpedela** [comment] 2018-02-11 22:19
I noticed that when adding a new content parser, the user needs to handle the body stream. While that is certainly useful if you need a streaming parser, I think the most common use case is to collect the entire body and then parse. Should ```addContentTypeParser()``` return a buffer instead and then the user can decide how to parse the buffer? It would be similar to how the ```raw``` parser works in [body-parser](https://github.com/expressjs/body-parser). Something like this:

```js
fastify.addContentTypeParser('application/json', function (buffer, done) {
  done(null, customJsonParser(buffer))
})
```

Looking at ```jsonBody()``` in [libRequest.js](https://github.com/fastify/fastify/blob/master/lib/handleRequest.js), the only JSON-specific code is ```JSON.parse()```. So I think it would be pretty easy to refactor/implement. BTW I think it useful to allow the user to implement a streaming parser. I am not suggesting removing that functionality. But I think the more common case, parsing the entire body, could and should be easier to override.

**Comment by mcollina** [comment] 2018-02-11 23:28
@rpedela considering it's very easy to collect all the data coming from a stream, how about we document how to do that?

There are various ways to do this, and a generic approach would definitely have more overhead than the fast path we have for strings right now. Parsing a JSON from buffers would slow us down significantly. There are too many cases, and I would like to keep our API tidy, and document the various options.

We might also add an option to `addContentTypeParser` so that the user can specify if they want a stream, a buffer or a string.

Would you like to send a PR with the docs update or the new functionality?

**Comment by rpedela** [comment] 2018-02-11 23:44
> considering it's very easy to collect all the data coming from a stream, how about we document how to do that?

I don't agree it is "very easy". It certainly isn't hard either. In order to do it correctly, there are several error cases which need to be handled which ```jsonBody()``` already does. It is something that every user will have to implement themselves the same way. Why force that on users? Besides if you remove ```JSON.parse()``` from ```jsonBody()```, you have the generic, just as fast, body handling code. There will be no performance difference.

> Parsing a JSON from buffers would slow us down significantly. 

String is fine too.

> Would you like to send a PR with the docs update or the new functionality?

If we can agree on a way forward first, sure.

**Comment by nwoltman** [comment] 2018-02-12 00:04
It is "very easy" if you use the [`raw-body`](https://www.npmjs.com/package/raw-body) module:

```js
const rawBody = require('raw-body')

fastify.addContentTypeParser('*', (req, done) => {
  rawBody(req, {
    length: req.headers['content-length'],
    limit: '1mb',
    encoding: 'utf8', // Remove if you want a buffer
  }, (err, body) => {
    if (err) return done(err)
    done(null, parse(body))
  })
})
````

**Comment by mcollina** [comment] 2018-02-13 22:06
@jsumners how about:

```js
fastify.addContentTypeParser('application/x-foo', { concatAs: 'string' }, function (payload, done) {
  const parsedPayload = doThings(payload)
  done(null, parsedPayload)
}
```

**Comment by jsumners** [comment] 2018-02-13 22:20
That looks like a good API.

**Comment by delvedor** [comment] 2018-02-14 12:11
I'm working on this.

**Comment by rpedela** [comment] 2018-02-14 17:56
@delvedor Thanks!

**Comment by delvedor** [comment] 2018-02-19 08:52
Closing this, if you have more questions feel free to reopen :)

**Comment by mikemaccana** [comment] 2020-04-16 15:24
@delvedor is it possible to have `req.rawBody` and keep the parsed `req.body`? I need to be able to access the `rawBody` (for signature verification of webhooks) but don't want to break `body` for everything else in the route. 

I've followed https://github.com/fastify/fastify/pull/785 to https://www.fastify.io/docs/master/ContentTypeParser/#body-parser and the only options seems to be `done(error, body))` which means I can't have both a `body` and a `rawBody`.

**Comment by mcollina** [comment] 2020-04-24 17:40
@mikemaccana thanks for reporting this. I _now_ think that is totally a valid usecase that we should support at our best. I _think_ a route-level `rawBody: true` option would do. It would easily double the memory usage, but that's exactly what is needed.

Would you like to send a PR?

**Comment by wolfejw86** [comment] 2020-05-21 21:58
is there a more elegant way to workaround this than something like:
```
fastify.addContentTypeParser('application/json', { parseAs: 'string' }, function (req, body, done) { 
  done(body);
});
```
I am stuck on it because of webhook-type use cases as well, although I still have to JSON.parse the body if i need to use the fields with this method.

**Comment by mcollina** [comment] 2020-05-22 06:38
> is there a more elegant way to workaround this?

Sending a PR to implement this feature :).

**Comment by Eomm** [comment] 2020-05-22 06:53
I think this PR #2286 would close this issue too

**Comment by joelwass** [comment] 2020-06-13 19:21
a route-level `rawBody: true` option would be a life saver

**Closed** 2020-06-23 20:11 UTC
Labels: feature request, good first issue

**Comment by cmawhorter** [comment] 2021-04-11 00:50
I've never been able to get the plugin to work.  Not sure why, but it's probably me.

However, this works without a plugin:

```ts
// override built-in parser. otherwise everything _except_ json will be a buffer
server.addContentTypeParser('application/json', { parseAs: 'buffer' }, (req, body, done) => {
  done(null, body);
});

// set a catch-all for everything other than json.
// NOTE: this still misses request that don't send a content-type at all (see #2994)
server.addContentTypeParser('*', (req, payload, done) => {
  const chunks: Buffer[] = [];
  payload.on('data', chunk => {
    chunks.push(chunk);
  });
  payload.on('end', () => {
    done(null, Buffer.concat(chunks));
  });
});
```

**Comment by mcollina** [comment] 2021-04-11 08:04
@cmawhorter please open a fresh issue on the help repo or inside the plugin itself, it's unlikely you'll get some help in a closed issue. Moreover include a reproducible example.
