### ISSUE TITLE
alias schema.query to schema.querystring in route definition

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1690] opened 2019-06-03 15:29 UTC
## 🐛 Bug Report

When defining a route, it's easier to `schema.query` be automatically copied into `schema.querystring`, mainly because `request.query` is what we use to access the querystring, and simmetry here would be good.

Moreover, we should look into doing some stricter validation of those properties to catch this type of errors.

## To Reproduce

```js
app.get('/', {
  schema: {
    query: { // this should querystring
      type: "object",
      properties: {
        name: {
          type: "string",
          default: "world"
        }
      },
      required: ["name"]
    }
  }
}, async (request, reply) => {
  return { hello: request.query.name }
})
```

## Expected behavior

`schema.query` to work as `schema.querystring`.

## Your Environment

- *node version*: 10
- *fastify version*: all
- *os*: Mac, Windows, Linux

**Comment by jsumners** [comment] 2019-06-03 15:31
Agree. My org’s Fastify wrapper does this: alias querystring to query.

**Comment by raghavmac** [comment] 2019-06-04 10:28
Hi, I would like to fix this issue but I would like to clarify that `schema.query` and `schema.querystring` should have same behaviour right?
Because the **default** value is not working for `schema.query` due to validation!

**Comment by mcollina** [comment] 2019-06-04 11:25
> Because the default value is not working for schema.query due to validation!

What do you mean?

**Comment by raghavmac** [comment] 2019-06-04 12:14
If used `schema.query` without actually passing any query, the `default: "world"` will not getting in response, instead it does works when using `schema.querystring`. 
You can reproduce from your above schema example as well.

**Comment by mcollina** [comment] 2019-06-04 17:01
`schema.query` is not currently supported. Adding support is the key part of that issue.

**Comment by raghavmac** [comment] 2019-06-05 09:34
Can you please assign this issue to me?

**Comment by RafaelGSS** [comment] 2019-06-07 13:11
If user passed `query` and `querystring` on schema could throw an error, right? Because, based on the last commit, the `querystring` is overwrite by `query`

**Comment by mcollina** [comment] 2019-06-08 13:13
Yes it could!

Il giorno ven 7 giu 2019 alle 15:11 Rafael Gonzaga <notifications@github.com>
ha scritto:

**Closed** 2019-06-09 22:01 UTC
Labels: good first issue
