### ISSUE TITLE
statusCode is ignored when returning FastifyError (defaults to 200)

### ISSUE THREAD

**Issue by Suraj-Tiwari** [fastify/fastify#4141] opened 2022-07-16 22:51 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.1

### Plugin version

3.0.0

### Node.js version

16.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

when using `@fastify/error@3.0.0` and `@fastify/swagger@^7.4.1` and creating error response from there, 
eg: `createError('400', 'Invalid operation', 400)` response validator for status code 200 is triggered instead of 400

### Steps to Reproduce

Request Handler
```js
const handleRequest = async (request: FastifyRequest, reply: FastifyReply) => {  
   return new (createError('400', 'Invalid operation', 400))();
}
```

Route Registry
```js
fastify.route({
    method: 'GET',
    url: '/send-error',
    schema: {
      response: {
        200: {
          type: 'object',
          description: 'Success Response',
          required: ['message'],
          properties: {
            message: {type: 'string'}
          }
        },
        400: {
          type: 'object',
          description: 'Error Message',
          properties: {
            error: {
              type: 'string'
            }
          }
        }
      }
    },
    handler: handleRequest
  });
```

In this case response will be status code 500, message body:  message is required

### Expected Behavior

Status code should be set 400 automatically.

**Comment by Suraj-Tiwari** [comment] 2022-07-16 22:55
Here is a temporary fix which i'm using, i've written that as a comment to issue for easy visibility.

```ts
import { FastifyError, FastifyReply, FastifyRequest } from 'fastify';

const handleError = (
  error: FastifyError,
  request: FastifyRequest,
  reply: FastifyReply
) => {
  request.log.error(error);
  if (error.statusCode != null) {
    reply.status(error.statusCode);
  }
  return {
    error: error.message
  };
};

export { handleError };
```

```ts
fastify.route({
    method: 'GET',
    url: '/throw-error',
    // ...schema
    // ...handler
    // ...etc
    errorHandler: handleError,
)}
```

**Comment by climba03003** [comment] 2022-07-17 06:23
I cannot reproduce your issue with

```js
const fastify = require("fastify")({});
const createError = require("@fastify/error");

fastify.get("/", () => {
  return new (createError("400", "Invalid operation", 400))();
});

(async function () {
  const res = await fastify.inject("/");
  console.log(res.statusCode);
})();
```

I assume you already replaced the internal error handler globally.
That's means you should handle the `statusCode` inside that error handler.

**Comment by Suraj-Tiwari** [comment] 2022-07-17 06:53
@climba03003 this issue is from 4.x release assuming as old one was 3.x, in earlier version i had same implementation, in that i did placed an error handler overriding body only, handling status code does solve that problem in new version, but looks like intended behaviour is changed possibly or old version had an anti bug 🤣.

```js
import { FastifyError, FastifyReply, FastifyRequest } from 'fastify';

const handleError = (
  error: FastifyError,
  request: FastifyRequest,
  reply: FastifyReply
) => {
  request.log.error(error);
  // --- this part is new for fix v3.x didn't needed that. 
  if (error.statusCode != null) {
    reply.status(error.statusCode);
  }
  // -- end --
  return {
    error: error.message
  };
};

export { handleError };
```

i doubt that could be due to '@fastify/swagger', anyway we can close this issue if you think that's intended behaviour. If someone faced this issue when upgrading i've already added a possible fix.

**Comment by climba03003** [comment] 2022-07-17 12:26
Duplicate of #3959

Yes, it is intended behavior.

**Closed** 2022-07-17 12:26 UTC
