### ISSUE TITLE
HTTP2  crash on h2spec check

### ISSUE THREAD

**Issue by songdongsheng** [fastify/fastify#2402] opened 2020-07-11 15:16 UTC
## 🐛 Bug Report

HTTP2 (h2) or HTTP2 in plain text (h2c) crash on h2spec test

h2c crashed after running h2spec up to three times.

h2 crashed rarely.

## To Reproduce

1. run the demo h2c (or h2) code

```PowerShell
PS C:\> [System.Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.17763.0 Microsoft Windows NT 10.0.17763.0

PS C:\> node --version
v14.5.0
```

Use fastify  "3.0.1":

```js
const fastify = require("fastify")({
  logger: true,
  http2: true,
});

fastify.get("/", async (request, reply) => {
  reply.type("application/json").code(200);
  return { hello: "world" };
});

fastify.listen(8181, "0.0.0.0", (err, address) => {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
  // fastify.log.info(`Server listening on ${address}`);
});
```

2.  run h2spec up to three times

- https://github.com/summerwind/h2spec/releases/tag/v2.5.0

```PowerShell
PS C:\> h2spec --version
Version: 2.5.0 (8b58a5e5cc9590ac7a470dc1c01065ae575bbf25)

PS C:\> h2spec.exe -p 8181
h2spec -p 8181
Generic tests for HTTP/2 server
  1. Starting HTTP/2
    ✔ 1: Sends a client connection preface

  2. Streams and Multiplexing
    ✔ 1: Sends a PRIORITY frame on idle stream
    × 2: Sends a WINDOW_UPDATE frame on half-closed (remote) stream
    Error: EOF
    × 3: Sends a PRIORITY frame on half-closed (remote) stream

Error: dial tcp 127.0.0.1:8181: connect: connection refused
```

3. nodejs crashed

```PowerShell
PS C:\> node .\index.js
{"level":30,"time":1594478874181,"pid":23028,"hostname":"xyz","msg":"Server listening at http://0.0.0.0:8181"}
...
{"level":30,"time":1594478892074,"pid":23028,"hostname":"xyz","reqId":72,"res":{"statusCode":415},"err":{"type":"FastifyError","message":"Unsupported Media Type: %s","stack":"FastifyError: Unsupported Media Type: %s\n    at ContentTypeParser.run (C:\\var\\vcs\\git\\misc\\scratch\\nodejs\\fastify-h2c-demo\\node_modules\\fastify\\lib\\contentTypeParser.js:95:16)\n    at handleRequest (C:\\var\\vcs\\git\\misc\\scratch\\nodejs\\fastify-h2c-demo\\node_modules\\fastify\\lib\\handleRequest.js:32:41)\n    at runPreParsing (C:\\var\\vcs\\git\\misc\\scratch\\nodejs\\fastify-h2c-demo\\node_modules\\fastify\\lib\\route.js:374:5)\n    at Object.routeHandler [as handler] (C:\\var\\vcs\\git\\misc\\scratch\\nodejs\\fastify-h2c-demo\\node_modules\\fastify\\lib\\route.js:350:7)\n    at Router.lookup (C:\\var\\vcs\\git\\misc\\scratch\\nodejs\\fastify-h2c-demo\\node_modules\\find-my-way\\index.js:351:14)\n    at Router.defaultRoute (C:\\var\\vcs\\git\\misc\\scratch\\nodejs\\fastify-h2c-demo\\node_modules\\fastify\\fastify.js:471:23)\n    at Router._defaultRoute (C:\\var\\vcs\\git\\misc\\scratch\\nodejs\\fastify-h2c-demo\\node_modules\\find-my-way\\index.js:565:14)\n    at Router.lookup (C:\\var\\vcs\\git\\misc\\scratch\\nodejs\\fastify-h2c-demo\\node_modules\\find-my-way\\index.js:349:36)\n    at Http2Server.emit (events.js:314:20)\n    at Http2Server.onServerStream (internal/http2/compat.js:828:10)","name":"FastifyError","code":"FST_ERR_CTP_INVALID_MEDIA_TYPE","statusCode":415},"msg":"Unsupported Media Type: %s"}
{"level":30,"time":1594478892077,"pid":23028,"hostname":"xyz","reqId":72,"res":{"statusCode":415},"responseTime":3.5424000024795532,"msg":"request completed"}
PowerShell 7 (x64)[23028]: c:\ws\src\node_http2.cc:522: Assertion `(current_nghttp2_memory_) == (0)' failed.
 1: 00007FF7C5EBE87F v8::internal::wasm::DisjointAllocationPool::~DisjointAllocationPool+76303
 2: 00007FF7C5E65B66 v8::base::OS::ActivationFrameAlignment+33350
 3: 00007FF7C5E65EE1 v8::base::OS::ActivationFrameAlignment+34241
 4: 00007FF7C5E3BEEC v8::internal::OrderedHashTable<v8::internal::OrderedHashMap,2>::NumberOfBucketsOffset+126684
 5: 00007FF7C65E083D v8::internal::GlobalHandles::InvokeFirstPassWeakCallbacks+157
 6: 00007FF7C65B2A05 v8::internal::Heap::PageFlagsAreConsistent+2469
 7: 00007FF7C65A7C65 v8::internal::Heap::CollectGarbage+1493
 8: 00007FF7C6562327 v8::internal::ItemParallelJob::Item::TryMarkingAsProcessing+3031
 9: 00007FF7C5DF82AF std::basic_ostream<char,std::char_traits<char> >::operator<<+71455
10: 00007FF7C5DF6BA6 std::basic_ostream<char,std::char_traits<char> >::operator<<+65558
11: 00007FF7C5F11ADB uv_async_send+331
12: 00007FF7C5F1126C uv_loop_init+1228
13: 00007FF7C5F11418 uv_run+216
14: 00007FF7C5E1F515 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap,2>::NumberOfBucketsOffset+9477
15: 00007FF7C5E92920 node::Start+288
16: 00007FF7C5CF672C RC4_options+339500
17: 00007FF7C6C5395C v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+156316
18: 00007FF80C127974 BaseThreadInitThunk+20
19: 00007FF80E67A271 RtlUserThreadStart+33
```

## Expected behavior

h2spec should be passed all tests.

At least the node js process should not crash.

## Your Environment

- *node version*: v14.5.0
- *fastify version*: 3.0.1
- *os*: Microsoft Windows NT 10.0.17763.0

**Comment by songdongsheng** [comment] 2020-07-11 15:25
This issue similar to nodejs issue [http2 crash on h2spec check](https://github.com/nodejs/node/issues/34311).

But nodejs is easy to reproduce both h2 and h2c crash, fastify easy to reproduce h2c crash, hard to reproduce h2 crash.

**Comment by StarpTech** [comment] 2020-07-11 15:38
I have a different result with the sample example but I can reproduce the internal crash on some runs.
Btw: I'd always recommend using a proxy like NGINX, Traefik to offload HTTP2.

```
Failures:

Hypertext Transfer Protocol Version 2 (HTTP/2)
  5. Streams and Multiplexing
    5.1. Stream States
      × 8: closed: Sends a DATA frame after sending RST_STREAM frame
        -> The endpoint MUST treat this as a stream error of type STREAM_CLOSED.
           Expected: GOAWAY Frame (Error Code: STREAM_CLOSED)
                     RST_STREAM Frame (Error Code: STREAM_CLOSED)
                     Connection closed
             Actual: DATA Frame (length:17, flags:0x00, stream_id:1)
      × 9: closed: Sends a HEADERS frame after sending RST_STREAM frame
        -> The endpoint MUST treat this as a stream error of type STREAM_CLOSED.
           Expected: GOAWAY Frame (Error Code: STREAM_CLOSED)
                     RST_STREAM Frame (Error Code: STREAM_CLOSED)
                     Connection closed
             Actual: DATA Frame (length:17, flags:0x00, stream_id:1)
      × 11: closed: Sends a DATA frame
        -> The endpoint MUST treat this as a connection error of type STREAM_CLOSED.
           Expected: GOAWAY Frame (Error Code: STREAM_CLOSED)
                     RST_STREAM Frame (Error Code: STREAM_CLOSED)
                     Connection closed
             Actual: Timeout
      × 12: closed: Sends a HEADERS frame
        -> The endpoint MUST treat this as a connection error of type STREAM_CLOSED.
           Expected: GOAWAY Frame (Error Code: STREAM_CLOSED)
                     Connection closed
             Actual: Timeout

      5.1.1. Stream Identifiers
        × 2: Sends stream identifier that is numerically smaller than previous
          -> The endpoint MUST respond with a connection error of type PROTOCOL_ERROR.
             Expected: GOAWAY Frame (Error Code: PROTOCOL_ERROR)
                       Connection closed
               Actual: DATA Frame (length:0, flags:0x01, stream_id:5)

    5.4. Error Handling
      5.4.1. Connection Error Handling
        × 1: Sends an invalid PING frame for connection close
          -> The endpoint MUST close the TCP connection
             Expected: Connection closed
               Actual: GOAWAY Frame (length:28, flags:0x00, stream_id:0)

  6. Frame Definitions
    6.7. PING
      × 2: Sends a PING frame with ACK
        -> The endpoint MUST NOT respond to PING frames with ACK.
           Expected: PING Frame (length:8, flags:0x01, stream_id:0, opaque_data:h2spec)
             Actual: Connection closed

Finished in 12.1406 seconds
146 tests, 138 passed, 1 skipped, 7 failed
```

**Comment by mcollina** [comment] 2020-07-11 16:14
I’m closing this because there is little we can do. Node.js itself is crashing and all of http2 is implemented there unfortunately.

**Closed by mcollina** 2020-07-11 16:14 UTC
