### ISSUE TITLE
`onRoute` hook doesn't receive the resolved schema

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#2123] opened 2020-03-02 15:45 UTC
## 💬 Questions and Help

`onRoute` hook doesn't receive the resolved schema. Is it ok?
NB: [`fastify-swagger`](https://github.com/fastify/fastify-swagger/blob/3a7a67395812c0500f73685a22319baaf0646ded/dynamic.js#L12-L14) registers itself using `onRoute`

### Please note that this issue tracker is not a help forum and this issue may be closed.
```
  const fastify = Fastify()

  fastify.addSchema({
    $id: 'test',
    type: 'object',
    properties: {
      id: { enum: ['foo'] }
    }
  })

  fastify.addHook('onRoute', (route) => {
    t.strictDeepEqual(route.schema.headers, {
      type: 'object',
      properties: {
        id: { enum: ['foo'] }
      }
    })
  })

  fastify.route({
    method: 'GET',
    url: '/headers',
    schema: {
      headers: 'test#'
    },
    handler: (req, reply) => {}
  })

  fastify.ready()
```

If you want I'm ok to send a PR to fix this. Anyway I don't know if this can be considered a braking change or not

**Comment by Eomm** [comment] 2020-03-02 18:07
This should be fixed in
https://github.com/fastify/fastify/pull/2108

Your check is not working because you need to run it after the fastify.ready

This happens because the onroute is triggered before the evaluation of the schemas (since the beginning, it is not a regression this case)

**Comment by allevo** [comment] 2020-03-03 09:56
> Your check is not working because you need to run it after the fastify.ready

I don't understand: from my point of view, the hook `onRoute` is fired with the route configuration with the resolved schema.

**Comment by Eomm** [comment] 2020-03-03 10:12
The `onRoute` hook is fired before the evaluation of the shared-schema (replace-way):

https://github.com/fastify/fastify/blob/0b50f38df033ae112d5043cdf21297c7562f608e/lib/route.js#L193

after:

https://github.com/fastify/fastify/blob/0b50f38df033ae112d5043cdf21297c7562f608e/lib/route.js#L272

This test shows what I mean:

https://github.com/fastify/fastify/blob/0b50f38df033ae112d5043cdf21297c7562f608e/test/hooks.test.js#L2787-L2817

**Comment by allevo** [comment] 2020-03-10 16:13
Sorry for the delay.
Yeah, reading the code this behaviour is right.
But from developer point of view? I don't know

**Comment by mcollina** [comment] 2020-03-10 16:38
> But from developer point of view? I don't know

Should we add another event after resolution is completed? How would you fix it?

**Comment by SkeLLLa** [comment] 2020-03-10 16:54
The schemes will be resolved after Fastify's `.ready()` method will be called. That was since fastify v1 and that's why fastify-swagger plugin has `.swagger()` method:
```
fastify.ready(err => {
  if (err) throw err
  fastify.swagger()
})
```

Maybe all devs just get used to it.

**Comment by Eomm** [comment] 2020-03-26 07:25
This issue is related to https://github.com/fastify/fastify/issues/2144

I will give the issue a try in the next days 👍

**Comment by mcollina** [comment] 2020-04-26 13:19
@eomm are there any news about this?

**Comment by Eomm** [comment] 2022-07-21 06:39
Closing due https://github.com/fastify/fastify/pull/2023

The "replace-way" schema composition has been removed, so now the `onRoute` hook receives the same JSON schema set by the user

**Closed by Eomm** 2022-07-21 06:39 UTC
Labels: discussion
