### ISSUE TITLE
relativeContext is not defined

### ISSUE THREAD

**Issue by edoparo** [fastify/fastify#2431] opened 2020-07-22 13:22 UTC
## 💥 Regression Report

We are getting the following error, after running `npm install` with `fastify@2.8.0`:

```
(node:56760) UnhandledPromiseRejectionWarning: ReferenceError: relativeContext is not defined
    at readyPromiseCB (/Users/edo/WebstormProjects/fastify-bug/node_modules/avvio/boot.js:313:17)
    at Boot.timeoutCall (/Users/edo/WebstormProjects/fastify-bug/node_modules/avvio/boot.js:381:5)
    at Boot.callWithCbOrNextTick (/Users/edo/WebstormProjects/fastify-bug/node_modules/avvio/boot.js:360:19)
    at Object.push (/Users/edo/WebstormProjects/fastify-bug/node_modules/fastq/queue.js:101:14)
    at Promise (/Users/edo/WebstormProjects/fastify-bug/node_modules/avvio/boot.js:297:18)
    at new Promise (<anonymous>)
    at Boot.ready (/Users/edo/WebstormProjects/fastify-bug/node_modules/avvio/boot.js:296:10)
    at Object.server.(anonymous function) [as ready] (/Users/edo/WebstormProjects/fastify-bug/node_modules/avvio/boot.js:47:21)
    at listenPromise (/Users/edo/WebstormProjects/fastify-bug/node_modules/fastify/lib/server.js:86:19)
    at Object.listen (/Users/edo/WebstormProjects/fastify-bug/node_modules/fastify/lib/server.js:126:34)
```

## Last working version

Worked up to version:
 - `fastify`: 2.8.0
 - `avvio`: 6.4.1

Stopped working in version:
 - `fastify`: 2.8.0
 - `avvio`: 6.5.0

## To Reproduce

```js
const fastify = require('fastify')({
  logger: false
});

( async () => {
  const schema = {
    schema: {
      response: {
        200: {
          type: 'object',
          properties: {
            hello: {
              type: 'string'
            }
          }
        }
      }
    }
  }

  fastify
    .get('/', schema, function (req, reply) {
      reply
        .send({ hello: 'world' })
    })

  await fastify.ready();
  await fastify.listen(3000, '0.0.0.0');
})();
```

The problem appears to happen when using `Promise` on `fastify.listen` together with `await fastify.ready()`.
Removing `await fastify.ready()`, seems to work.
Keeping `await fastify.ready()` and setting a callback to `fastify.listen`, seems to work as well.

## Your Environment

- *node version*: 10
- *fastify version*: 2.8.0
- *os*: Linux, MacOS

**Comment by jsumners** [comment] 2020-07-22 13:28
The latest release in the v2 line is v2.15.1. Have you tried this version? I am unable to reproduce this error with v2.15.1.

**Comment by edoparo** [comment] 2020-07-22 13:43
Hello James, thank you for your immediate reply. 

Yes, with the 2.15.1, the example is working fine. However, in our production env, we are running 2.8.0 and, as you might know, is not so simple to upgrade to 2.15.1. We saw that `avvio` has been upgraded to 6.5.0 few days ago, and it seems this upgrade made the error occur, not actually related to fastify.

Is there any chance to make it working again with fastify 2.8.0?
Thank you again.

**Comment by edoparo** [comment] 2020-07-22 13:56
Yes, with 2.15.1, the example is working fine. Didn't try other versions, since 2.8.0 is the one we're currently using in production. We believe that this problem is caused by the new version of avvio 6.5.0 released few days ago.

As workaround we're gonna return a Promise which wraps the result of the callback of `fastify.listen`. Hope this might help someone else.

**Comment by edoparo** [comment] 2020-07-23 07:13
In any case, is there any chance to get it fixed? Currently our pipelines are broken due to this issue since fastify's package-lock entry needs avvio ^6.2.2 and the version downloaded is 6.5.0

**Comment by mcollina** [comment] 2020-07-23 08:58
We do not support old version of fastify nor avvio or any combinations of those that are not the latest in the dependent semver-major range.. Upgrade to the latest fastify (this is the simplest path).

I'd be happy to review a PR to avvio if you want this fixed. Anyway, I'm closing this as it's not a fastify problem.

**Closed by mcollina** 2020-07-23 08:58 UTC
