### ISSUE TITLE
To upload large file 10 GB + over http2.

### ISSUE THREAD

**Issue by starsoftdev** [fastify/fastify#5826] opened 2024-11-06 19:55 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I am uploading large file using Fastify framework over http2.

In frontend, large file instance is sent using fetch api.
To avoid accumulate file in server memory, I want to directly write the file on disk. also, don't want to put on temporary.

```
await (fetch as any)(`${api.getUri()}/v2-upload`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/octet-stream',
        'Filename': fileName
      },
      signal: cancelSource.signal,
      body: fileInstance,
      duplex: 'half',
    });
```

In server side, currently, I am using nest.js with Fastify.

main.ts
```
app.getHttpAdapter().getInstance().addContentTypeParser('application/octet-stream', (req, payload, done) => {
    done(null, payload);
  });
```
controller.ts
```
import { FastifyRequest, FastifyReply } from 'fastify';
import * as fs from 'fs';
import { pipeline } from 'stream';
import * as util from 'util';
const pump = util.promisify(pipeline);


async uploadFileV2(
    @Req() request: FastifyRequest,
    @Res() response: FastifyReply,
    @Headers('Filename') fileName: string,
  ): Promise<void> {
    console.log(fileName, ':::::::::STARTED:::::::::::');
    try {
      setInterval(() => {
        const memoryUsage = process.memoryUsage();  
  
        console.log('::::::::::::::::::Memory Usage:1');  
        console.log(`- RSS (Resident Set Size): ${(memoryUsage.rss / 1024 / 1024).toFixed(2)} MB`);
      }, 1000);

      response.send('ok').status(200);
      const writeStream = fs.createWriteStream('D:/vol1/aaa.iso', {
        highWaterMark: 1024*1024 * 1024, // Adjust the internal buffer size
        autoClose: true
      });
      await pump(request.raw, writeStream);
}

```

but I can see the file size is zero(0) while the file is uploading. I think file size should be increased.
If file uploading is finished then I can see the file size is 10 GB.

In my case, where file is buffered ?
How can I store file directly on disk without buffering temporary / memory in server?

**Comment by climba03003** [comment] 2024-11-07 03:54
Please provide a minimal reproducible code snippets. It should be able to copy and paste, then run directly.

At a first glance, you are not using `fastify` directly but mixed with other framework.
You should pipe with `request.body` instead of `request.raw`.

**Comment by starsoftdev** [comment] 2024-11-07 04:21
Thank you for your reply.

As I said, I used Fastify framework over Nest.js.

it's very difficult to upload the entire project here . :-)

**Comment by climba03003** [comment] 2024-11-07 05:17
> it's very difficult to upload the entire project here . :-)

It is impossible for us to provide support for `Nest.js`. Most of our folks have no knowledge on it.
Although it is using `fastify` as underlying server, they may using some plugin that we don't know.

If you need to find out the exact issue, you should isolate your reproducible code to only using `fastify`.
Otherwise, I might close the issue within a week without anything added.

**Comment by starsoftdev** [comment] 2024-11-07 08:45
Fastify Backend Code.

```
import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import * as fs from 'fs';
import { pipeline } from 'stream';
import * as util from 'util';

const pump = util.promisify(pipeline);

async function uploadFileV2(request: FastifyRequest, reply: FastifyReply) {
  const fileName = request.headers['filename'] as string; // Access custom headers in Fastify
  
  console.log(`${fileName} :::::::::STARTED:::::::::::`);

  // Log memory usage at intervals
  const memoryUsageInterval = setInterval(() => {
    const memoryUsage = process.memoryUsage();
    console.log('::::::::::::::::::Memory Usage');
    console.log(`- RSS (Resident Set Size): ${(memoryUsage.rss / 1024 / 1024).toFixed(2)} MB`);
  }, 1000);

  try {
    // Immediately send response acknowledgment
    reply.status(200).send('ok');

    // Create a write stream to save the file
    const writeStream = fs.createWriteStream(`D:/vol1/${fileName}`, {
      highWaterMark: 1024 * 1024 * 1024, // 1GB buffer size
      autoClose: true
    });

    // Use `pump` to pipe the request to the file system efficiently
    await pump(request.raw, writeStream);

    console.log(`${fileName} :::::::::UPLOAD COMPLETE:::::::::::`);
  } catch (error) {
    console.error('Error during file upload:', error);
    reply.status(500).send({ error: 'File upload failed' });
  } finally {
    clearInterval(memoryUsageInterval); // Clear the interval to stop memory logging
  }
}

export default async function (fastify: FastifyInstance) {
  fastify.post('/upload-file', uploadFileV2);
}
```

Frotnend Fetch javascript Code
```
await (fetch as any)(`https://localhost:3000/v2-upload`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/octet-stream',
        'Filename': fileName
      },
      signal: cancelSource.signal,
      body: fileInstance,
      duplex: 'half',
    });
```

**Comment by climba03003** [comment] 2024-11-08 04:18
I don't knows if it makes any different, but you send the response before pipe to the file.
If you move it after piping, is it working correctly?

I have no idea how can I directly run your code, it is the same as no runnable minimal reproducible code.

**Comment by climba03003** [comment] 2024-11-18 03:45
I am closing this issue because it still leak of clear information.

I have tested with `http2` directly, it is not possible to end the request and piping afterward.
Please let me knows if you have any more information.

**Closed by climba03003** 2024-11-18 03:45 UTC
Labels: need info
