### ISSUE TITLE
close() on an http2 server waits for http2SessionTimeout, even with forceCloseConnections: true 

### ISSUE THREAD

**Issue by bhollis** [fastify/fastify#5866] opened 2024-11-29 22:49 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.1.0

### Node.js version

v22.11.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

24.1.0

### Description

I am starting and stopping fastify servers in tests, to use as a mock endpoint for service clients. The clients require an http2 server (they're ConnectRPC clients). When I call `await server.close()`, the call hangs for the length of the `http2SessionTimeout`, regardless of whether or not I specify `forceCloseConnections: true`. I can't find any way to shut down the server without this wait, which makes test runs very slow.

```
async function mockAuthServer() {
  const abortController = new AbortController();

  const server = fastify({
    http2: true,
    forceCloseConnections: true,
    keepAliveTimeout: 1,
    // http2SessionTimeout: 5, // default 72s
  });
  
  // code that implements my mock service

  await server.listen({ host: "localhost", port: 0, signal: abortController.signal });

  // code that makes requests 

  return async () => {
    await server.close();
    abortController.abort();
  }
}
```

### Link to code that reproduces the bug

https://github.com/StatelyCloud/fastify-close

### Expected Behavior

This seems to be because the ConnectRPC clients by default don't shut down their connections, which makes sense. I think Fastify should be able to close these connections after there are no longer active requests, if `forceCloseConnections` is set.

**Comment by climba03003** [comment] 2024-11-30 05:19
Duplicate of https://github.com/fastify/fastify/issues/5716

**Closed by climba03003** 2024-11-30 05:19 UTC
