### ISSUE TITLE
tests get connection refused for localhost

### ISSUE THREAD

**Issue by emelalkim** [fastify/fastify#5117] opened 2023-10-24 03:43 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

My previously working tests stopped working.
I am using fastify 4.17.0, chai 4.3.4 and mocha 9.1.3
I set the host to 0.0.0.0 and I have specific tests for localhost (Some of my functionality only works when the URL is localhost for security reasons)
I am getting Error: connect ECONNREFUSED ::1:5987 when I use localhost in the URL.
Does anyone have any idea why this is happening?

**Comment by metcoder95** [comment] 2023-10-24 11:28
Hey! Can you share a 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to help you in a better way? 🙂

**Comment by jsumners** [comment] 2023-10-24 11:35
https://github.com/fastify/fastify/blob/9b8a7825dc033887d293549e40284284bf27c5a5/docs/Reference/Server.md?plain=1#L966-L984

**Comment by climba03003** [comment] 2023-10-30 10:28
Closing because it is correct behavior according to the document.

**Closed by climba03003** 2023-10-30 10:28 UTC
Labels: need info
