### ISSUE TITLE
listen() registers a callback even when listen() fails, calling the callback twice - once when it fails and again if it succeeds in a later call

### ISSUE THREAD

**Issue by kryztoval** [fastify/fastify#5519] opened 2024-06-12 04:04 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.2

### Node.js version

22.2.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 11 Pro (10.0.22621.3374)

### Description

When you call fastify.listen() and it fails it will launch the callback with err set correctly
If you catch this error, and try to call listen() again later and it succeeds it will return a callback for the current call but it will also trigger a callback for each of the previous listen() calls.

```
/* common settings */
const host = "0.0.0.0";
const port = 3033;

/* Helper to block the port */
const net = require("net");
server = net.createServer();
server.listen(port, host, function () {
  setTimeout(serverClose, 20000);
});

/* Helper function to free the port */
function serverClose() {
  server.close(() => { })
}

/* MRE starts here */
const fastify = require('fastify')();
function tryToListen() {
  fastify.listen({host: host, port: port}, function(err,address) {
    if(err) {
      console.log((new Date()).toISOString(),"tryToListen.then{}",err.toString());
      setTimeout(tryToListen, 5000);
    } else {
      console.log((new Date()).toISOString(),"tryToListen.else{}");
    }
  });
} 

//Let's fire the code
console.log((new Date()).toISOString(),"tryToListen()");
tryToListen();

// we stop listening
setTimeout(fastify.close, 30000);
```

### Expected Behavior

The expected behavior is for no callback to be register if the listen() attempt fails such that a later successful listen should only call the current callback and not any of the previous callback functions passed to any listen attempts.

The current behavior is that the function is registered as a success callback even if it fails to listen.

A possible workaround would be to retry connecting with a callback that has no path for when there is no error.

There must be a path in the code that registers the callback as a function to call on successful connection, this path seems to be hit even when the connection fails.

Another option is that this is a documented expected behavior in which case it should be in the documentation.

**Comment by climba03003** [comment] 2024-06-12 07:05
This is the line which cause problem.
https://github.com/fastify/fastify/blob/caaeb9fc3a928bb4df4c636468553df135d82edb/lib/server.js#L112

**Comment by metcoder95** [comment] 2024-06-12 07:54
The multiple-calls seems valid to `avvio` API definitions, tho on `fastify` can lead to confusion.
Maybe we can keep some sort of flag per-callback to verify wether or not to call it given the attempt.

We do not mark the server as `failed` when failed to start listening, I imagined was designed with multiple calls in mind?

**Comment by kryztoval** [comment] 2024-06-13 05:12
I think multiple calls make sense in other contexts. Such as when setting up plugins or setting up routes which can hit several functions and the order matters.

But on the listen() function it doesn't seem to make sense to register a callback for when the function can connect. Specially since there is no native mechanism to auto retry the connection, there doesn't seem to be an endpoint to retry the connection with the previous parameters either, and I am unsure if the ready state can change for it to be triggered again.

Also every single point in the documentation points to exiting the process as soon as it fails.

Finally this seems like a problem because after 10 failed attempts to listen() you will get a node warning message stating this:
`(node:22408) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 listening listeners added to [Server]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(Use 'node --trace-warnings ...' to show where the warning was created)`

**Comment by metcoder95** [comment] 2024-06-14 07:56
Yeah, that's somehow expected given how the `listen` works Today.

I imagine multiple-calls can be helpful in situations when, e.g. you are waiting for a `port` to be freed to listen on it. But there are better ways to manage that.

From my side, I believe it should be fine to avoid multiple-calls to `listen` when an error happened.
We can take advantage of the new major to make it default, and backport a warn in case there are implementations that rely on it Today.

**Comment by climba03003** [comment] 2024-06-14 08:51
I am closing the issue because it is the same behavior without `fastify`.
We have no way to prevent multiple call from the `net.listen`.

```js
/* common settings */
const host = "0.0.0.0";
const port = 3033;

/* Helper to block the port */
import net from 'node:net';
const server = net.createServer();
server.listen(port, host, function () {
  setTimeout(serverClose, 5000);
});

/* Helper function to free the port */
function serverClose() {
  server.close(() => { })
}

/* MRE starts here */
const server2 = net.createServer();
function tryToListen() {
  function callback(err,address) {
    if(err) {
      console.log((new Date()).toISOString(),"tryToListen.then{}",err.toString());
      setTimeout(tryToListen, 1000);
    } else {
      console.log((new Date()).toISOString(),"tryToListen.else{}");
    }
  }
  server2.once('error', callback)
  server2.listen({host: host, port: port}, callback);
}

//Let's fire the code
console.log((new Date()).toISOString(),"tryToListen()");
tryToListen();

// we stop listening
setTimeout(server2.close, 10000);
```

**Closed by climba03003** 2024-06-14 08:51 UTC
