### ISSUE TITLE
Can't able to set-up the headers when streaming

### ISSUE THREAD

**Issue by iserioton** [fastify/fastify#4923] opened 2023-07-21 11:01 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

8.2.0

### Node.js version

18.16.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Window 10

### Description

```
const stream = fs.createReadStream(filePath);
reply
  .type("application/json")
  .header("Access-Control-Allow-Origin", "*")
  .header("Content-Length", fs.statSync(filePath).size);
reply.send();
return stream.pipe(reply.raw);
```

I can't able to set up the headers, I also set up the fastify/cors

```
server.register(cors, {
  origin: "*",
});
```

### Steps to Reproduce

Follow the above description

### Expected Behavior

Should have those headers in response!

**Comment by Uzlopak** [comment] 2023-07-21 11:06
Closing as duplicate of https://github.com/fastify/fastify-cors/issues/259

Also @iserioton is trying to stream directly to reply.raw, instead the way it has to be done, by sending the stream like reply.send(stream).

**Closed by Uzlopak** 2023-07-21 11:06 UTC
