### ISSUE TITLE
query string is not being parsed in middleware handlers

### ISSUE THREAD

**Issue by phra** [fastify/fastify#103] opened 2017-06-11 14:36 UTC
hi,

while implementing the fastify integration for [graphql-server](https://github.com/apollographql/graphql-server) i have noticed that in the middleware handler you have to manually parse the query string if you need access to while in the route handler it comes already parsed.

is this the expected behaviour? (in express it comes parsed in middlewares too)

you can see the difference between express and fastify integrations:
- https://github.com/phra/graphql-server/blob/89461c408ab1b62bed36624258b1f0f778f5e8de/packages/graphql-server-fastify/src/fastifyApollo.ts#L26
- https://github.com/phra/graphql-server/blob/89461c408ab1b62bed36624258b1f0f778f5e8de/packages/graphql-server-express/src/expressApollo.ts#L30

**Comment by delvedor** [comment] 2017-06-11 15:15
Hi! Yes it's the expected behavior as you can see [here](https://github.com/fastify/fastify/blob/master/docs/Lifecycle.md).
The parsing is done after the routing. If you want you can use the `preHandler` hook, that gives you everything you need :)

**Comment by mcollina** [comment] 2017-06-11 15:37
I think you should not use middlewares for integrating with Apollo, but rather develop a full blown plugin for Fastify.

**Comment by phra** [comment] 2017-06-11 16:10
i can investigate also that way, for now i just followed the structure of other integrations.
can you please give me additional infos on the solution you are thinking about?

as i can see the requirements to make apollo works are:
- ability to intercept only certain paths (`/graphql` and `/graphiql`)
- ability to access to the `req.body` for POST or `req.query` for GET
- ability to write raw data in the `Reply` stream
- ability to close the `Reply` stream

you can also find the actual example usage with the middleware solution [here](https://github.com/phra/graphql-server/blob/89461c408ab1b62bed36624258b1f0f778f5e8de/packages/graphql-server-fastify/src/examples/index.ts)

thanks.

**Comment by mcollina** [comment] 2017-06-11 16:30
You should use the plugin interface, not the middleware one. There is plenty of docs in the repo, so there should be all that you need.
All the requirements you are listing can be implemented using the normal fastify API.

Have a look and let us know if you need any specifics details.

**Comment by phra** [comment] 2017-06-11 16:35
ok, i'll let you know guys. thanks for the suggestion.

**Comment by delvedor** [comment] 2017-06-20 09:11
Closing this, feel free to reopen if you have some issues :)

**Closed by delvedor** 2017-06-20 09:11 UTC

**Comment by coopnd** [comment] 2017-07-20 16:36
I'd seen this start over at Apollo (apollographql/apollo-server#402, apollographql/apollo-server#421).  I assume they'll include it eventually since they have an option for micro.  

But I wanted to port a project from work that runs with Apollo and express over to fastify.  I like the possibilities with hooks for some use cases better than clunky express (authn, authz, graphql context, etc.).  mcollina mentioned it as a plugin, so I took a stab at my first OSS project and made [fastify-apollo](https://github.com/coopnd/fastify-apollo).  I hope an Apollo server lines up with fastify's ecosystem.

**Comment by mcollina** [comment] 2017-07-20 17:26
@coopnd this is amazing work! Would you like to send us a PR to the README https://github.com/fastify/fastify#ecosystem

Let us know if you get any bugs in fastify, open them or send PRs.

**Comment by delvedor** [comment] 2017-07-20 18:16
Awesome, thanks! :)

**Comment by phra** [comment] 2017-07-20 19:00
@coopnd good work! 🚀
