### ISSUE TITLE
Memory Leak: fastify instance kept in memory after calling .close()

### ISSUE THREAD

**Issue by johannes-wtfoxtrot** [fastify/fastify#4843] opened 2023-06-22 07:44 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.13.0

### Node.js version

v18.16.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.0.1

### Description

We are experiencing OOM errors in our tests, both locally (macOS) and in CI (linux).

After some analysis we found that the fastify instances are kept in memory even after `.close()` was called.

We were able to reproduce this in a minimal reproduction, where only the repeated invocation of `Fastify().close()` leads to the allocation of more and more memory.

![Screenshot 2023-06-22 at 09 33 19](https://github.com/fastify/fastify/assets/111499660/8d43755b-d406-46fa-827b-d640d865d0cd)

What looks interesting is the `connectionsCheckingInterval`. This is new in Node.js v18.0.0: https://nodejs.org/api/http.html#httpcreateserveroptions-requestlistener. When running the script with Node.js v16.13.0, memory still increases, but not as much and there are no Router/Server instances in memory after the script has finished.

### Steps to Reproduce

```
// memory-test.js
const Fastify = require('fastify')

const initialRss = process.memoryUsage().rss

async function main() {
  for (let i = 0; i < 2000; i += 1) {
    if (i % 100 === 0) {
      global.gc()
      console.log('server', i, process.memoryUsage().rss - initialRss)
    }
    const server = Fastify()
    // eslint-disable-next-line no-await-in-loop
    await server.close()
  }
  await new Promise(resolve => setTimeout(resolve, 1000))
  global.gc()
  debugger
}

main()
```

Run with `node --expose-gc ./memory-test.js` to see logs or `node --inspect-brk --expose-gc ./memory-test.js` to analyse memory allocation.

### Expected Behavior

Fastify instances being freed after calling .close().

**Comment by johannes-wtfoxtrot** [comment] 2023-06-22 07:48
Actually I was just able to reproduce this with `createServer().close()` directly from `http`. 
I don't see any existing issues and will open one in https://github.com/nodejs/node/ 👀.

Maybe this issue is still helpful for people who have memory problems with fastify.

**Comment by johannes-wtfoxtrot** [comment] 2023-06-22 08:04
I thought this might be an issue of `http` server, but when using `const { createServer } = require('http')` directly, memory is cleaned up.

**Comment by metcoder95** [comment] 2023-06-22 21:19
I've did an initial assessment of this and it really does not seems Fastify is leaking memory at all if used correctly.

In the example you are giving, you are forgetting to call `server.listen()` which triggers not only the machinery within `fastify` but also the Node's `http` internals that allows the to work.
My initial assumption is that creating constant server instances without listening to it causes Node to hang several references and not be free as never used (haven't checked Node.js internals yet).

When omitting the `server.listen` machinery, indeed, the memory grows exponentially through several reads, as shown in the following image:

<img width="208" alt="image" src="https://github.com/fastify/fastify/assets/10200776/c5f4b2d0-53ee-45dc-9a29-1acc54a72914">

These are snapshots at 100th, 300th and 500th iteration, growing exponentially on every iteration.

>__Note__: Had to do it in this way as the Chrome debugger was failing to show it the timeline


Instead, if calling the server properly, this behaviours wipes out:
<img width="1059" alt="image" src="https://github.com/fastify/fastify/assets/10200776/6ea3298c-5658-4fee-bd2c-ae03c6d71c8d">

On average, the memory remains within 11 MB.

**Comment by mcollina** [comment] 2023-06-25 11:06
The code above is actually valid, there should be no need to call `listen()` in Fastify. It looks like we are leaking some memory in this case.

**Comment by mcollina** [comment] 2023-06-25 11:08
@metcoder95 did you figure out where is the leak? Do we have to call `httpServer.close()` anyway even if the server wasn't started?

**Comment by metcoder95** [comment] 2023-06-25 11:40
Not yet, I'm planning to do it over the week. So far this is what I've noticed when doing the samples:

1. It only happens when not calling `.listen` at the application
2. When calling `.listen` and subsequently `.close`, the memory leak is not present (including the fact of the multiple bindings that can be made)
3. Using `.ready` does not resolve the issue, it remains in the same state

I have an initial assumption that the culprit might be around the `.onClose` hook, as when called we do not do "manual cleanup" of the server but rather depend on the [`listening` state](https://github.com/fastify/fastify/blob/433439f94c2c82ba6c15791fe74c7e8bb0daf4a4/fastify.js#L429). Haven't confirmed my theory yet, but I'm planning to work on it this week

**Comment by metcoder95** [comment] 2023-06-27 21:04
Coming back to the issue, I can confirm that this statement is basically the reason of the memory leak:

>Do we have to call httpServer.close() anyway even if the server wasn't started?

I've been playing with different combinations, and only when calling `httpServer.close` the leak is gone.

With the following code, the memory of the process behaves as expected. It frees the server memory as soon as they are not referenced anymore.

```js
async function main () {
  let i = 0
  while (true) {
    if (i % 100 === 0) {
      global.gc()
    }
    const server = Fastify()
    await server.listen()
    // eslint-disable-next-line no-await-in-loop
    await server.close()
    i++
  }
}
```

>__Note__: The columns goes as follows: `New`, `Deleted`, `Delta`, `Alloc. Size`, `Freed Size`, and `Size Delta` respectively

This is the memory comparison between snapshots before the GC is explicitly called (100 iterations before calling the GC):
<img width="1510" alt="image" src="https://github.com/fastify/fastify/assets/10200776/89af813a-bd72-491d-bcc1-776e7e7dc934">


And this is the new allocation after calling the GC:
<img width="1514" alt="image" src="https://github.com/fastify/fastify/assets/10200776/c11f1b23-e53c-4203-ac38-baa2f63bfb00">

Now, with the following code:
```js
async function main () {
  let i = 0
  while (true) {
    if (i % 100 === 0) {
      global.gc()
    }
    const server = Fastify()
    // await server.listen()
    // eslint-disable-next-line no-await-in-loop
    await server.close()
    i++
  }
}
```

The results change drastically. A similar process, comparison before calling the GC after 100 iterations:
<img width="1516" alt="image" src="https://github.com/fastify/fastify/assets/10200776/fcc76340-f388-407e-b2e5-4e0f09831d8e">

After calling the GC, and creating a new Fastify instance:
<img width="1504" alt="image" src="https://github.com/fastify/fastify/assets/10200776/ec649ee1-e8ed-4ebc-a50a-5819330b22df">

We just pilled up more memory distributed between the instances required for Fastify to work (i.e. `Router` for the two binding servers, `Reply` and `Request` objects, etc.).

By removing the following line (or exchanging it to use `fastify[kState].closing` instead), the memory pattern goes back to normal as if we were listening and closing the server under normal circumstances:
https://github.com/fastify/fastify/blob/49b416c8f58190e393f782478d70a00f4e054e82/fastify.js#L429

It seems that most of the moving pieces of fastify are stuck to the `server` instance and never removed due to not calling `httpServer.close`. But that is just my initial assumption.

**Comment by mcollina** [comment] 2023-06-29 19:14
Note that this is a memory leak in Node.js: https://github.com/nodejs/node/issues/48604.

**Comment by mcollina** [comment] 2023-06-29 19:20
Here is the minimal fix we can do: https://github.com/fastify/fastify/pull/4860.

**Closed** 2023-06-30 09:30 UTC
