### ISSUE TITLE
Value of `request.url` when using `.inject` differs from a real server

### ISSUE THREAD

**Issue by runeh** [fastify/fastify#3257] opened 2021-08-13 10:35 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.20.1

### Node.js version

v14.17.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

When using `app.inject` in a test, the value of `request.url` is different from what it would be when doing the same request using running fastify server for some paths.

It seems some sanitization is applied to the URL only in test. This applies to URLs with two slashes, such as `http://example.org//two-slashes`.

### Steps to Reproduce

There is a repo with a reproduction here: https://github.com/runeh/fastify-inject-tc

- create an app with a handler that listens to a wildcard path
- make a request using `app.inject` that requests a path with two slashes, such as `//foo`
- observe the value of `request.url` in the handler.

### Expected Behavior

The value of `request.url` when requesting

```
http://localhost:3000//foo
```

should be identical to the value when running

```
app.inject({ method: "GET", url: "//foo" })
```

The actual behaviour is that `app.inject` changes the path to just be `/`

**Comment by mcollina** [comment] 2021-08-13 10:46
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mcollina** [comment] 2021-08-13 10:47
The required fix might need to be done in light-my-request.

**Comment by runeh** [comment] 2021-08-13 10:51
> Would you like to send a Pull Request to address this issue? Remember to add unit tests.

I'll give it a try over the weekend.

**Comment by climba03003** [comment] 2021-08-13 11:30
> 
> 
> > Would you like to send a Pull Request to address this issue? Remember to add unit tests.
> 
> I'll give it a try over the weekend.

It is basically related this line.
https://github.com/fastify/light-my-request/blob/master/lib/parseURL.js#L17

`//foo` will be parsed as `http://foo/` because url starting with `//` will respect the page protocol when parsing. 

It should be a correct behavior for `url` option but not `path`.

**Comment by LobRockyl** [comment] 2021-08-21 05:36
Could I have a stab at it?

**Comment by mcollina** [comment] 2021-08-21 08:04
Go for it!

**Comment by LobRockyl** [comment] 2021-08-21 16:35
> Go for it!

So I am doubting if this is related to this: https://github.com/fastify/light-my-request/blob/master/lib/parseURL.js#L17
I did a few logs and tweaks
So doing this change in the code:
`          
          
          module.exports = function parseURL (url, query) {
          let x=new URL(url,BASE_URL)
          x.pathname='//foo'
        
          const result = typeof url === 'object'
            ? Object.assign(x, url)
            : new URL(url, BASE_URL)
          console.log("url here "+ url)
          
        
          const merged = Object.assign({}, url.query, query)
          Object.keys(merged).forEach(key => {
            const value = merged[key]

          if (Array.isArray(value)) {
            result.searchParams.delete(key)
            value.forEach(param => {
              result.searchParams.append(key, param)
            })
          } else {
            result.searchParams.set(key, value)
          }
        })
        console.log("object" + result)
        return result
}
`

Produced this

`   Expected: {"url": "//foo.com"}
     Received: "{\"url\":\"/\"}"

       6 |     url: "//foo.com",
       7 |   });
    >  8 |   expect(res.body).toEqual({ url: "//foo.com" });
         |                    ^
       9 | });
      10 |

      at Object.<anonymous> (app.test.js:8:20)

    console.log
    url here //foo.com

      at parseURL (node_modules/light-my-request/lib/parseURL.js:20:11)

    console.log
    objecthttp://foo.com/

      at parseURL (node_modules/light-my-request/lib/parseURL.js:21:11)
`
So could you direct me towards the right direction?  I think the problem should be elsewhere

**Comment by mcollina** [comment] 2021-08-21 16:51
Have you tried adding a unit test just in light-my-request to reproduce the issue?

**Comment by climba03003** [comment] 2021-08-21 17:08
> So could you direct me towards the right direction? I think the problem should be elsewhere

@LobRockyl The problem is exactly how `URL` parse the input.

You can see the result from below snippet.

```js
new URL('//foo', 'http://localhost/')
```

```js
const result = typeof url === 'object'
 ? Object.assign(x, url) // change here do not make any different
 : new URL(url, BASE_URL) // here is the problem because `url` is a string
 ```

**Comment by LobRockyl** [comment] 2021-08-21 17:58
> > So could you direct me towards the right direction? I think the problem should be elsewhere
> 
> @LobRockyl The problem is exactly how `URL` parse the input.
> 
> You can see the result from below snippet.
> 
> ```js
> new URL('//foo', 'http://localhost/') // result: http://foo/
> ```
> 
> ```js
> const result = typeof url === 'object'
>  ? Object.assign(x, url) // change here do not make any different
>  : new URL(url, BASE_URL) // here is the problem because `url` is a string
> ```

So I changed that line to 

`
        let x=new URL(url,BASE_URL)
         x.pathname=url

         const result = typeof url === 'object'
           ? Object.assign(new URL(BASE_URL), url)
           : x
          console.log("url here "+ url)

`

![Screenshot 2021-08-21 at 11 24 38 PM](https://user-images.githubusercontent.com/45710269/130330859-1e39c778-7d1a-4e67-a67b-934f5b4a7221.png)

**Comment by LobRockyl** [comment] 2021-08-22 05:30
> Have you tried adding a unit test just in light-my-request to reproduce the issue?

No. I am using the repo https://github.com/runeh/fastify-inject-tc and it has a jest to test the file where the request is made with app.inject , should I add it?

**Comment by Eomm** [comment] 2021-08-22 07:42
> Is this correct?

Ues, it is a good process to create the test before changing the code, so you can focus on what you set and the output you expect

> should I add it?

If you do the code changes (test + implementation) on the light-my-request code base, then you could arrange a PR and share your work with the whole community 🔝

**Comment by LobRockyl** [comment] 2021-08-22 09:10
Sure, I will raise a PR

**Comment by LobRockyl** [comment] 2021-08-22 12:28
One more query is that about the already existing tests in light-my-request. Some of them are not working :
![Screenshot 2021-08-22 at 5 57 07 PM](https://user-images.githubusercontent.com/45710269/130355118-d9607af9-bb61-436b-a72f-082a3f3bc6eb.png)

So the change I have done in light-my-request is
![Screenshot 2021-08-22 at 5 58 33 PM](https://user-images.githubusercontent.com/45710269/130355178-eee62e91-541d-408c-ae98-1e95856e52ea.png)

What am I missing?

**Comment by climba03003** [comment] 2021-08-22 15:37
I would suggest doing the below one.

```js
if ( typeof url === 'string' && url.startWiths('//') ) {
  url = BASE_URL + url
} 
```

**Comment by LobRockyl** [comment] 2021-08-22 17:00
> I would suggest doing the below one.
> 
> ```js
> if ( typeof url === 'string' && url.startWiths('//') ) {
>   url = BASE_URL + url
> } 
> ```

Hi, thanks for that. It solved it tests which were already there arer running no problems but the test I created is not working somehow. Basically this repo https://github.com/runeh/fastify-inject-tc I pulled and did the changes and it works no problems but here jest unlike the one used in light-my-request(here tap is used). Is my test code correct?

![Screenshot 2021-08-22 at 10 27 23 PM](https://user-images.githubusercontent.com/45710269/130363547-dc447b9b-520e-4676-884f-6185204f1f3f.png)

The jest one in the https://github.com/runeh/fastify-inject-tc repo works as a charm:
![Screenshot 2021-08-22 at 10 28 32 PM](https://user-images.githubusercontent.com/45710269/130363573-5fbdb0f4-1878-4148-b117-214bdaaa1c04.png)

There's no much difference in the test code in both the codes but can't figure why one works and the other doesn't

**Comment by runeh** [comment] 2021-08-22 17:55
@LobRockyl Thanks for picking up this! I only got as far as adding some failing tests, but feel free to grab those if you want. Added them as unit tests for just the parse function. https://github.com/runeh/light-my-request/commit/9a8131ac747d5e919730e0ee38b06ffa4fa5b57f

**Comment by runeh** [comment] 2021-08-22 17:57
Related, renaming the function to `parsePathOrUrl`, or something along those lines, might make sense?

**Comment by LobRockyl** [comment] 2021-08-22 18:34
So I could pass the tests but somehow code coverage is less. Can someone help:
![Screenshot 2021-08-23 at 12 03 00 AM](https://user-images.githubusercontent.com/45710269/130366117-69005428-86f0-4f75-81b0-eb0ea2dc6d3d.png)

**Comment by LobRockyl** [comment] 2021-08-22 18:36
> @LobRockyl Thanks for picking up this! I only got as far as adding some failing tests, but feel free to grab those if you want. Added them as unit tests for just the parse function. [runeh/light-my-request@9a8131a](https://github.com/runeh/light-my-request/commit/9a8131ac747d5e919730e0ee38b06ffa4fa5b57f)

I will keep these in mind. Thanks!

**Comment by mcollina** [comment] 2021-08-22 18:47
> So I could pass the tests but somehow code coverage is less. Can someone help:
> 
> ![Screenshot 2021-08-23 at 12 03 00 AM](https://user-images.githubusercontent.com/45710269/130366117-69005428-86f0-4f75-81b0-eb0ea2dc6d3d.png)
> 
> 

You need to write a test that covers line 16.

**Comment by LobRockyl** [comment] 2021-08-22 21:38
Finally it's solved all tests passed, additional tests by @runeh was added and passed.
Please check this PR : https://github.com/fastify/light-my-request/pull/156

**Closed** 2021-08-23 07:53 UTC
Labels: bug, good first issue
