### ISSUE TITLE
Support for asynchronous validation

### ISSUE THREAD

**Issue by avaragado** [fastify/fastify#511] opened 2017-12-04 14:18 UTC
Looks to me as though fastify doesn't currently support async validation. Is this right? I haven't been able to make it work, at least, and a pass through the code hasn't found anything to suggest it should. The doc says nothing about async validation.

It would be great if fastify handled this, as the validation libraries mentioned in the doc, ajv and joi, both support async validation.

**Comment by zenflow** [comment] 2017-12-04 15:30
Related discussion: https://github.com/fastify/fastify/pull/167#issuecomment-329304812

+1 for this feature request!

**Comment by mcollina** [comment] 2017-12-04 15:44
I'm a bit lost on the _need_ for async validation. What operation do you plan to do asynchronously?  Validating a JSON seems a straight synchronous operation to me.
Allowing user to send bad-input to schedule async executions might open up some DoS possibilities.

**Comment by avaragado** [comment] 2017-12-04 15:50
A very common async validation requirement is to check the availability of a username.

**Comment by zenflow** [comment] 2017-12-04 17:26
I wouldn't say there is a *need* for this, since extra validation can be done in the handler, but it would be **very** convenient. 

I could think of tons of examples where it would be useful: (1) @avaragado's example above, (2) checking the existence of a referenced model, (3) checking details of a referenced model (e.g. for a call to `POST /invoices/pay?invoiceId=321`, invoice 321 must be unpaid), and so on. All the examples I've thought of revolve around the idea that we often need to do some I/O to validate the *contents* (not the format) of some request.

If added, this feature could be very powerful combined with something like [react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form) to provide a **simple** & **robust** way of building forms that are both secure (full validation server-side) and with great UX/performance (full validation client-side).

**Comment by delvedor** [comment] 2017-12-04 18:33
Can the [`preHandler` hook](https://github.com/fastify/fastify/blob/master/docs/Hooks.md) solve this need for you?

**Comment by avaragado** [comment] 2017-12-04 19:08
I'm trying to avoid having to write validation code twice in different ways. Being able to use the same validation schema client-side and server-side is a big win. Right now I can do that as long as the validation is synchronous. As soon as I need some form of asynchronous validation, I'm forced to write two chunks of code, with all the obvious problems.

**Comment by allevo** [comment] 2017-12-04 20:07
I'm 👎 

Truly the `jsonschema` doesn't validate the content but the shape.

the `400` status code should be used *only* when the data is malformed. See [here](https://httpstatuses.com/400) or [here](https://tools.ietf.org/html/rfc7231#section-6.5.1)

@zenflow  in your example you are not validating the shape of the body:
1. In the registration form (for example) you need to return a [409 Conflict](https://tools.ietf.org/html/rfc7231#section-6.5.8)
2. [410 Gone](https://tools.ietf.org/html/rfc7231#section-6.5.9) or something like that
3. [410 Gone](https://tools.ietf.org/html/rfc7231#section-6.5.9) or something like that

**Comment by mcollina** [comment] 2017-12-06 12:10
Does AJV fail early if the rest of the JSON is not valid, or does it always perform the async validation?
I'm very conflicted by this request, as it seems that validations are not something that should be async to me. Specifically because when validating if something exists, we would typically want to load that thing because we need some other property. Doing an async validation followed by a look means doing 2 database round-trips.

**Comment by zenflow** [comment] 2017-12-06 19:18
> Doing an async validation followed by a look means doing 2 database round-trips.

Not necessarily. I would use something like [dataloader](https://github.com/facebook/dataloader), or even just [p-memoize](https://www.npmjs.com/package/p-memoize) to make sure my two validations (e.g. invoice exists and invoice is unpaid) result in only 1 database request

**Comment by zenflow** [comment] 2017-12-06 20:59
> Truly the jsonschema doesn't validate the content but the shape

`jsonschema` is not restricted to validating just the shape/structure/format. That is just what it is good at doing out-of-the-box. Surely some developers are using it to validate content.. This is why Ajv supports [custom async keywords](https://github.com/epoberezkin/ajv#addkeywordstring-keyword-object-definition---ajv). And I don't see any fundamental reason why jsonschema shouldn't be used this way (where possible in respect to performance, etc.). Fundamentally, we use jsonschema to describe our json documents.. and we have `title` and `description` keywords to describe their _contents_ for humans-only.. (e.g. `description` might say "id of an *unpaid* invoice*) Why not allow that requirement to be machine-readable too?

> the 400 status code should be used only when the data is malformed. See here or here

> The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

"malformed request syntax" is just an *example* of where a 400 error should be used. The spec actually *defines* it in a more general way ("... perceived to be a client error") which I think allows for it to be used for invalid request content.

1. "409 Conflict" is not appropriate since the spec says "This code is used in situations where the user might be able to resolve the conflict and resubmit the request" and gives an example pretty different from our example
2. "410 Gone" may be appropriate in some of these cases
3. "410 Gone" doesn't seem to apply to my specific example (for a call to POST /invoices/pay?invoiceId=321, invoice 321 must be unpaid). I read through [all the 4xx errors](https://tools.ietf.org/html/rfc7231#section-6.5) and none seem to fit except "400 Bad Request"

I don't think there is a specific 4xx status code to cover every kind of client error. Seems like 400 should be used as a generic "4xx Client Error" status code.

**Comment by avaragado** [comment] 2017-12-06 23:15
One other data point: the express middleware [express-validator](https://www.npmjs.com/package/express-validator), ~190K downloads in the last month, supports async validation.

**Comment by mcollina** [comment] 2017-12-06 23:21
> Not necessarily. I would use something like dataloader, or even just p-memoize to make sure my two validations (e.g. invoice exists and invoice is unpaid) (edit: plus getting/loading the entity to work with it imperatively) result in only 1 database request

More or less this indicates why it is a bad idea to do this, and why I won't recommend this to anyone: it adds a completely new layer of complexity for some convenience. However, I'm not stopping anyone to work on this: if supporting async validations __does not cause any performance regressions__ with sync validations / without validations, then I'm ok with landing such PR.

**Comment by delvedor** [comment] 2017-12-07 09:32
Our validation system is built to validate just the request object.
I think that if you want to make a more complex validation you should use the `preHandler` hook or the `beforeHandler` hook, which fully supports async operations and does not add any overhead to the framework itself.
Checkout our [docs](https://github.com/fastify/fastify/blob/master/docs/Hooks.md) about hooks :)

**Comment by mcollina** [comment] 2018-01-18 10:17
Closing because of https://github.com/fastify/fastify/pull/674.

**Closed by mcollina** 2018-01-18 10:17 UTC
Labels: discussion, feature request

**Comment by zenflow** [comment] 2018-02-08 00:41
@mcollina I think this may have been closed in error. This is not related to configuring Ajv, and is not Ajv-specific. It is a completely different issue than #493.

**Comment by zenflow** [comment] 2018-02-08 00:51
> More or less this indicates why it is a bad idea to do this, and why I won't recommend this to anyone: it adds a completely new layer of complexity for some convenience.

The same statement applies to computers in general - they add a completely new layer of complexity for some (very much) convenience. 

I think perhaps you underestimate *how much* convenience this would add. Being able to contain the business logic of json validation in a single place (json schema), rather than duplicating it in two places (front-end and back-end) would be *very* convenient, and (1) reduce overall complexity and (2) move complexity from the business logic level to the framework/infrastructure level.

**Comment by zenflow** [comment] 2018-02-08 01:17
> I think that if you want to make a more complex validation you should use the preHandler hook or the beforeHandler hook, which fully supports async operations and does not add any overhead to the framework itself.

@delvedor What type of overhead are you concerned about? Performance, complexity, and or something else? I want to prepare a PR, and make sure that there is no overhead in terms of performance, and next to no overhead in terms of complexity (I think this is possible). Are there any other concerns you have that would prevent you from approving such a PR?

I have concerns about the approach of (making a plugin) using hooks... Can the built-in validation be disabled so that the same `route.schema` property can be used? This would be necessary to mesh with other plugins that depend on that property, like fastify-swagger. Also it seems like making a plugin to add this one very simple feature would be overkill, and keeping feature parity with the built-in validation would be difficult.

**Comment by delvedor** [comment] 2018-02-08 09:38
@zenflow there is no way to support sync and async validation at the same time.
The validator would become a function with a `done` callback, then we should handle errors and add a new layer in our optimized path.
Async-await? Same thing, you should handle the promise and compromise again the optimized path.
Our validation system is designed to be extremely fast and not add any overhead to (y)our code.
Add a function with a callback and a different error handler means increase that overhead.

That's why I suggested you to use the `preHandler` or `beforeHandler`hooks, with them you can achieve what you need.
Even more, you can even design a very elegant api by using the `onRoute` hook.

```js
fastify.addHook('onRoute', (opts) => {
  if (opts.asyncValidation) {
    opts.beforeHandler = youAsyncValidationFunction // signature (req, reply, next)
  }
})

fastify.route({
  url: '/',
  method: 'POST'.
  asyncValidation: true,
  handler: yourHandler
})
```
[Hooks documentation](https://github.com/fastify/fastify/blob/master/docs/Hooks.md)

**Comment by yusuf-khamis** [comment] 2022-07-15 16:30
Hi, its now 2022 and I came across  this issue, I noticed for the async validation, it actually resolves later during route execution, this would be a helpful feature, for instance, in my case, I am validating an image to certain restricted formats and sizes, all require async, can we reopen this conversation?

**Comment by Eomm** [comment] 2022-07-16 17:20
How do you do that by using `ajv` and JSON schema?

**Comment by yusuf-khamis** [comment] 2022-07-24 19:39
> How do you do that by using `ajv` and JSON schema?

See code below @Eomm 

```
import Ajv from 'ajv';
import { fromBuffer } from 'file-type';
import sharp from 'sharp';

ajv.addKeyword({
  keyword: 'image',
  schemaType: 'object',
  modifying: true,
  $data: true,
  async: true,
  metaSchema: {
    type: 'object',
    required: [
      'type',
    ],
    dependencies: {
      maxHeight: ['maxWidth'],
      maxWidth: ['maxHeight'],
    },
    properties: {
      type: {
        type: 'string',
        enum: ['png', 'jpg'],
      },
      ratio: {
        type: 'number',
        minimum: 0,
      },
      minHeight: {
        type: 'number',
        minimum: 0,
      },
      minWidth: {
        type: 'number',
        minimum: 0,
      },
      maxHeight: {
        type: 'number',
        minimum: 0,
      },
      maxWidth: {
        type: 'number',
        minimum: 0,
      },
    },
  },
  error: {
    message: 'Invalid image data',
  },
  async validate(schema, data, parentSchema, { parentData, parentDataProperty }) {
    let buffer = Buffer.from(data, 'base64');

    const fileType = await fromBuffer(buffer);

    if (schema.type !== fileType?.ext) {
      return false;
    }

    if (Object.keys(schema).length > 1) {
      const metadata = await sharp(buffer).metadata();

      if (schema.ratio && schema.ratio !== (metadata.width / metadata.height)) {
        return false;
      }

      if (schema.minHeight && schema.minHeight > metadata.height) {
        return false;
      }

      if (schema.minWidth && schema.minWidth > metadata.width) {
        return false;
      }

      if (schema.maxWidth || schema.maxHeight) {
        buffer = await sharp(buffer)
          .resize({
            width: schema.maxWidth,
            height: schema.maxHeight,
            fit: 'inside',
          })
          .toBuffer();

        parentData[parentDataProperty] = buffer;
      }
    }

    return true;
  },
});
```
