### ISSUE TITLE
Syntax Error On Fastify 4 and node docker latest (18 version)

### ISSUE THREAD

**Issue by FrancescoMasaia** [fastify/fastify#4015] opened 2022-06-14 09:11 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.2

### Plugin version

3.0.1

### Node.js version

18

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

19.10

### Description

When I'm starting the server via docker it says that a syntax error is appearing, changing to node 16 everything is resolved

Attaching to qrdemobackend_QRDemo_1
QRDemo_1  | /app/node_modules/fastify/lib/server.js:38
QRDemo_1  |       const hostPath = listenOptions.path ? [listenOptions.path] : [listenOptions.port ?? 0, listenOptions.host ?? 'localhost']
QRDemo_1  |                                                                                         ^
QRDemo_1  | 
QRDemo_1  | SyntaxError: Unexpected token '?'
QRDemo_1  |     at wrapSafe (internal/modules/cjs/loader.js:1063:16)
QRDemo_1  |     at Module._compile (internal/modules/cjs/loader.js:1111:27)
QRDemo_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
QRDemo_1  |     at Module.load (internal/modules/cjs/loader.js:996:32)
QRDemo_1  |     at Function.Module._load (internal/modules/cjs/loader.js:896:14)
QRDemo_1  |     at Module.require (internal/modules/cjs/loader.js:1036:19)
QRDemo_1  |     at require (internal/modules/cjs/helpers.js:72:18)
QRDemo_1  |     at Object.<anonymous> (/app/node_modules/fastify/fastify.js:34:54)
QRDemo_1  |     at Module._compile (internal/modules/cjs/loader.js:1147:30)
QRDemo_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)

### Steps to Reproduce

Use docker with latest node version, I think that is possible to reproduce it with node 18 without docker too

**Comment by mcollina** [comment] 2022-06-14 09:45
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by FrancescoMasaia** [comment] 2022-06-14 10:57
This code is needed to reproduce the problem, I've tried NodeJS 13.9.0 too and it gives the same error again version 14 doesn't

```javascript
const fastify = require('fastify')

server.listen({ port: 3000, host: "0.0.0.0" }, async (err) => {
    if (err) {
        console.log(err);
        throw err;
    }
    console.log("listening");
});
```

**Comment by FrancescoMasaia** [comment] 2022-06-14 10:58
This is the generic error without extra console logs
const hostPath = listenOptions.path ? [listenOptions.path] : [listenOptions.port ?? 0, listenOptions.host ?? 'localhost']
                                                                                        ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1067:16)
    at Module._compile (internal/modules/cjs/loader.js:1115:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/francesco/Documents/testfastify/node_modules/fastify/fastify.js:34:54)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)

**Comment by climba03003** [comment] 2022-06-14 11:10
> This code is needed to reproduce the problem, I've tried NodeJS 13.9.0 too and it gives the same error again version 14 doesn't
> 
> ```js
> const fastify = require('fastify')
> 
> server.listen({ port: 3000, host: "0.0.0.0" }, async (err) => {
>     if (err) {
>         console.log(err);
>         throw err;
>     }
>     console.log("listening");
> });
> ```

`node@13` is expected to be fail since `nullish operator` is added in `node@14`.
And cannot reproduce it use `node@18` installed on `WSL`.

**Comment by FrancescoMasaia** [comment] 2022-06-14 11:18
in this [repo](https://github.com/FrancescoMasaia/Fastify-error-example) there is an example code with latest docker container for node that i was using on my server and got the error

**Comment by climba03003** [comment] 2022-06-14 11:29
No, I cannot reproduce with your repo. Note that your repo cannot be startup since no `server` variables is declared.
I added `const server = fastify({ logger: true })`

```
[testbackend] | {"level":30,"time":1655206089520,"pid":8,"hostname":"c08670660af5","msg":"Server listening at http://0.0.0.0:3000"}
[testbackend] | listening
```

**Comment by climba03003** [comment] 2022-06-14 13:24
I will close it since it should not be the problem of `fastify@4`.

**Closed by climba03003** 2022-06-14 13:24 UTC

**Comment by PierBover** [comment] 2022-06-29 17:10
I'm having the exact same issue using Ubuntu and Node 18.

This is my Docker file:

```
FROM ubuntu:latest

USER root

RUN apt update
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN apt -y install --no-install-recommends nodejs
RUN apt -y install --no-install-recommends npm

WORKDIR /usr/src/app

COPY package.json .
COPY package-lock.json .
RUN npm i --production

COPY . .

ENV NODE_ENV production
ENV PORT 8080
ENV HOST 0.0.0.0

CMD ["node", "index.js"]
```

Error:

```
Preparing to run: `node index.js` as root
2022/06/29 17:02:16 listening on [fdaa:0:24d2:a7b:a27f:280e:3e32:2]:22 (DNS: [fdaa::3]:53)
/usr/src/app/node_modules/fastify/lib/server.js:38
      const hostPath = listenOptions.path ? [listenOptions.path] : [listenOptions.port ?? 0, listenOptions.host ?? 'localhost']
                                                                                        ^
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/node_modules/fastify/fastify.js:34:54)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by climba03003** [comment] 2022-06-30 02:25
> I'm having the exact same issue using Ubuntu and Node 18.

@PierBover 
Nullish Operator is supported by `node@18` and `nodesource` is not a official image for `node`.
Please report to `nodesource` why there `node@18` is not supporting nullish operator.

You should really log which version of `node` is using inside the `container`.
In the previous issue, the user believe they are using `node@18` but they actually NOT.

**Comment by PierBover** [comment] 2022-06-30 02:34
Thanks @climba03003 I wasn't aware of that.

Unfortunately I can't use any of the official images based on Alpine since I need to install an apt package which is only available for Ubuntu.

When doing `apt install nodejs` you get v12. All the sources to install more modern versions on Ubuntu point to `nodesource`.

Thank again for the clarification. I will figure out a better way to install Node on Ubuntu.
