### ISSUE TITLE
When passing options to a plugin with a function, the prefix option returned from the function is not respected 

### ISSUE THREAD

**Issue by serdnam** [fastify/fastify#3771] opened 2022-03-14 18:44 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.4

### Node.js version

16.14.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Manjaro Linux 21.2.3

### Description

When registering a plugin with the `options` parameter as a function, and the function returns an object with a `prefix` key, Fastify does not respect this `prefix` value when registering routes within the plugin.

I have checked the documentation and did not find anything that would imply that this is intended behavior.

### Steps to Reproduce

```js
const fastify = require('fastify');

const server = fastify();

// Passing options as an object literal
server.register(async function (fastify) {
    fastify.get('/', async function (req, rep) {
        return { message: `Hello from this route! ${req.url}` };
    })
}, { prefix: 'route1' });

// Passing options with a function
server.register(async function (fastify) {
    fastify.get('/', async function (req, rep) {
        return { message: `Hello from this other route! ${req.url}` };
    })
}, (fastify) => ({ prefix: 'route2' }));


server.listen(3000);
```

```bash
# This works as expected, this route was registered within a plugin
# for which the options were in an object literal with the `prefix: 'route1'` value
$ curl localhost:3000/route1
{"message":"Hello from this route! /route1"}

# This does not work as expected, this route was registered within a plugin 
# where a function was passed as the options parameter, 
# a function that returns an object with the `prefix: 'route2'` value
$ curl localhost:3000/route2
{"message":"Route GET:/route2 not found","error":"Not Found","statusCode":404}

# The route described above ended up being registered as a root route
$ curl localhost:3000/
{"message":"Hello from this other route! /"}
```

### Expected Behavior

I expected the behavior to be as follows

```bash
$ curl localhost:3000/route1
{"message":"Hello from this route! /route1"}

$ curl localhost:3000/route2
{"message":"Hello from this other route! /route2"}

$ curl localhost:3000/
{"message":"Route GET:/ not found","error":"Not Found","statusCode":404}
```

That is, I expected Fastify's routing to respect the `prefix` option when the options were passed through a function.

**Comment by jsumners** [comment] 2022-03-14 19:01
Duplicate of https://github.com/fastify/help/issues/174

**Closed as completed** 2022-03-14 19:01 UTC
