### ISSUE TITLE
The stream has been destroyed - ERR_HTTP2_INVALID_STREAM 

### ISSUE THREAD

**Issue by mokimo** [fastify/fastify#1926] opened 2019-11-07 09:58 UTC
## 🐛 Bug Report

App crashing often with http2

Related Issue: https://github.com/fastify/fastify/issues/1494

```
internal/http2/compat.js:641
        throw err;
        ^

Error [ERR_HTTP2_INVALID_STREAM] [ERR_HTTP2_INVALID_STREAM]: The stream has been destroyed
    at Http2ServerResponse.write (internal/http2/compat.js:637:19)
    at IncomingMessage.ondata (_stream_readable.js:726:22)
    at IncomingMessage.emit (events.js:210:5)
    at IncomingMessage.Readable.read (_stream_readable.js:524:10)
    at flow (_stream_readable.js:999:34)
    at resume_ (_stream_readable.js:980:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
 {
  code: 'ERR_HTTP2_INVALID_STREAM'
}
```

## To Reproduce
TODO find out how to consistently reproduce / minimal project

Hoped that does it, but nope: _If you push F5 in the browser few times too fast / working in multiple tabs this bug often occurs:_

## Expected behavior
It should be ignored or logged instead of crashing

## Your Environment

- *node version*: 12.12.0 / 13.1.0
- *fastify version*: >=2.0.0
- *os*: MacOs High Sierra

**Comment by Eomm** [comment] 2019-11-07 17:28
I cannot reproduce with:

```js
const fs = require('fs')
const Fastify = require('fastify')
const fastify = Fastify({
  http2: true,
  https: {
    key: fs.readFileSync('./node_modules/fastify/test/https/fastify.key'),
    cert: fs.readFileSync('./node_modules/fastify/test/https/fastify.cert')
  }
})

fastify.get('/', function (req, reply) {
  reply.code(200).send({ hello: 'world' })
})

fastify.listen(3000, err => {
  if (err) { throw err }
})
```

and F5 constantly pressed `https://localhost:3000/`

Could you arrange a minimal project that reproduces the error?
Maybe you could try also others node 12 versions?

**Comment by mokimo** [comment] 2019-11-08 13:55
I just tested it with `node 13.1.0` still reproduces with the same error as posted initially, can't get a minimal example working sadly.

**Comment by Eomm** [comment] 2019-11-08 16:20
> Maybe it's related to our realtime updates that come in for a stream that has been destroyed

I don't understand.
Is your handler sending a stream (file or whatelse) not a simple json?

**Comment by aligator301** [comment] 2019-12-02 07:15
Hi,

When you attempt to make a HTTP2 Push then when you refresh the page very often then it is exceptionally easy to reproduce.

This is a severe bug as it kills the entire server:

`
if (req && req.raw && req.raw.stream && req.raw.stream.pushAllowed) {
        try {
            if (!req.raw.stream.aborted && !req.raw.stream.closed && !req.raw.stream.destroyed) {
                req.raw.stream.pushStream({
                    ':path': '/assets/fonts/firasans/fira-sans-v9-latin-500.woff2'
                }, function (err, stream, headers) {
                    if (err) {
                        request.log.warn(err);
                        return;
                    }
                    if (!stream.aborted && !stream.closed && !stream.destroyed) {
                        stream.respond({ ':status': 200, 'content-encoding' : encoding, 'content-type' : 'text/css'});
                        stream.end( wrapStream(encoding, fs.readFileSync( path.resolve(__dirname + '../../../public/fonts/firasans/fira-sans-v9-latin-500.woff2') )));
                    }
                });
            }

            if (!req.raw.stream.aborted && !req.raw.stream.closed && !req.raw.stream.destroyed) {
                req.raw.stream.pushStream({
                    ':path': '/assets/fonts/firasans/fira-sans-v9-latin-regular.woff2'
                }, function (err, stream, headers) {
                    if (err) {
                        request.log.warn(err);
                        return
                    }
                    if (!stream.aborted && !stream.closed && !stream.destroyed) {
                        stream.respond({':status': 200, 'content-encoding': encoding, 'content-type': 'text/css'});
                        stream.end(wrapStream(encoding, fs.readFileSync(path.resolve(__dirname + '../../../public/fonts/firasans/fira-sans-v9-latin-regular.woff2'))));
                    }
                });
            }
            
        } catch (ERR) {
            console.log('failed to push into stream', ERR);
        }
    }
`

No safeguarding to check the stream is still open/active seems to work (as above)

**Comment by mcollina** [comment] 2019-12-02 07:33
Great work @aligator301!

@fastify/core I think we should add that as a property of the reply object. What do you think?

**Comment by Eomm** [comment] 2019-12-10 21:43
@mcollina could you elaborate?

I would be really glad to see a snippet like this as a minimal reproducible problem:

```
const fs = require('fs')
const Fastify = require('fastify')
const fastify = Fastify({
  logger: true,
  http2: true,
  https: {
    key: fs.readFileSync('./node_modules/fastify/test/https/fastify.key'),
    cert: fs.readFileSync('./node_modules/fastify/test/https/fastify.cert')
  }
})

fastify.get('/', async function (request, reply) {
  request.raw.stream.pushStream({
    ':path': '/example.css'
  }, function (err, stream) {
    if (err) {
      request.log.warn(err)
      return
    }
    stream.respond({ ':status': 200, 'content-type': 'text/css' })
    // example.css: body{  background: red;}
    stream.end(fs.readFileSync('./example.css'))
  })
  reply.type('text/html')
  return `<!DOCTYPE html><html><head>
  <link rel="stylesheet" href="/example.css">
</head><body><h1>This is a heading</h1><p>This is a paragraph.</p></body></html>`
})

fastify.listen(3000, err => {
  if (err) { throw err }
})
```

With this code, I get some 404 when I refresh the page 3 click/sec

**Comment by mcollina** [comment] 2019-12-11 12:59
I mean, we might want to add an utility to call pushStream as a decorator in fastify. It can also be a separate plugin

**Comment by aligator301** [comment] 2019-12-12 06:43
Hej!

I can reproduce this instantly in my development but so far, cutting it down into a manageable and producible form has proven to be difficult, because it doesn't break! So. I will try to reproduce the error but it may also simultaneously unravel the true cause of the error that kills the server and potentially enlighten me as to how to fix it and why it breaks. 

A little insight:

My code is a headless eCommerce (with API/Shopify) solution sitting on Fastify with React, operating as SSR + Hydrated CSR. I am attempting to leverage HTTP2 for performance gain. This was previously working with Express + SPDY and never had issues, but SPDY broke when I moved to Node 12, so I moved to HTTP2 within Node, and also Fastify, while adding SSR functionality. So it's a little complex in there. I will continue to investigate and provide feedback if it helps.

When I open two tabs next to each-other in my browser and request from Fastify, it instantly breaks the entire server, which I think shouldn't be possible in any scenario, even if it is an uncaught Promise floating around.

A

**Comment by aligator301** [comment] 2019-12-12 13:43
Hi!

I have an update - I have managed to somehow fix the problem... without truely identifying it. However, it seems to be an interesting interaction between the following:

- High load on Fastify
- Fastify Compression Plugin <-- removing this fixed it entirely, now I compress the HTML using zlib "by hand" and have 0 errors
- React DOM RenderToString (SSR) potentially due to AJAX calls back into website
- async promise chain for route

A

**Comment by aligator301** [comment] 2020-01-07 04:31
Hi!

It appears to be the following:-

When an ajax/fetch/etc. call is made within SSR on the server back to itself calling HTTP2 and something goes wrong in the SSR. It breaks the server entirely.

This is a horrendous fix:


fastify.server.on('error', function(error) {
    console.log('Issue raised in connection', error);
});


A

**Comment by Eomm** [comment] 2020-04-10 22:05
It seems related to #2190 

Whenever it will be released could you check if this issue has been solved for you?

**Comment by aligator301** [comment] 2020-04-11 21:25
I'm happy to check when it's released!

**Comment by mcollina** [comment] 2020-04-12 09:45
Released v2.13.1

**Comment by mokimo** [comment] 2020-04-14 11:08
Still persists in fastify@2.13.1 sadly

**Comment by Eomm** [comment] 2020-04-15 06:37
My bad: the fix has been merged in `next` not in the `v2` 🤕

**Closed** 2020-04-15 10:35 UTC
Labels: bug, need info

**Comment by inikulin** [comment] 2020-04-15 14:35
@mcollina Has it been released?
