### ISSUE TITLE
Investigation on TypeScript structure

### ISSUE THREAD

**Issue by climba03003** [fastify/fastify#4081] opened 2022-06-23 09:16 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently, the typing system of `fastify` is just good to use.
However, it restricted the usage on certain way and may not be good enough.
I open a new issue here for investigating how can we improve the typing system before `fastify@5` lands (around 1 year later).

We have plenty idea of this area but do not have enough effort to push thing forward.
I hope community can put their effort together with us and improve this area.

1. Unify of using object Generic

We add a lot of Generic in the typings system, it is easy to use without modify the Generic.
However, when we override one of them. It will collide with the others types.
Unify of using object Generic can prevent this problem.

#3642 is the first attempt of refactoring.

2. Promote chaining `fastify` types 

This approach is similar to `Express` and `Koa` which is optimal solution for stacking up decorated instance.
https://github.com/fastify/fastify-type-provider-typebox/issues/5#issuecomment-1159456144

**Comment by zrosenbauer** [comment] 2022-09-23 16:47
@climba03003 I saw this yesterday on Mongoose repo (everything is in JS) -> https://github.com/SamVerschueren/tsd

Might be good idea to help us prevent regressions in the future of types etc. (no idea if its came up before)

**Comment by Uzlopak** [comment] 2022-09-23 17:26
@zrosenbauer 
https://github.com/fastify/fastify/blob/2c97c4c7ad084c228026575eda3a14abbf2876eb/package.json#L167

**Comment by mcollina** [comment] 2022-09-26 08:27
@climba03003 something that might be worth looking is supporting TypeScript `nodenext` module resulution.

**Comment by Uzlopak** [comment] 2022-11-22 13:37
Is there even a solution for mutating objects without reassigning them?

Currently our typings get extended by requiring the corresponding package. When we mutate the fastify-instance by registering a plugin, i dont know a way to keep the mutated instance in sync with typescript

E.g.
```typescript
const fastify = Fastify({})

fastify.register(somePlugin) // the return value of fastify.register could return a mutated version of the fastifyInstance but we still have the old type in typescript 
```

vs. 
```typescript
let fastify = Fastify({})

fastify = fastify.register(somePlugin) // the return value of fastify.register could return a mutated version of the fastifyInstance and because we assign it to the fastify variable we keep the mutated type
```

Again:
Is it possible to mutate an object without reassigning it?

**Comment by mcollina** [comment] 2022-11-22 13:39
> Is it possible to mutate an object without reassigning it?

I don't think this would work across encapsulation boundaries.

**Comment by L2jLiga** [comment] 2022-11-22 22:37
> Again:
Is it possible to mutate an object without reassigning it?

Yes, but does not worst a cost =)

[Example on TS Playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwDYEMDOa4EE4G8BQccA5gJYBuwAssAHLADuAClBGMLAJ4A8AKnKBjAAdgBNMWADRwWbASCFjMaGFFLDicALxwA5LoB8AChgALUmgBccXtLCsw12WACU19Gg4xMZi3D-8AGQypAgA1twASsAI0KLcKmoa0gBGEBBIwCjCBtLOBniERHAA9ABUcGgQALbAcEgQZAhwphx1ZSVFAL74PfixwipwKNY4OsKM2EYuANz4+CgAdGSUNPTMDl6cRrphwJy6s-MLi3ucc0uiAGbic0A)

**Comment by Uzlopak** [comment] 2022-11-22 22:45
Looks not thaaat complicated.

**Comment by L2jLiga** [comment] 2022-11-22 22:58
Well yes, but no 😅 

It does not mutate original class but mutates type of `a`, as well it doesn't work if type of `a` is not set explicitly

Within one file I think everything is totally fine, but how I can tell other files about actual type of `a`?

**Comment by L2jLiga** [comment] 2022-11-22 23:08
Ok, I have an answer: 

<details>
<summary>Example</summary>

*app.ts*:
```typescript
import { doSomeJobWithApp } from './job.js';

export interface FastifyInstance {
  decorate<T extends FastifyInstance, Prop extends string, Decorator>(
    this: T,
    property: Prop,
    decorator: Decorator,
  ): asserts this is T & Record<Prop, Decorator>;
}

const app: FastifyInstance = {} as FastifyInstance;

app.decorate('test', () => true);

export type MyApp = typeof app;

doSomeJobWithApp(app);
```


*job.ts*:
```typescript
import type { MyApp } from './my-app.js';

export function doSomeJobWithApp(app: MyApp): boolean {
  return app.test();
}
```
</details>

**Comment by L2jLiga** [comment] 2022-11-24 20:23
btw it's also possible to build generic type on the fly, order does not make sense, [TS playground example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgSQHYGMImKg5gWQFMBnYgQ10IBo4B5AVxlwhwJPMrgF84AzKLHADkACxgwwQgNwAoGQHp5cAOKFUhKMHRwcMDbzLpCM3fsOE4AJUIBHeiRir1m9AB5rdh3EIAPPagATYhQMLFYiUgpqK0IwABsAT28-NSC6RmZw9iiaACEIAKSAXjh6VABrVAgAd1QAPkQZODgoW3tiGAAuGM8O2WbW+ITu6yH+uAAjAuG4fMLZLjlFOABBUkIQCbiNOBgISfpgOIC4SmctGkMjMBhgsDJYYJw4MlQk6ACNGRgEsAsAMRwAQACg8YK5QVAyCBCHooMFfP40mVKjVUABtAC6NAAKhBAYEaAA5CAwADKhxgZC2FkRqWCKKqtSxcBKWIaJUh0NhGgRKUCwXROF4OwAqjQAHRS4U7awdTFNOAAfjgouSSOCeIJAUVzRV6PFcHRUolcpgkqlJPJlOp20xCuazW62sh4LNuPxQJoxstpIpwCpNJoosxdUV3XUADcNLJvr8LE4NFo1sQNjSoBD1fTShUmRjQ6y4C6wa4fRLgTQ0JhsHgIhxogwmCxa9lKNiQtWspFKA06QKdKgRVAeu0YAAJCDHL56kcOCdT4d9tLoqthFvd6KMtFYh2OlXF2DuNpzyefKDogCM7cbmXX9d7-LSMuHo0S87Pur3MSG752S8FN7NmwG40FuzL2p+jrKkWQKukeP6nhol7tq8CQPhqA5DrM0y-lAkFQdBcwJLhWb9uiqGgbm24QQRtHQR4o6Ji4R69OOiHngADO2r7Eex6JcXkOF8VxYZ0QREaENGeFiU6cBRtOdESVJ+FKQpsnydJcCqVAsbLP8ZToDAwAQKgcCfOgcQPGQRkmXA1QBiIBxHGepT1jIviQLAfAGTZplkAEASWBAjCEK4TFaKRaQMQ44VuBRLxvHUdQABQiK8ATbFA3TJa0rHdLFACUrINJGLABAV3SlcAASyB50DwLwPnGX5AVBSFrgrIWYGoHkXVUbUNAAMJ9aitQpWlgSZdluWjvlahJugKZpplpYrHkQ2hkVRQlWVFVwFVNXuT4nkNU1tn+YFwV6Kl6VTXAOXHh0IyPY483MfFqF1FtO3VUVCCKpgqDEJOhASnEEC4Ddk0aAVCxLEoOIOMQcimFABhGHAACij6EAEdZRJFwSrjWwH1o0AxkNUopQHE3QdJoeBwzIF1tXorhIB01n0MQ3RCBA5RCNwKUzV423k3AgPA9sYMQw9rESlMhQSpzMDc7DcDLHEAYaGQcRwAARPz+syFwBVyCzV2hdjSK4-jPZy6OxXi5LIMy5DIsdBKHswF7lPU3ERXLPTrAm2bzOtZb7NwCr3O8-zgtcDQ1upLbraEMLL1O-9zQu9L4Puy9CvTMrVKq8Q6ua9rUJ64b5TGznJlS6D+cOw4XuF1CVM04HSjB3gofmxH7XRR0sWuMngSpyB6RNl29Y0Bzpex8I8dCxnrFZwDjeuy33tF0rMfl1IGtKFrcK6wbRtb0DO+y3v99+93J-RzADO4KHQA)

**Comment by simoneb** [comment] 2023-01-12 11:07
As NearForm, we would be glad to help in this area. Because this is not a typical issue requiring troubleshooting and fixing, we could use additional details about how we can support this.

**Comment by Uzlopak** [comment] 2023-05-05 15:04
The issue is, that typescript is transpiling typescript to javascript. We benchmark and optimize for javascript. By rewriting it to typescript, we would need to ensure, that the produced javascript is what we would expect. This means, that we would write code, transpile, check the transpiled code and then maybe realize that the code is not good enough, and invest more time and write the code differently, until the produced javascript is what we expected in the first place.
It is a pain in the ass.

I assume, that we can improve the typing system, so that the encapsulation and decoration of Fastify, FastifyRequest and FastifyReply can be handled by typescript properly. But this would mean, that we maybe need to release a fastify major version and also modify all typings of the plugins etc. etc.

**Comment by lord007tn** [comment] 2023-05-05 20:10
> Can you share what are your main pain points?

adding typescript through `declare` Sometimes types are included but the compiler can't access them or are not valid. tbh, I don't know the exact problem I just make `@ts-ignore`.
E.g: when I add the i18next-http-middleware plugin and call the request.t that they provide It works well in hooks but I had to ignore the ts or else a type error will occur.
I think the problem is in the `FastifyRequest` declaration as when I use it with `FastifyPluginAsync`
there are other plugins also that cause this problem

> What problems do you see with bundling?

things were good with commonjs until I had to use modules in my project for compatibility with other stuff 
and my Fastify can't run and I had to add `*.js` extension at the end of the import so they can be seen and imported.
when I tried to add Babel and webpack ( tried it with SWC ) autoload can't load the plugins cz everything is in one bundle.js
I manage to get around these problems after days of searching and solving them.
but I think newcomers, when they want to try Fastify with ESM, will face these problems and we should maybe update docs or if it's related to the actual Fastify framework

@Uzlopak seems logical, I support having a new way of typing in the next major, and giving proper docs for newcomers to grow the community and have the excellency of Fastify above the NodeJs community :D

**Comment by mcollina** [comment] 2023-05-05 21:01
@climba03003 would you issue the PR for the changes at the top of the file? They are great ideas.

**Comment by mcollina** [comment] 2023-05-05 21:07
> things were good with commonjs until I had to use modules in my project for compatibility with other stuff
and my Fastify can't run and I had to add *.js extension at the end of the import so they can be seen and imported.

I'm not sure how rewriting Fastify to TS would help with this, and I'm unsure why you are putting the blame for this to Fastify.
This is how ESM was designed to work by the Node.js team (and the reason why are really outside of the scope of this issue).

> when I tried to add Babel and webpack ( tried it with SWC ) autoload can't load the plugins cz everything is in one bundle.js

I don't understand how rewriting Fastify in TS would help with this. It seems a valid feature request "support bundling with autoload".

> I manage to get around these problems after days of searching and solving them.
but I think newcomers, when they want to try Fastify with ESM, will face these problems and we should maybe update docs or if it's related to the actual Fastify framework

I agree! But none of this are really related to Fastify. The problems you are listing are related to ESM. Would you like to send a PR? A few FAQ/guides to
help with those issue would be amazing.

**Comment by webstrand** [comment] 2023-07-18 02:10
I don't recommend using `asserts` to mutate the type of the fastify object after construction. It tends to be rather fragile in my experience, requires that users annotate the variable containing the fastify object, and doesn't tend to propagate over module boundaries. For an example of the last issue, check out [this playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEkoGdnwGIHtPwN4Ch55QBbTAQVRBgBcAeAFQD4AKANyggFcQAueBgEp+KZNRpoaACwCWaOfGkKAZHmIgy-BvAC+Abnw78+EAA8ADplqJMAO2Q14UflhwBeeLZAB3DNhaCBlAAdKQUVLQsAOQA1iAAnlGBJhZWjmB2DvAARvAeUHpAA) and take a look at the `.d.ts` tab on the right:
```ts
export declare const a: Foo;
export declare const b: Foo & {
    demo: string;
};
```
note that the first export, the one most users will logically pick, does not export the modified types correctly. None of these problems are insurmountable with enough documentation and tutorials, but I would not personally choose to build an API using `asserts` this way.

The alternative is using a builder API as [suggested by sinclair](https://github.com/fastify/fastify-type-provider-typebox/issues/5#issuecomment-1159456144). However, to make a builder API _safe_, you need to return a new object from every method call. Otherwise your users could end up calling builder methods and mutating the value without properly mutating the type.

Additionally, care should be taken when switching to such a builder API because the previous pattern of

```ts
const fastify = Fastify({})

fastify.register(somePlugin)
```

would be a no-op with a builder API, because the return value of `.register` is being ignored.

**Comment by Uzlopak** [comment] 2023-07-18 02:26
Thank you webstrand for your analysis of the subject. 

I know webstrand for a few years and he is a typescript expert. For the background: He is very active in the typescript community and gives alot of community support. I asked him to have a look at the issue and give us his opinion and his experience regarding the overall topic. Especially if he agrees with our findings or if he knows some other approach. Also it helps to get somebody outside our fastify bubble.

Based on all the comments and the analysis of webstrand I would finally assess that it is not desirable to implement it and recommend to not follow this approach further for fastify v5. Maybe when typescript supports someday a better way to implement typings for a builder api we can investigate it further. But I assume this will be not happening in the near future. So we should imho close this issue and mark it as "not planned".

Looking forward for your opinions.

**Comment by simoneb** [comment] 2024-06-07 08:35
Is this issue still relevant? It feels like the conclusion posted above suggests that there is nothing to do about this in the sort term.

**Comment by climba03003** [comment] 2024-06-07 08:38
> Is this issue still relevant?

It is continues works on improving the TypeScript types.
At least the pain of types is not solved until now.

**Comment by simoneb** [comment] 2024-06-07 08:41
> It is continues works on improving the TypeScript types. At least the pain of types is not solved until now.

Is it due to fastify's TS types or limitations in TS itself?

**Comment by climba03003** [comment] 2024-06-07 08:43
> Is it due to fastify's TS types or limitations in TS itself?

Currently due to the limitation of TS. But I do see something can be done in later release of TypeScript.
For example the decorator approach would helps a lot in file splitting.

**Comment by simoneb** [comment] 2024-06-07 08:52
Thanks for clarifying @climba03003

**Comment by mcollina** [comment] 2024-06-07 12:07
I think we can close this in favor of https://github.com/fastify/fastify/issues/5061, which is a bit more clear in scope.

**Closed by mcollina** 2024-06-07 12:07 UTC
Labels: help wanted, discussion, semver-major, semver-minor, feature request, typescript
