### ISSUE TITLE
Typebox union serialization omits properties after upgrading from fastify v3

### ISSUE THREAD

**Issue by MoLow** [fastify/fastify#4920] opened 2023-07-21 01:22 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.20.0

### Node.js version

18.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.4 (22F66)

### Description

I am using Fastify with TypeBox for schema validation.
my types include the usage of `Type.Union` wich seems to cause data to be omitted from the response

### Steps to Reproduce

this minimal repro provides different results on fastify v3 and fastify v4. repro also published to [this repo](https://github.com/MoLow/fastify-v4-migration-repro):

```ts
const app = fastify();

const DatumBase = Type.Object({ _id: Type.String() });
const Datum = Type.Intersect([DatumBase, Type.Union([
  Type.Object({ type: Type.Literal('A'), a: Type.String() }),
  Type.Object({ type: Type.Literal('B'), b: Type.String() }),
])]);

app.register(async (instance) => {
  instance.get('/', {
    schema: {
      response: {
        200: Type.Object({
          success: Type.Literal(true),
          data: Type.Array(Datum)
        }),
      },
    },
  },
  async (request, reply) => {
    return reply.status(200).send({ success: true, data: [{ _id: '1', type: 'A', a: 'a' }] })
  });
});

```

### Expected Behavior

in fastify v4, the response will be
```json
{"success":true,"data":[{"_id":"1"}]}
```
and in fastify v3 the response is
```json
{ "success": true, "data": [{ "_id": "1", "type": "A", "a": "a" }] }
```

I am wondering if this is expected and I am doing anything wrong, or if it is a bug. I am willing to do some contribution work to fastify if it is needed

**Comment by MoLow** [comment] 2023-07-21 01:25
if it helps - Typebox compiles that type into this json schema:
```js
{
  allOf: [
    {
      type: 'object',
      properties: { _id: { type: 'string', [Symbol(TypeBox.Kind)]: 'String' } },
      required: [ '_id' ],
      [Symbol(TypeBox.Kind)]: 'Object'
    },
    {
      anyOf: [
        {
          type: 'object',
          properties: {
            type: {
              const: 'A',
              type: 'string',
              [Symbol(TypeBox.Kind)]: 'Literal'
            },
            a: { type: 'string', [Symbol(TypeBox.Kind)]: 'String' }
          },
          required: [ 'type', 'a' ],
          [Symbol(TypeBox.Kind)]: 'Object'
        },
        {
          type: 'object',
          properties: {
            type: {
              const: 'B',
              type: 'string',
              [Symbol(TypeBox.Kind)]: 'Literal'
            },
            b: { type: 'string', [Symbol(TypeBox.Kind)]: 'String' }
          },
          required: [ 'type', 'b' ],
          [Symbol(TypeBox.Kind)]: 'Object'
        }
      ],
      [Symbol(TypeBox.Kind)]: 'Union'
    }
  ],
  [Symbol(TypeBox.Kind)]: 'Intersect'
}
```

**Comment by climba03003** [comment] 2023-07-21 02:22
Can you install `fastify@3` inside the same repo with the same schema used.
Since `typebox` is using unstable version `0.x.x`, it often ship breakage change between release. 
We need to ensure it is using the same version before try.

**Comment by climba03003** [comment] 2023-07-21 03:38
cc @ivan-tymoshenko 

Seem like the problem is the logic here. You are assuming when `anyOf` or `oneOf` exists. `type` must not be exist.
https://github.com/fastify/fast-json-stringify/blob/8d72614f4a621d30f47c970c6cb4fa86a3e697d5/index.js#L835-L849

However, when using with `allOf` and nested `anyOf` or `oneOf`, it will be merged with `type` exist.
https://github.com/fastify/fast-json-stringify/blob/8d72614f4a621d30f47c970c6cb4fa86a3e697d5/index.js#L356-L453

**Comment by ivan-tymoshenko** [comment] 2023-07-21 08:48
@climba03003 Yes, you are 100% right. It can be done, but this is a tricky one. If you have a parent schema and a few (oneOf or anyOf) nested schemas, you need to build serialization functions for each product of these schemas. Mainly because parent and child schemas might not be independent. 

Example:

```js
{
  id: "A",
  anyOf: [
    { id: "B" },
    { id: "C" }
  ]
}
```

You should merge those schemas into: AB and AC and compile a serialization function for each merged schema. The code would be like these.

**Comment by MoLow** [comment] 2023-07-21 09:28
> Can you install `fastify@3` inside the same repo with the same schema used. Since `typebox` is using unstable version `0.x.x`, it often ship breakage change between release. We need to ensure it is using the same version before try.

the repo contains two commits, one [with fastify v3](https://github.com/MoLow/fastify-v4-migration-repro/commit/b979237a8f6f22adc05fa24ba77cfa391c428763) and one with [fastify v4](https://github.com/MoLow/fastify-v4-migration-repro/commit/b979237a8f6f22adc05fa24ba77cfa391c428763), all other versions and packages are identical:


> As a `typebox` user, I recommend you to replace `Type.Intersect` with `Type.Composite` which eliminate the usage of `allOf`.
> 
> ```ts
> const DatumBase = Type.Object({ _id: Type.String() });
> const Datum = Type.Union([
>   Type.Composite([DatumBase, Type.Object({ type: Type.Literal('A'), a: Type.String() })]),
>   Type.Composite([DatumBase, Type.Object({ type: Type.Literal('B'), b: Type.String() })]),
> ]);
> ```

that might help, but I am working on migrating a repo with hundreds of schemas, changing all of them is not feasible

**Comment by MoLow** [comment] 2023-07-21 09:34
> As a typebox user, I recommend you to replace Type.Intersect with Type.Composite which eliminate the usage of allOf.

also - composite does not support `Type.Union` as a child:

```ts
const DatumBase = Type.Object({ _id: Type.String() });
const Datum = Type.Composite([DatumBase, Type.Union([
  Type.Object({ type: Type.Literal('A'), a: Type.String() }),
  Type.Object({ type: Type.Literal('B'), b: Type.String() }),
])]);
```

type script is not happy with this:
```
Type 'TUnion<[TObject<{ type: TLiteral<"A">; a: TString; }>, TObject<{ type: TLiteral<"B">; b: TString; }>]>' is missing the following properties from type 'TObject<TProperties>': type, propertiests(2739)
```

and with type checking off it compiles to (missing `a` and `b`):
```js
{
  type: 'object',
  properties: {
    _id: {
      allOf: [
        { type: 'string', [Symbol(TypeBox.Kind)]: 'String' },
        {
          anyOf: [
            { not: {}, [Symbol(TypeBox.Kind)]: 'Never' },
            { not: {}, [Symbol(TypeBox.Kind)]: 'Never' }
          ],
          [Symbol(TypeBox.Kind)]: 'Union'
        }
      ],
      [Symbol(TypeBox.Kind)]: 'Intersect'
    },
    type: {
      anyOf: [
        {
          const: 'A',
          type: 'string',
          [Symbol(TypeBox.Kind)]: 'Literal'
        },
        {
          const: 'B',
          type: 'string',
          [Symbol(TypeBox.Kind)]: 'Literal'
        }
      ],
      [Symbol(TypeBox.Kind)]: 'Union'
    }
  },
  required: [ '_id', 'type' ],
  [Symbol(TypeBox.Kind)]: 'Object'
}
```

**Closed** 2023-08-01 13:33 UTC
