### ISSUE TITLE
Accept-Version is always undefined

### ISSUE THREAD

**Issue by BlackGlory** [fastify/fastify#3625] opened 2022-01-16 16:00 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.3

### Node.js version

16.13.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04.3 LTS

### Description

I don't want to use [constraints](https://www.fastify.io/docs/latest/Reference/Routes/#constraints).

### Steps to Reproduce

```js
const fastify = require('fastify')
const server = fastify()
server.addHook('onRequest', async (req, reply) => {
  console.log(req.headers)
})
server.listen(8080)
```

```sh
curl \
  --header 'Accept-Version: 1.0' \
  http://localhost:8080
```

```
{
  host: 'localhost:8080',
  'user-agent': 'curl/7.68.0',
  accept: '*/*',
  'accept-version': undefined
}
```

### Expected Behavior

```
{
  host: 'localhost:8080',
  'user-agent': 'curl/7.68.0',
  accept: '*/*',
  'accept-version': '1.0'
}
```

**Comment by climba03003** [comment] 2022-01-16 16:13
I cannot reproduce your problem. It is probably something is wrong on your end or you do not provide the correct repro.
Here is what I use to test.
```js
const Fastify = require("fastify");
const fastify = Fastify();
fastify.addHook("onRequest", async (req, reply) => {
  console.log(req.headers);
});
fastify.get("/", async function (request) {
  return request.headers;
});
fastify.listen(8080);
```

![image](https://user-images.githubusercontent.com/23028015/149667998-b935779a-ad27-41a4-a62c-7641a2a13247.png)

**Comment by BlackGlory** [comment] 2022-01-16 16:32
What? You changed my example and said it can't be reproduced? If you can't get the `Accept-Version` without adding `.get(...)`, then it's already a problem.

**Comment by climba03003** [comment] 2022-01-16 16:52
Your word can be more polite. And as I am changed the repro, that's why I also posted inside the comment.
It is true that without a actual route added, it will be `undefined`.

**Comment by BlackGlory** [comment] 2022-01-16 16:55
If I give an example, you should reproduce that example, isn't it?

**Comment by mcollina** [comment] 2022-01-16 17:00
Would you like to send a PR to fix this? Thanks!

**Comment by climba03003** [comment] 2022-01-16 17:19
@mcollina I think it is an intended behavior?

https://github.com/fastify/fastify/blob/ae3320de7fd9ba2e6d68349c89f28de643b49f16/fastify.js#L577-L582

**Comment by mcollina** [comment] 2022-01-16 17:34
I do not have a clue. After the above (rude) messages from the OP, I'm not willing to engage in this issue, nor I think it's worth our time. I'm willing to see a PR that makes this behave like the OP want and then make a call. I do not think that's likely to come from them and I'm ok for the stalebot to close this without further discussion.

**Comment by BlackGlory** [comment] 2022-01-16 17:36
No problem, would love to see this issue exist in v4.

**Closed** 2022-01-17 08:23 UTC
