### ISSUE TITLE
Custom bodyLimit is not taken into account, so fallback on default limit of 1MiB

### ISSUE THREAD

**Issue by DamienDeSousa** [fastify/fastify#5533] opened 2024-06-26 14:21 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.21.0

### Node.js version

18.19.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.4

### Description

I get the following error from Fastify : **FastifyError [FST_ERR_CTP_BODY_TOO_LARGE]: Request body is too large**.  
In the documentation, it says that I have to increase le the bodyLimit to avoid the error.

So I did this:
```
import Fastify from 'fastify'

const app = Fastify({
  logger: true,
  bodyLimit: 10485760, // 10MiB
})
```

When I send a 1.7 MiB file, I still have the issue.
I've tested with a 129KiB file, and in this case everything works fine.

So I guess, the custom limit is ignored and the default one is effective (1MiB).

### Expected Behavior

Expected behaviour : able to send a payload with a a custom limit set on the server.
Current behaviour : unable to send a payload because the custom limit is ignored.

**Comment by metcoder95** [comment] 2024-06-30 09:03
Can you provide an 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) to support you better?

Tried with the following sample and couldn't reproduce it:

```js
const fastify  = require('fastify')({ logger: true, bodyLimit: 5 * 1024 })

const payload = Buffer.allocUnsafe(5 * 1024).fill('a');

fastify.post('/upload', async (req, reply) => ({ length: req.headers['content-length'] }));

fastify.inject({
  method: 'POST',
  url: '/upload',
  headers: { 'content-type': 'text/plain' },
  payload,
}).then(response => {
  console.log(response.statusCode); // 413
  console.log(response.body); // {"statusCode":413,"error":"Payload Too Large","message":"Payload Too Large"}
}).catch(console.error);```

**Comment by DamienDeSousa** [comment] 2024-07-01 10:06
Hello !
Thank you for answering !

Yes of course, here is my code **api/serverless.ts** :

```typescript
'use strict'

// Read the .env file.
import * as dotenv from 'dotenv'
dotenv.config()

// Require the framework
import Fastify, { FastifyReply, FastifyRequest } from 'fastify'

// Instantiate Fastify with some config
const app = Fastify({
  logger: true,
  bodyLimit: 10485760,
})

// Register your application as a normal plugin.
app.register(import('../src/app'))

export const maxDuration = 300

export default async (req: FastifyRequest, res: FastifyReply) => {
  await app.ready()
  app.server.emit('request', req, res)
}
`
``

Maybe it is related, I host my project on Vercel.

**Comment by jsumners** [comment] 2024-07-01 10:48
Please read the link that @metcoder95 provided.

**Comment by climba03003** [comment] 2024-07-04 06:13
The author said the `bodyLimit` is not taken into account, so you should try the payload bytes fall between the default limit and specified limit.

The below example shows the `bodyLimit` work as expected and reply with `200`
```js
import Fastify from 'fastify';

const fastify = Fastify({ logger: true, bodyLimit: 5 * 1024 })
const payload = Buffer.allocUnsafe(4 * 1024).fill('a');

fastify.post('/upload', async (req, reply) => ({ length: req.headers['content-length'] }));

const response = await fastify.inject({
  method: 'POST',
  url: '/upload',
  headers: { 'content-type': 'text/plain' },
  payload,
})
console.log(response.statusCode); // 200
console.log(response.body); // {"length":"4096"}
```

**Comment by DamienDeSousa** [comment] 2024-07-11 09:12
Thank you @climba03003 !  
So I guess it is because I host my project on vercel. I should set the bodyLimit in another way.  
I don't use `@fastify/multipart` or other plugin.

Do you have an idea or another way I can achieve this ?

**Comment by Uzlopak** [comment] 2024-07-11 09:22
Isnt vercel already body parsing? So if you upload a gzip, then it is already un-gzipped and bigger than you expect?

**Comment by DamienDeSousa** [comment] 2024-07-23 09:38
Hello !

I've finally found the solution but I don't really understand why it works.

I've set the bodyLimit on the route level instead of the Global config.  
Currently, I don't understand why it doesn't work on global config.

Here is my api/serverless.ts:
```typescript
'use strict'

// Read the .env file.
import * as dotenv from 'dotenv'
dotenv.config()

// Require the framework
import Fastify, { FastifyReply, FastifyRequest } from 'fastify'

// Instantiate Fastify with some config
const app = Fastify({
  logger: true,
  bodyLimit: 10485760, // Limite définie à 10 Mo (contrairement à 1 Mo par défaut)
})

// Register your application as a normal plugin.
app.register(import('../src/app'))

export const maxDuration = 300

export default async (req: FastifyRequest, res: FastifyReply) => {
  await app.ready()
  app.server.emit('request', req, res)
}
```


and here is my src/app.ts:
```typescript
import { join } from 'path'
import AutoLoad, { AutoloadPluginOptions } from '@fastify/autoload'
import { FastifyPluginAsync } from 'fastify'
import mongoose from 'mongoose'
import { handleErrorProperly } from './commons/helpers/errorHandler.helpers'

export type AppOptions = {
  // Place your custom options for app below here.
} & Partial<AutoloadPluginOptions>

// Pass --options via CLI arguments in command to enable these options.
const options: AppOptions = {}

const app: FastifyPluginAsync<AppOptions> = async (fastify, opts): Promise<void> => {
  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'plugins'),
    options: opts,
  })

  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'routes'),
    options: opts,
  })

  fastify.setErrorHandler((error, request, reply) => {
    handleErrorProperly(error, request, reply)
  })

  if (process.env.NODE_ENV !== 'test') {
    await mongoose
      .connect(process.env.DATABASE_URI!)
      .then(() => console.log('Mongoose connection opened !'))
      .catch((error) => console.log(error))

    fastify.addHook('onClose', async (instance, done) => {
      await mongoose.connection
        .close()
        .then(() => console.log('Mongoose connection closed'))
        .then(() => done())
        .catch((error) => console.log(error))
    })
  }
}

export default app
export { app, options }
```

I guess the way that I register my app has an impact on the bodyLimit but I didn't find the answer.
Do you guys are able to explain me the behaviour ?

Thank you for your time !

**Comment by metcoder95** [comment] 2024-08-14 06:43
I cannot see where are you setting the body limit here, but I'm guessing something is missed around those lines

**Comment by climba03003** [comment] 2024-08-16 02:40
Since there is no further information provided or no indication the option is not working.
I am going to close the issue.

If you think the issue the still exist, please provide a minimal reproducible example that can run directly.

**Closed by climba03003** 2024-08-16 02:40 UTC
Labels: need info

**Comment by RoelLeal** [comment] 2025-03-14 21:35
> Hello !
> 
> I've finally found the solution but I don't really understand why it works.
> 
> I've set the bodyLimit on the route level instead of the Global config. Currently, I don't understand why it doesn't work on global config.
> 
> Here is my api/serverless.ts:
> 
> 'use strict'
> 
> // Read the .env file.
> import * as dotenv from 'dotenv'
> dotenv.config()
> 
> // Require the framework
> import Fastify, { FastifyReply, FastifyRequest } from 'fastify'
> 
> // Instantiate Fastify with some config
> const app = Fastify({
>   logger: true,
>   bodyLimit: 10485760, // Limit defined at 10 MB at global level
> })
> 
> // Register your application as a normal plugin.
> app.register(import('../src/app'))
> 
> export const maxDuration = 300
> 
> export default async (req: FastifyRequest, res: FastifyReply) => {
>   await app.ready()
>   app.server.emit('request', req, res)
> }
> and here is my src/app.ts:
> 
> import { join } from 'path'
> import AutoLoad, { AutoloadPluginOptions } from '@fastify/autoload'
> import { FastifyPluginAsync } from 'fastify'
> import mongoose from 'mongoose'
> import { handleErrorProperly } from './commons/helpers/errorHandler.helpers'
> 
> export type AppOptions = {
>   // Place your custom options for app below here.
> } & Partial<AutoloadPluginOptions>
> 
> // Pass --options via CLI arguments in command to enable these options.
> const options: AppOptions = {}
> 
> const app: FastifyPluginAsync<AppOptions> = async (fastify, opts): Promise<void> => {
>   void fastify.register(AutoLoad, {
>     dir: join(__dirname, 'plugins'),
>     options: opts,
>   })
> 
>   void fastify.register(AutoLoad, {
>     dir: join(__dirname, 'routes'),
>     options: opts,
>   })
> 
>   fastify.setErrorHandler((error, request, reply) => {
>     handleErrorProperly(error, request, reply)
>   })
> 
>   if (process.env.NODE_ENV !== 'test') {
>     await mongoose
>       .connect(process.env.DATABASE_URI!)
>       .then(() => console.log('Mongoose connection opened !'))
>       .catch((error) => console.log(error))
> 
>     fastify.addHook('onClose', async (instance, done) => {
>       await mongoose.connection
>         .close()
>         .then(() => console.log('Mongoose connection closed'))
>         .then(() => done())
>         .catch((error) => console.log(error))
>     })
>   }
> }
> 
> export default app
> export { app, options }
> I guess the way that I register my app has an impact on the bodyLimit but I didn't find the answer. Do you guys are able to explain me the behaviour ?
> 
> Thank you for your time !

Same error, for me that's was the solution ^^^^^^^^^^
