### ISSUE TITLE
Improving Start-Up Times

### ISSUE THREAD

**Issue by nahtnam** [fastify/fastify#1598] opened 2019-04-13 19:17 UTC
## 🚀 Feature Proposal

I decided to benchmark fastify and a few other frameworks to see which would be good for a framework I'm building. As expected, fastify blew everything else out of the water in all categories except startup time where it was 2-6x slower than other options. I think it's important that fastify tries to improve this.

## Motivation

The startup times don't really affect people in production, however it is related to developer happiness. From my testing, I found that fastify almost took 200ms to start up with a single route (this only gets worse with more routes) and so when you save the file and refresh the browser you get greeted with a "connection refused" message rather than the API since nodemon is still restarting the server.

Because of ^ I think it may annoy or drive developers away. There are two possible ways to fix this:

1. Actually improve the startup time, but this may be hard as there will probably be an upper limit to how much time we can shave off.
2. Push some of the computation onto the routes in development mode. What this means is the initial computation that is done can be moved to the routes. Developers won't really notice slower response times as long as the server boots up fast. In production these changes would have to be reversed so we can get maximum response times.

## Example

All of the servers I wrote (along with the results) can be found here: https://github.com/nahtnam/fastify-benchmarks

| Name                   | Packages | First Start Time | Avg Start Time | Avg Latency | Req/S |
|------------------------|----------|------------------|----------------|-------------|-------|
| Fastify                | 42       | 189ms            | 192-193ms      | 8.67ms      | 2.89k |
| Koa (without router)   | 41       | 58ms             | 60ms           | 11.42ms     | 2.20k |
| Koa (with router)      | 47       | 109ms            | 70ms           | 11.98ms     | 2.09k |
| Micro (without router) | 20       | 48ms             | 30ms           | 8.98ms      | 2.79k |
| Micro (with router)    | 25       | 32ms             | 33ms           | 9.78ms      | 2.56k |

One thing to note is you may want to ignore the "first start time" as it varies and isn't representative of the frameworks speed.

**Comment by jsumners** [comment] 2019-04-13 19:35
Wouldn’t it be better to measure time with `process.hrtime` instead of `Date.now`?

**Comment by mcollina** [comment] 2019-04-13 20:06
I measured with the unix time utility, coming to similar conclusions.

The vast majority of this cost is caused by Ajv initialization cost. We create a lot of Ajv instances in Fastify, and we can avoid most of them.

**Comment by dalisoft** [comment] 2019-04-13 20:15
My comments maybe useless, but spending bit more on startup rather than on request.
If can avoid most of them and frameworks performant as now, then ok or we should not.

Just my 2 cents :)

**Comment by nahtnam** [comment] 2019-04-13 21:14
@dalisoft I agree that fastify should focus on request speeds but I think also think developer happiness is important. If we could reduce the server startup speed while still keeping the request speeds the same, then I think it's worth it.

If needed I can redo the tests with process.hrtime!

**Comment by dalisoft** [comment] 2019-04-13 21:17
> If we could reduce the server startup speed while still keeping the request speeds the same, then I think it's worth it

Yes, i also think this, but when it costs reducing requests performance, then not worth

**Comment by mcollina** [comment] 2019-04-13 22:13
Reducing startup time is important in a wide range of scenarios, and I think we can track and remove places where there are inefficiencies and/or we are doing repeated work.

**Comment by nahtnam** [comment] 2019-04-14 19:48
To add onto that, one perfect use case where start-up speed matters is serverless. For example, platforms like Zeit's Now and Apex's Up boot up your server when they receive a request. So in reality, when it comes to serverless architectures, frameworks like micro and koa will return requests 2-6 times faster than fastify. Considering how popular serverless is becoming, I think it is important for this to be worked on as well.

**Comment by jsumners** [comment] 2019-04-14 20:32
Fastify does not target those environments.

**Comment by nahtnam** [comment] 2019-04-16 07:15
Can I ask why not? Fastify is impressively fast... Wouldn't it be great to support other paradigms when possible?

Regardless it's still useful for development speeds

**Comment by jsumners** [comment] 2019-04-16 13:59
Fastify is a framework that facilitates building a long running HTTP server. Apex Up looks compatible with this, but the others that are designed to communicate with a simple function are not.

**Comment by nahtnam** [comment] 2019-04-16 17:46
Apologies, that is what I meant. Zeit's now, Apex up, and Google cloud run, all let you run full fledged apps (unlike lambda) in a serverless style. I was saying that for these situations, boot up times also matter

**Comment by nahtnam** [comment] 2019-04-17 00:57
@mcollina I did some more testing

```js
const a = Date.now();
import * as fastify from 'fastify';
console.log(Date.now() - a);
```

Doing this takes 160ms. The rest of the program takes 50ish ms. So I think its the initial import of the library that takes up most of the time, not actually calling `fastify()`.

**Comment by mcollina** [comment] 2019-04-17 07:42
Most of that cost it is due to Ajv initiatilizing its validators. You might want to check master and update the dependencies as we just landed some improvements.

**Comment by mcollina** [comment] 2019-04-17 08:29
Actually, the cost of start up time is even deeper. Essentially the issue it is on how Ajv generates the resolves URIs with https://www.npmjs.com/package/uri-js in https://github.com/epoberezkin/ajv/blob/bc993deceada5cc152ba0fd3b2e300012b2330a0/lib/compile/resolve.js#L235 and https://github.com/epoberezkin/ajv/blob/bc993deceada5cc152ba0fd3b2e300012b2330a0/lib/compile/resolve.js#L207-L216.


[![](https://upload.clinicjs.org/public/32ba5f97d5b2236fb85f50edcdd7dca62ae165eb587c64b1df3d3db5142e8a76/88053.clinic-flame.png)](https://upload.clinicjs.org/public/32ba5f97d5b2236fb85f50edcdd7dca62ae165eb587c64b1df3d3db5142e8a76/88053.clinic-flame.html#selectedNode=568&zoomedNode=&exclude=83c0&merged=true)


This is a flamegraph of the startup time. Apparently, the bottleneck is normalizing IPv6 addresses (which we are not using) in https://github.com/garycourt/uri-js/blob/4f6f600fade03398c08adf2755c3a2ad66d31b3c/src/uri.ts#L175.

Note that that RegExp is:

```js
/^\[?((?:(?:(?:(?:[0-9A-Fa-f]{1,4})\:){6}(?:(?:(?:[0-9A-Fa-f]{1,4})\:(?:[0-9A-Fa-f]{1,4}))|(?:(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9]))))|(?:\:\:(?:(?:[0-9A-Fa-f]{1,4})\:){5}(?:(?:(?:[0-9A-Fa-f]{1,4})\:(?:[0-9A-Fa-f]{1,4}))|(?:(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9]))))|(?:(?:(?:[0-9A-Fa-f]{1,4}))?\:\:(?:(?:[0-9A-Fa-f]{1,4})\:){4}(?:(?:(?:[0-9A-Fa-f]{1,4})\:(?:[0-9A-Fa-f]{1,4}))|(?:(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9]))))|(?:(?:(?:(?:[0-9A-Fa-f]{1,4})\:){0,1}(?:[0-9A-Fa-f]{1,4}))?\:\:(?:(?:[0-9A-Fa-f]{1,4})\:){3}(?:(?:(?:[0-9A-Fa-f]{1,4})\:(?:[0-9A-Fa-f]{1,4}))|(?:(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9]))))|(?:(?:(?:(?:[0-9A-Fa-f]{1,4})\:){0,2}(?:[0-9A-Fa-f]{1,4}))?\:\:(?:(?:[0-9A-Fa-f]{1,4})\:){2}(?:(?:(?:[0-9A-Fa-f]{1,4})\:(?:[0-9A-Fa-f]{1,4}))|(?:(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9]))))|(?:(?:(?:(?:[0-9A-Fa-f]{1,4})\:){0,3}(?:[0-9A-Fa-f]{1,4}))?\:\:(?:[0-9A-Fa-f]{1,4})\:(?:(?:(?:[0-9A-Fa-f]{1,4})\:(?:[0-9A-Fa-f]{1,4}))|(?:(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9]))))|(?:(?:(?:(?:[0-9A-Fa-f]{1,4})\:){0,4}(?:[0-9A-Fa-f]{1,4}))?\:\:(?:(?:(?:[0-9A-Fa-f]{1,4})\:(?:[0-9A-Fa-f]{1,4}))|(?:(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9])\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9][0-9])|(?:0?[1-9][0-9])|0?0?[0-9]))))|(?:(?:(?:(?:[0-9A-Fa-f]{1,4})\:){0,5}(?:[0-9A-Fa-f]{1,4}))?\:\:(?:[0-9A-Fa-f]{1,4}))|(?:(?:(?:(?:[0-9A-Fa-f]{1,4})\:){0,6}(?:[0-9A-Fa-f]{1,4}))?\:\:)))(?:(?:\%25|\%(?![0-9A-Fa-f]{2}))((?:(?:[A-Za-z0-9\-\.\_\~\xA0-\u200D\u2010-\u2029\u202F-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|(?:(?:%[EFef][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f])|(?:%[89A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f])|(?:%[0-9A-Fa-f][0-9A-Fa-f])))+)))?\]?$/
```

Optimizing/fixing this problem would likely give us another 10%.

**Comment by StarpTech** [comment] 2019-04-17 09:01
@mcollina awesome tool :smile: Is it posible to see the absolute time?

I see two solutions in order to get rid of it:

- Ajv use `uri-js` only in few [places](https://github.com/epoberezkin/ajv/blob/0fdb5052b1318c95ccfdd39b6e2e37f829f63a6c/lib/compile/resolve.js) we could try to replace it with a ligthweight solution but that could be quite hard.
- We use a server only ajv validation library

**Comment by mcollina** [comment] 2019-04-17 10:27
I think the next step is to open an issue on Ajv itself, and see what the author recommends. I will open one later on today.

**Comment by delvedor** [comment] 2019-07-25 10:38
Can we close this?

**Comment by mcollina** [comment] 2019-07-25 19:02
Yes and no, there is still work to do in dependencies.

Il giorno gio 25 lug 2019 alle 12:38 Tomas Della Vedova <
notifications@github.com> ha scritto:

**Comment by DrachovDmytro** [comment] 2019-09-26 13:33
Hey @mcollina 
I am going to try [bytenode](https://www.npmjs.com/package/bytenode) with fastify.
I'll share my results.

**Comment by StarpTech** [comment] 2019-09-29 11:34
@nahtnam what is the baseline? Which Node.js version? Did you use a SSD? Which processor? I would like to exclude that you use an unoptimized hardware setup.

@mcollina What's slow in your opinion? Bootstraping a framework and running a http server under 200ms seems pretty fast to me. Here some refefernces for hello world programms in other languages e.g [scala needs 800ms](https://github.com/chocolateboy/startup-time) to run hello world.

### My results:

**Baseline:** Start and listen for a http server took 8ms!
**Fastify simple example:** ~97ms
**Node.js:** 12.5.0
**CPU:** Ryzen 2600x 3.6GHz
**SSD:** yes

@DrachovDmytro I tested bytenode with that example and it was around ~5% slower than starting the app with node directly.

I tested with
```js
  const hrstart = process.hrtime()
  const hrend = process.hrtime(hrstart)
  console.info('Execution time (hr): %ds %dms', hrend[0], hrend[1] / 1000000)
```

**Comment by StarpTech** [comment] 2019-09-29 11:47
For a more realistic comparison hapi.js took around ~245ms to start based on my setup above.

**Comment by nahtnam** [comment] 2019-09-29 17:59
Unfortunately I dont remember the node version but it was one of the 8's I believe. Im running a 2015 MBPro with 16GB ram, SSD, and "2.2 GHz Intel Core i7"

**Comment by StarpTech** [comment] 2019-09-29 18:34
I think after @mcollina improvements the performance is very aligned with the others. @nahtnam could you retest it with Node 10 or higher?

(Node 10.16.3)
Koa (router): ~50ms
fastify: ~115ms

(Node 12.11.0)
Koa (router): ~45ms
fastify: ~86ms

**Comment by mcollina** [comment] 2019-09-30 07:32
We are slow compared to others. We might call it that we are “fast enough”, considering that our main bottleneck is regexp parsing and compiling.

If we are happy with the current performance on Node 12 we can close this.

**Comment by StarpTech** [comment] 2019-09-30 07:43
Which others? You really want to compare Koa or micro with fastify? I compared Hapi with fastify and it's 100% slower.

**Comment by mcollina** [comment] 2019-09-30 08:49
All things considered, I’m striving to have as low cost as possible for startup time as it make fastify more viable in serverless environments.

We could experiment with https://www.npmjs.com/package/v8-compile-cache and maybe use it in fastify-cli.

**Comment by DrachovDmytro** [comment] 2019-09-30 13:12
@StarpTech 

> @DrachovDmytro I tested bytenode with that example and it was around ~5% slower than starting the app with node directly.

Basically the reason of that you have not make a cache inside for fastify itself.
The reason of that it how require and node js [Module works](https://github.com/nodejs/node/blob/c42ab99/lib/internal/modules/cjs/loader.js#L854).


Regarding your question "What's slow in your opinion?" - basically as @mcollina mentioned it makes sense only for serverless environment. Therefore in scope of serverless I response time will be affected by load time of fastify.

**Comment by StarpTech** [comment] 2019-09-30 13:29
> Basically the reason of that you have not make a cache inside for fastify itself.

I was expecting that using `bytenode` would already make the difference because it skips the parsing and bytecode generation step. My idea is that "lazy-evaluation" is faster in that scenario.

> All things considered, I’m striving to have as low cost as possible for startup time as it make fastify more viable in serverless environments.

Is it worth the efforts? [We](https://github.com/fastify/fastify/issues/1598#issuecomment-483055861) didn't even know that we will support such use-cases.

**Comment by mcollina** [comment] 2019-09-30 13:44
> @mcollina Is it worth the efforts? We didn't even know that we will support such use-cases.

Likely no. But I would not mind being extremely fast booting as well tbh :).

**Comment by Eomm** [comment] 2019-10-01 07:11
Maybe we could think a utility to save the compiled schemas to use on startup instead of compiling it?
A sort of `--extreme-mode`?

**Comment by mcollina** [comment] 2019-10-01 07:35
We could potentially do this with fastify-cli.
However,It won’t help with the ipv6 regexp unfortunately. Moreover the tool for doing that compilation is not well maintained.

**Comment by delvedor** [comment] 2019-10-03 15:16
I agree that this kind of optimizations could live in `fastify-cli` especially something like https://www.npmjs.com/package/v8-compile-cache.

**Comment by Eomm** [comment] 2020-01-26 22:00
After #2023 we can work on this 💪

**Comment by mcollina** [comment] 2020-09-25 09:40
I don't think there is much more than we can do here as most of the time is spent in booting Ajv due to the massive ipv6 regexp :/.

**Closed by mcollina** 2020-09-25 09:40 UTC
Labels: discussion, enhancement, performances
