### ISSUE TITLE
Specifying .listen({ host: '0.0.0.0' }) should display all interfaces with .addresses().

### ISSUE THREAD

**Issue by yaneony** [fastify/fastify#5699] opened 2024-09-19 08:27 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

When specifying `fastify.listen({ host: '0.0.0.0' })` and then calling `fastify.addresses()` it only display `[ { address: '0.0.0.0', family: 'IPv4', port: 3000 } ]` when it would be much better to display all interfaces/IPs it listening on. It could be easily achieved by calling `os.networkInterfaces()` to get all available interfaces with their IPs.

**Comment by Uzlopak** [comment] 2024-09-19 08:34
what is the IPv6 equivalent of 0.0.0.0?

**Comment by yaneony** [comment] 2024-09-19 09:12
Afaik it would be `::`

**Comment by yaneony** [comment] 2024-09-19 09:21
Here is my small workaround to get all addresses. Working with `::` and `0.0.0.0`, depending on IPv family lists all IP addresses. When no host is specified, fall back to `localhost`, also `127.0.0.1` and `::1`

```
let addresses = app.addresses();
let families = addresses.map(({ family }) => family);

if (addresses.at(0).address === '0.0.0.0' || addresses.at(0).address === '::') {
  const port = addresses.at(0).port;
  addresses = Object.values(os.networkInterfaces())
    .flat()
    .filter(({ family }) => families.includes(family))
    .map(({ address, family }) => ({ address, family, port }));
}

console.log(addresses)
```

**Comment by yaneony** [comment] 2024-09-19 09:30
Here with sorting IP's:

```
let addresses = app.addresses();
if (addresses.at(0).address === '0.0.0.0' || addresses.at(0).address === '::') {
  addresses = Object.values(os.networkInterfaces())
    .flat()
    .filter(({ family }) => addresses.map(({ family }) => family).includes(family))
    .map(({ address, family }) => ({ address, family, port: addresses.at(0).port }))
    .sort((a, b) => a.address.localeCompare(b.address));
}
```

**Comment by jsumners** [comment] 2024-09-19 11:09
Closing as working as intended. As documented, `0.0.0.0` is IPv4 only. Use `::` if you want to listen on all interfaces regardless of IP version.

**Closed by jsumners** 2024-09-19 11:09 UTC
