### ISSUE TITLE
[NESTJS BUG] Request context not working when using FastifyAdapter

### ISSUE THREAD

**Issue by mittche** [fastify/fastify#3555] opened 2021-12-20 14:12 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.0.0

### Plugin version

1.0.0

### Node.js version

14

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

https://github.com/iamolegga/nestjs-pino/issues/546
https://github.com/mikro-orm/mikro-orm/discussions/2531

### Steps to Reproduce

---

**Comment by jsumners** [comment] 2021-12-20 14:14
Closing due to lack of information and the title indicating this lies with a completely separate project. If you feel otherwise, please provide some actual detail in the report and, ideally, a minimal reproduction.

**Closed by jsumners** 2021-12-20 14:14 UTC
