### ISSUE TITLE
Schema validation with specific response code fails

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#693] opened 2018-01-21 10:25 UTC
According to this section https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#serialization we are able to define different schemas for different status codes.

```js
'use strict'

const fastify = require('../fastify')()

const schema = {
  schema: {
    response: {
      200: {
        type: 'object',
        properties: {
          hello: {
            type: 'integer'
          }
        }
      }
    }
  }
}

fastify
  .get('/', schema, function (req, reply) {
    reply
      .send({ hello: 'world' })
  })

fastify.listen(3000, err => {
  if (err) throw err
  console.log(`server listening on ${fastify.server.address().port}`)
})

```

Respond this with status code 200 but I expect 400 with an error payload.
```js
{"hello":null}
```

**Comment by mcollina** [comment] 2018-01-21 10:40
I'm a bit lost in your example, when are you returning a 404?

**Comment by StarpTech** [comment] 2018-01-21 10:45
My response schema expects an `integer` but no error is thrown or 404 is set.

**Comment by mcollina** [comment] 2018-01-21 10:49
So, this is confusing and possibly the behavior is not correct.
`fast-json-stringify` is trying to render an integer and it is failing.
It should _really_ be throwing, and you'd get a 500 or a process crash.

**Comment by StarpTech** [comment] 2018-01-21 11:05
It looks like that this behavior is already known
https://github.com/fastify/fastify/blob/master/test/output-validation.test.js#L59

**Comment by mcollina** [comment] 2018-01-21 11:17
yeah. I’m not really conviced it’s the right thing to do.

**Comment by StarpTech** [comment] 2018-01-21 11:41
As a user, I expect a `number` that my handler responds with a number when not an error should be thrown. Aren't you convinced? When you do this in input-validation you will get a `400` with an error payload.

**Comment by allevo** [comment] 2018-01-21 11:49
The issue is here https://github.com/fastify/fast-json-stringify/blob/60fc96faae51bea13570b946d1a43f7d8ef670b3/index.js#L147-L154

Your schema doesn't define `hello` nullable and returning `null` breaks the output.

**Comment by StarpTech** [comment] 2018-01-21 11:52
@allevo thanks for the pointer but an error should be thrown `null` can't represent an `integer`

**Comment by mcollina** [comment] 2018-01-21 12:02
I tend to agree, this should be a PR against fast-json-stringify.

**Comment by allevo** [comment] 2018-01-21 12:04
As I said, `null` breaks the interface. And this is an issue.

**Comment by mcollina** [comment] 2018-01-21 12:06
This is a bug indeed! Would any of you send a PR against fast-json-stringify?

**Comment by StarpTech** [comment] 2018-01-21 12:13
@allevo already familiar with this? I working on https://github.com/fastify/fastify/issues/694

**Comment by mcollina** [comment] 2018-02-01 09:05
In the end we opted to _not throw_ in fast-json-stringify because it would cause a significant throughput regression. However, the field is skipped (so at least it does not break the interface).

**Comment by delvedor** [comment] 2018-03-07 11:52
Can we close this?

**Closed** 2018-03-07 13:26 UTC
Labels: bug
