### ISSUE TITLE
No IntelliSense

### ISSUE THREAD

**Issue by Crypt0Graphic** [fastify/fastify#2829] opened 2021-02-02 01:34 UTC
Why intellisense does not show fastify objects? It only shows what is in that page. Is that a bug? Very annoying.

![Screen Shot 2021-02-02 at 04 30 43](https://user-images.githubusercontent.com/9743846/106539787-aad60680-650f-11eb-98ff-fecd3ce05509.png)

When i use default then it seems like work:

`const fp = require('fastify-plugin').default;`

![Screen Shot 2021-02-02 at 04 38 57](https://user-images.githubusercontent.com/9743846/106540227-947c7a80-6510-11eb-8949-75469b80457f.png)

But this not work in everywhere (eg routes folder) because there is no import there. 

![Screen Shot 2021-02-02 at 04 49 52](https://user-images.githubusercontent.com/9743846/106541013-2cc72f00-6512-11eb-92fd-0239fbe5f602.png)

Btw, I created project with fastify-cli. Using VS Code.

**Comment by mcollina** [comment] 2021-02-02 08:34
cc @fastify/typescript 

This seems a good reason to create a VSCode extension.

**Comment by mcollina** [comment] 2021-02-02 08:38
I'm sorry I might have been too brief. IntelliSense is provided via Typescript typings. The first problem is about `.default`: for some obscure reason, it only picks the typing up when you access it via `.default`, even if it should not be the case. This might be depending on some (default?) Typescript settings I always get confused about. There might be a bug.

The second problem is about the lack of typings if you define plugins as JavaScript function. I think this is a missing feature and we should look into ways to support it better there.

**Comment by simoneb** [comment] 2021-02-02 08:39
@Crypt0Graphic in your last example I believe it's currently not possible, at least unless we provide some hint to the IDE about what type the `fastify` variable might be. You have a plain function there and VS cannot possibly figure out that just because you name one of the parameters `fastify` then it is an instance of the fastify type.

**Comment by simoneb** [comment] 2021-02-02 08:40
The first issue instead is definitely something wrong with the types

**Comment by mcollina** [comment] 2021-02-02 16:17
I think we should use https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#adding-additional-language-features to add some code completion for editing fastify plugins.

**Comment by climba03003** [comment] 2021-02-02 16:19
The typings is provided by `typescript`, but there are a known limitation for `typescript`. `typescript` cannot mix the exportation of typing between `commonjs`, `amd` and `esm`.

`typescript` itself use `export default`, and it is normal to be typed only when you use `require('fastify-plugin').default` as it is by design.

**Comment by fox1t** [comment] 2021-02-02 16:21
This is due to the fact that we use "infamous triplet" and TS doesn't understand it in the CJS context. It understands it in the ESM and TS contexts though.

We should add this to our docs since many developers are starting to rely on IntelliSense in the CJS context.

@mcollina I agree that the lang server is the final solution for these issues and it provides the best DX.

**Comment by charsleysa** [comment] 2021-02-04 03:08
Correct me if I'm wrong, but isn't the code that @Crypt0Graphic posted JavaScript as opposed to TypeScript? If so, I wouldn't expect typings to work everywhere as it's not possible to determine the typings in many situations in JavaScript.

I think creating a VSCode extension is overkill. If you want typings, code with TypeScript.

**Comment by simoneb** [comment] 2021-02-04 07:36
I disagree. We're talking about intellisense/autocomplete. Typings provide that to the editor. Because it's not always possible to infer them, an extension to the IDE would help.

**Comment by mcollina** [comment] 2021-02-04 07:42
> I think creating a VSCode extension is overkill. If you want typings, code with TypeScript.

Developer experience is a priority of this project. As the vast majority of developers _could_ use a VSCode Language Server, I think it's not an impossible task. As an example, it's possible to use language servers with Vim.

**Comment by charsleysa** [comment] 2021-02-04 09:17
@mcollina an extension may improve developer experience but I wouldn't deem a VSCode extension to be a priority.

Code can already be annotated with types, even in JavaScript. So for @Crypt0Graphic's case, they would only need to add the following comment to their function as shown in the last image in order to have intellisense work:
```
/**
 * setup some routes
 * @param {import("fastify").FastifyInstance} fastify 
 * @param {*} opts 
 */
module.exports = async function (fastify, opts) {
    fastify.get('/look', () => 'at me');
}
```

**Comment by mcollina** [comment] 2021-02-04 09:25
Oooh, this is very nice! I didn't know that would work. Maybe we should update the docs?

**Comment by Crypt0Graphic** [comment] 2021-02-05 05:09
> @mcollina an extension may improve developer experience but I wouldn't deem a VSCode extension to be a priority.
> 
> Code can already be annotated with types, even in JavaScript. So for @Crypt0Graphic's case, they would only need to add the following comment to their function as shown in the last image in order to have intellisense work:
> 
> ```js
> /**
>  * setup some routes
>  * @param {import("fastify").FastifyInstance} fastify 
>  * @param {*} opts 
>  */
> module.exports = async function (fastify, opts) {
>     fastify.get('/look', () => 'at me');
> }
> ```

This works very well. Enough for me. Thank you very much.

Because of Fastify is written in plain Javascript, I don't want to force it to use Typescript. I prefer to use the framework defaults whenever possible because I can access more resources with this. This is also important while Fastify already has a small community. It needs more input on StackOverFlow. :)

**Comment by penx** [comment] 2021-02-09 09:13
A language server extension would need to know which files are deemed to be fastify plugins and then apply a type to the function argument of the export.

e.g. for a file containing:

> ```js
> /**
> module.exports = async function (fastify, opts) {
>     fastify.get('/look', () => 'at me');
> }
> ```

I'm not 100% how a vscode could determine to apply the types to these function arguments, particularly without having false positives elsewhere. Perhaps a [triple slash directive](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) could be used somehow, but even then it would only solve the issue for this specific use case and for users who can install the vscode extension.

On the other hand, the JSDoc approach could be applied to any library and any IDE and is only reliant on users being aware of this approach.

**Comment by mcollina** [comment] 2021-02-09 09:59
> A language server extension would need to know which files are deemed to be fastify plugins and then apply a type to the function argument of the export.

Exactly. I think detecting if the export function matches that signature would be a good first step.

**Comment by simoneb** [comment] 2021-02-09 11:06
I like this idea, what do you think of this plan:

- enhance the docs to document how to immediately enable autocompletion via jsdoc as described [above](https://github.com/fastify/fastify/issues/2829#issuecomment-773156664)
- start looking into a vs code language server extension which tries to detect if a module contains a fastify plugin and provide autocompletion. we need to figure out the heuristic to apply to do that detection. to start with, we could start by detecting the plugin signatures that Fastify supports (callback based, async, ...) then apply some restrictions to avoid too many false positives

**Comment by delvedor** [comment] 2021-02-12 08:10
Can we close this?

**Comment by simoneb** [comment] 2021-02-12 08:20
The second point of the last comment is planned to be worked on.

**Comment by voxpelli** [comment] 2021-02-14 18:40
> @mcollina an extension may improve developer experience but I wouldn't deem a VSCode extension to be a priority.
> 
> Code can already be annotated with types, even in JavaScript. So for @Crypt0Graphic's case, they would only need to add the following comment to their function as shown in the last image in order to have intellisense work:
> 
> ```js
> /**
>  * setup some routes
>  * @param {import("fastify").FastifyInstance} fastify 
>  * @param {*} opts 
>  */
> module.exports = async function (fastify, opts) {
>     fastify.get('/look', () => 'at me');
> }
> ```

The following would be a better approach. I write 100% strictly typed Fastify in my current JavaScript project and this is the one I use:

```javascript
/**  @type {import('fastify').FastifyPluginAsync<{ optionA: boolean, optionB: string }>} */
module.exports = async function (fastify, { optionA, optionB }) {
  fastify.get('/look', () => 'at me');
}
```

Benefits of it: One ensures that the syntax complies with the expected syntax of an async Fastify plugin both on the outside and on the inside.

If one also adds a `tsconfig.json` and either sets `checkJs: true` in it or adds a `// @ts-check` comment at the top of the js-file, then VS Code will also start verifying the type information and, depending on strictness level, complain when it can't resolve the types needed for intellisense, thus ensuring that one has correctly specified ones input and that one correctly delivers ones output.

Next level on top of that is to use those checks and that JSDoc data to generate the `.d.ts` files that are needed for publishing, thus getting a guarantee that what the `.d.ts` files describes are actually always in sync with ones code as it's actually produced from the validated JSDoc annotated code.

An example of this can be seen in eg: https://github.com/voxpelli/node-installed-check-core

A place to ask questions and get help: https://github.com/voxpelli/types-in-js/discussions

Official documentation on this: https://www.typescriptlang.org/docs/handbook/intro-to-js-ts.html

**Comment by penx** [comment] 2021-02-15 16:22
Regarding a VS Code extension:

As far as I can see, we can't use an extension to decorate a function with a particular type/signature, as VSCode passes all responsibility for autocompletion, 'Go To Declaration', 'Go To Implementation' etc. down to the TypeScript server. i.e. every time you hover over a function or trigger a list of completions, VSCode is calling the TypeScript server, and the TypeScript server parses the file and returns completions etc.

https://github.com/microsoft/vscode/blob/d99c218e9b2da6935d467a7566a3de49c406ce90/extensions/typescript-language-features/src/languageFeatures/completions.ts#L715

This includes completions provided by JSDoc:

https://github.com/microsoft/TypeScript/blob/master/src/services/codefixes/annotateWithTypeFromJSDoc.ts

We could potentially provide the same features, by writing an extension that is independent of the built in plugin and TypeScript server, 
e.g.

```ts
class FastifyProvider implements vscode.TypeDefinitionProvider, vscode.DefinitionProvider, vscode.ImplementationProvider, vscode.CompletionItemProvider {
...
}

const provider = new FastifyProvider();
vscode.languages.registerTypeDefinitionProvider('javascript', provider);
vscode.languages.registerDefinitionProvider('javascript', provider);
vscode.languages.registerImplementationProvider('javascript', provider);
vscode.languages.registerCompletionItemProvider('javascript', provider, '.');
```

However:

- I think this could be a fair bit of work
- I haven't yet identified all of the `vscode.languages.register*` calls we would need to provide feature parity with what the JSDoc annotation provides
- We'd need to convert the fastify `.d.ts` declaration in to something that can be parsed, and if we were to support multiple versions of `fastify`, this conversion may need to happen at runtime
- I am not convinced of the benefits of using an extension to do this over annotating with JSDoc

**Comment by simoneb** [comment] 2021-02-15 21:01
It may we worth having the example shown [here](https://github.com/fastify/fastify/issues/2829#issuecomment-778821727) in the docs too

**Comment by simoneb** [comment] 2021-02-16 21:53
@delvedor I think this can be closed. We investigated the VS code extension route but it's much effort for little benefit, the same benefit that can be achieved with JSDoc annotations.

**Closed** 2021-02-16 22:24 UTC
