### ISSUE TITLE
Recursive x-forwarded-for

### ISSUE THREAD

**Issue by lifeofguenter** [fastify/fastify#4867] opened 2023-07-01 23:53 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently it is not possible to get the real IP easily if behind multiple reverse proxies. This is common scenario however:

Cloudflare > Traefik > Container

Cloudfront > ALB > Container

**Comment by Eomm** [comment] 2023-07-02 06:26
> easily

What does it mean?

Did you know the trustProxy option? https://fastify.dev/docs/latest/Reference/Server/#trustproxy

**Comment by lifeofguenter** [comment] 2023-07-02 08:52
> > easily
> 
> What does it mean?
> 
> Did you know the trustProxy option? https://fastify.dev/docs/latest/Reference/Server/#trustproxy

Unfortunately it does not work recursively. X-for can contain a list of IPs.

**Comment by Uzlopak** [comment] 2023-07-02 09:00
It is correct that X-Forwarded-For contains a list of IPs. But you should access the determined IP by accessing request.ip

**Comment by metcoder95** [comment] 2023-07-02 18:04
>It is correct that X-Forwarded-For contains a list of IPs. But you should access the determined IP by accessing request.ip

And the array of IPs the request went through, using `request.ips`.

**Comment by lifeofguenter** [comment] 2023-07-03 08:41
So that is what is meant by "easily". Sure, I can build my own function to parse the "real IP", but it would be great if this feature existed built-in by fastify.

[trustproxy](https://fastify.dev/docs/latest/Reference/Server/#trustproxy) is already half-way there, but does not cater for the scenarios where more than one loadbalancer are in-front of your service.

**Comment by gurgunday** [comment] 2023-07-03 11:14
> [trustproxy](https://fastify.dev/docs/latest/Reference/Server/#trustproxy) is already half-way there, but does not cater for the scenarios where more than one loadbalancer are in-front of your service.

It literally does if you set `trustproxy` to a number/integer.

From https://fastify.dev/docs/latest/Reference/Server/#trustproxy:
> number: Trust the nth hop from the front-facing proxy server as the client.

**Comment by climba03003** [comment] 2023-07-07 04:38
I am closing this issue because the issue is about misunderstanding of how `trustproxy` works.

You can specify multiple trusted `IP / CIDR`, numbers of `hop` or even a `function` if needed.
It handles correctly for multiple proxy, it just requires a proper configuration.
Just a boolean `option` and helps you to determine the whole `trusted` proxy isn't realistic.

**Closed by climba03003** 2023-07-07 04:38 UTC
