### ISSUE TITLE
Before Handler Question

### ISSUE THREAD

**Issue by miguelAliaga** [fastify/fastify#536] opened 2017-12-11 17:54 UTC
Hi team, in the code above I am using a beforeHandler, but it never ends. In the handler I use a res.send('ok'). Can u help me ?
```js
let validateJwt =  (req, res, done) => {
  let Bearer = req.headers.authorization || req.headers.Authorization
  if (Bearer === undefined || Bearer === null) {
    done('Authorization is necesary')
  } else {
    decode(Bearer, process.env.SECRET, function (jwtError, token) {
      if (jwtError) {
        done(jwtError)
      } else {
        if (token) {
          done()
        } else {
          done('malformed token')
        }
      }
    })
  }
}
```
___
*edit by @delvedor: updated code formatting*

**Comment by delvedor** [comment] 2017-12-11 20:53
Can you paste the full example?
You should pass the error as `new Error` and not as plain string :)

**Comment by jsumners** [comment] 2017-12-21 14:32
ping: @miguelAliaga

**Comment by miguelAliaga** [comment] 2017-12-21 19:00
`'use strict'
const _Query = require('../../database')
const {promisify} = require('util')
const Query = promisify(_Query.query)
const jwt = require('jsonwebtoken')
const decode = promisify(jwt.decode)
module.exports = (Fastify, opts, next) => {
  Fastify.route({
    method: 'GET',
    url: '/:id',
    beforeHandler: (req, res, done) => {
      let Bearer = req.headers.authorization || req.headers.Authorization
      let header = Bearer.split(' ')[1]
      if (!Bearer) {
        done({message:'Authorization is necesary'})
      } else {
        decode(Bearer, process.env.SECRET, function (jwtError, token) {
          if (jwtError) {
            done(new Error({message: e.message}))
          } else {
            if (token) {
              done()
            } else {
              done('malformed token')
            }
          }
        })
      }
    },
    handler: async (req, res, done) => {
      try {
        // query with mysql
        require('./t')()
        _Query.query(`select * from employee where docNumber = ${req.params.id}`, (err, results, fields) => {
          if (err) {
            res.send(err)
          } else {
            res.send(results)
          }
        })
      } catch (e) {
        res.send(new Error(e))
      }
    }
  })
  next()
}`

**Comment by miguelAliaga** [comment] 2017-12-21 19:03
i am sending a request with a header:
```
"Authorization" : "Bearer qoepoqjwepo1j2po313121"
```

**Comment by jsumners** [comment] 2017-12-21 19:46
I recommend using `req.log.debug` liberally to see where your error is occurring. Other than fixing your error creations, they should be like `var anError = Error('ooop it failed')`, I don't see anything wrong.

**Comment by mcollina** [comment] 2017-12-22 09:41
The problem is in `const decode = promisify(jwt.decode)`.

You are using a function that returns a Promise, but you are passing in a callback. Just replace that with `decode = jwt.decode`. And fix your errors.

**Comment by jsumners** [comment] 2017-12-22 13:48
I believe your question has been answered so I am closing this issue. If you have further questions, feel free to re-open.

**Closed by jsumners** 2017-12-22 13:48 UTC
Labels: question
