### ISSUE TITLE
Serving static files

### ISSUE THREAD

**Issue by cedmax** [fastify/fastify#55] opened 2017-03-21 16:20 UTC
I haven't found any documentation about serving static files, then @mcollina put me on the right path suggesting to try a middleware for it. 

[Express serve-static](https://github.com/expressjs/serve-static) works like a charm to map a folder to `/`:

```js
fastify.use(serveStatic(`${__dirname}/public`))
```
```sh
> curl http://localhost:8888/index.html
<html>
  <head><title>public/index.html</title></head>
  <body>Hello world!</body>
</html>
```

but I couldn't find a way to map a path to the public folder. 
If I wanted to do the same on Express I would have something on the lines of
```js
app.use('/assets', serveStatic(`${__dirname}/dist`))
```

It would be a nice addition

**Comment by delvedor** [comment] 2017-03-22 08:58
Hi, currently we are working on the plugins and soon on the `Reply`/`Request` decorators, I think we can achieve what you need just with a `Reply` decorator :)

@mcollina any other idea?

Thanks for the interest!

**Comment by mcollina** [comment] 2017-03-22 09:04
Those are two things, one is a `Reply` decorator, and another one is to limit the middlewares or plugins to a certain prefix.

**Comment by delvedor** [comment] 2017-03-22 09:23
The plugins are already limited to a certain prefix if you are using the encapsulation, middlewares are not. Maybe we can think to add this feature to [`middie`](https://github.com/fastify/middie).

**Comment by delvedor** [comment] 2017-03-26 10:14
Done in https://github.com/fastify/middie/pull/2, with the next Fastify release we'll update the dependency here :)

**Comment by delvedor** [comment] 2017-03-29 08:40
Released in [v0.13.0](https://github.com/fastify/fastify/releases/tag/v0.13.0) :)

**Comment by eljefedelrodeodeljefe** [comment] 2017-09-18 11:49
Can you clarify in the docs specifically how to do stuff like `index.html` serving. I believe something was a breaking a change during 0.13. and now, since I cannot reproduce the old behaviour with the new version anymore. 

Adding a test would be helpful to avoid regressions.

**Comment by mcollina** [comment] 2017-09-18 12:56
what do you mean the "old behavior"? 

In 0.27.0 (and middie 2), we changed how `.use()`  works to better match how express works.
The old behavior was not necessarily correct. 

On a side note, every release has tagged release notes on github (https://github.com/fastify/fastify/releases/tag/v0.27.0)

**Comment by eljefedelrodeodeljefe** [comment] 2017-09-18 13:00
tbh, I don't know. I can't seem to run any of the patterns `serve-static` would give me as `express` examples. But I was able before. So I thought I'd make this a request for docs :flushed:

**Comment by mcollina** [comment] 2017-09-18 13:03
Can you open up a new issue with a code example? Sorry for the inconvenience. I've added some integration checks in https://github.com/fastify/middie/blob/master/test.js#L219-L238, we need to something similar for fastify too.

**Comment by Piezoid** [comment] 2017-09-20 14:06
Since 0.27.0, routing is done before running any middlewares. This might explain why middlewares can't answer queries on undeclared routes.

**Comment by mcollina** [comment] 2017-09-21 06:43
@eljefedelrodeodeljefe @Piezoid I found it. This will be solved by #266.

**Comment by allevo** [comment] 2017-09-21 08:02
Anyway there'a a plugin: https://github.com/fastify/fastify-static :smiley:

**Closed** 2017-09-25 12:53 UTC

**Comment by mujtabazaidi** [comment] 2017-09-26 13:23
It's Fixed! thanks.
