### ISSUE TITLE
plugin must be a function or a promise

### ISSUE THREAD

**Issue by CodingXD** [fastify/fastify#2991] opened 2021-04-10 09:27 UTC
## 🐛 Bug Report

Running the project in local development is causing the following error
```
Error: plugin must be a function or a promise
     at assertPlugin (C:\Users\Marsh\Desktop\SuiteJar\server\node_modules\avvio\boot.js:200:11)
     at Boot._addPlugin (C:\Users\Marsh\Desktop\SuiteJar\server\node_modules\avvio\boot.js:233:12)
     at Boot.use (C:\Users\Marsh\Desktop\SuiteJar\server\node_modules\avvio\boot.js:209:25)
     at Object.server.<computed> [as register] (C:\Users\Marsh\Desktop\SuiteJar\server\node_modules\avvio\boot.js:33:14)
     at runFastify (C:\Users\Marsh\Desktop\SuiteJar\server\node_modules\fastify-cli\start.js:141:17)
     at async main (C:\Users\Marsh\Desktop\SuiteJar\server\node_modules\fastify-cli\lib\watch\fork.js:40:13)
```
The project was created using `fastify-cli`.

## To Reproduce

Create project using `fastify-cli` with command `fastify generate --lang=ts news`
`npm i fastify-mongodb node-schedule firebase-admin`
Create 3 files in plugins folder - `mongo.ts`, `schedule.ts`, `firebase.ts`

```ts
// mongo.ts
import fp from "fastify-plugin";
import fastifyMongodb from "fastify-mongodb";

export default fp(async (fastify, opts) => {
  await fastify.register(fastifyMongodb, {
    url: process.env.MONGO_DRIVER_CORE,
    name: "core",
  });
  await fastify.register(fastifyMongodb, {
    url: process.env.MONGO_DRIVER_MARKETING,
    name: "marketing",
  });
});
```

```ts
// firebase.ts
import fp from "fastify-plugin";
import * as admin from "firebase-admin";

export default fp(async (fastify, opts) => {
  if (!admin.apps.length) {
    fastify.decorate(
      "firebase",
      admin.initializeApp({
        credential: admin.credential.cert(
          require("../../suitejar-22764-firebase-adminsdk-hab7d-457aa15134.json")
        ),
      })
    );
  }
});

declare module "fastify" {
  export interface FastifyInstance {
    firebase: typeof admin;
  }
}
```

```ts
// schedule.ts
import fp from "fastify-plugin";
import fetch from "node-fetch";
import { scheduleJob } from "node-schedule";
import { load } from "cheerio";
import requestPromise from "request-promise";
const { parseString } = require("xml2js");

export default fp(async (fastify, opts) => {
  fastify.ready(async (err) => {
    if (err) throw err;
    // Adds node-schedule, checks mongo db
  });
});

```
when I run `npm run dev`, I get the following error
```
Error: plugin must be a function or a promise
     at assertPlugin (C:\Users\Marsh\Desktop\SuiteJar\server\node_modules\avvio\boot.js:200:11)
     at Boot._addPlugin (C:\Users\Marsh\Desktop\SuiteJar\server\node_modules\avvio\boot.js:233:12)
     at Boot.use (C:\Users\Marsh\Desktop\SuiteJar\server\node_modules\avvio\boot.js:209:25)
     at Object.server.<computed> [as register] (C:\Users\Marsh\Desktop\SuiteJar\server\node_modules\avvio\boot.js:33:14)
     at runFastify (C:\Users\Marsh\Desktop\SuiteJar\server\node_modules\fastify-cli\start.js:141:17)
     at async main (C:\Users\Marsh\Desktop\SuiteJar\server\node_modules\fastify-cli\lib\watch\fork.js:40:13)
```

## Your Environment

- *node version*: 14.16.0
- *fastify version*: >=3.14.1
- *os*: Windows
- *any other relevant information*

**Comment by mcollina** [comment] 2021-04-10 09:48
cc @fastify/typescript can you take a look?

**Comment by mcollina** [comment] 2021-04-10 09:48
(we should probably move this to fastify-cli, there is likely something broken in the tsconfig).

**Comment by CodingXD** [comment] 2021-04-10 10:00
Here the `tsconfig`
```
{
    "extends": "fastify-tsconfig",
    "compilerOptions": {
        "outDir": "dist",
        "noImplicitAny": false,
        "esModuleInterop": true,
        "noUnusedLocals": false,
    },
    "include": [
        "src/**/*.ts"
    ]
}
```

**Comment by RafaelGSS** [comment] 2021-04-10 15:37
I've tested the routine:

- `fastify generate --lang=ts news`
- `cd news && npm i`
- `npm run dev`
- `curl localhost:3000`

And worked fine, it seems a bad plugin registration. Can you put everything in a repository easy to reproduce?

**Comment by CodingXD** [comment] 2021-04-11 12:13
Sure @RafaelGSS I have done it and reproduced the error. It's in this repo https://github.com/CodingXD/news.

**Comment by RafaelGSS** [comment] 2021-04-11 17:40
The repository is not easy to reproduce yet. Some plugins require a setup before. Can you remove all the dependencies?

**Comment by CodingXD** [comment] 2021-04-11 18:00
I have removed the dependencies, removed some unrelated code

**Comment by RafaelGSS** [comment] 2021-04-11 23:03
Your repository still is expecting a setup before the run (MongoDB instance). I removed the mongodb plugin (`src/plugins/mongo.ts`) and works fine. You might be missing some settings in plugin registration, take a deep look at each plugin.

**Comment by CodingXD** [comment] 2021-04-12 07:04
It was working for a whole month straight. All of a sudden this issue popped up

**Comment by zekth** [comment] 2021-08-08 17:54
Closing the issue has the cause seems to have been found.

**Closed by zekth** 2021-08-08 17:54 UTC
