### ISSUE TITLE
[bug] ReferenceError: $asNumber is not defined

### ISSUE THREAD

**Issue by nikitamarcius** [fastify/fastify#2382] opened 2020-07-07 21:04 UTC
Error occurs only when start building the script (not in dev). Using Webpack 4  + Babel 7.

```js
undefined:20
      var $asInteger = $asNumber
                       ^
ReferenceError: $asNumber is not defined
```

package.json

```json
{
  "name": "server",
  "version": "1.0.0",
  "description": "",
  "main": "src/main.js",
  "scripts": {
    "start": "nodemon --exec babel-node .",
    "build": "cross-env NODE_ENV=production webpack --progress"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "axios": "0.19.2",
    "cors": "2.8.5",
    "cron": "1.8.2",
    "fastify": "3.0.0",
    "moment": "2.27.0",
    "mongoose": "5.9.22",
    "timestring": "6.0.0"
  },
  "devDependencies": {
    "@babel/core": "7.9.6",
    "@babel/node": "7.8.7",
    "@babel/plugin-transform-runtime": "7.10.0",
    "@babel/runtime": "7.10.0",
    "babel-loader": "8.1.0",
    "cross-env": "6.0.3",
    "nodemon": "2.0.3",
    "webpack": "4.41.2",
    "webpack-cli": "3.3.10"
  }
}

```

webpack.config.js

```
const path = require('path')
const webpack = require('webpack')

process.env.NODE_ENV = 'production'

module.exports = {
	target: 'node',
	mode: 'production',
	entry: './src/main.js',
	output: {
		path: path.resolve(__dirname, './dist'),
		filename: '[name].js',
	},
	module: {
		rules: [
			{
				test: /\.m?js$/,
                                exclude: /(node_modules|bower_components)/,
                                use: {
                                   loader: 'babel-loader',
                                   options: {
                                        presets: ['@babel/preset-env']
                                   }
                                }
			}
		]
	},
	plugins: [
		new webpack.DefinePlugin({
			'process.env': {
				NODE_ENV: '"production"',
			},
		}),
		new webpack.LoaderOptionsPlugin({
			minimize: true,
		}),
	]
}
```

babel.config.json

```
{
  "presets": [
    "@babel/preset-env"
  ],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

main.js

```
// Require the framework and instantiate it
const fastify = require('fastify')({ logger: true })

// Declare a route
fastify.get('/', async (request, reply) => {
  return { hello: 'world' }
})

// Run the server!
const start = async () => {
  try {
    await fastify.listen(3000)
    fastify.log.info(`server listening on ${fastify.server.address().port}`)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()
``

**Comment by mcollina** [comment] 2020-07-07 22:15
I’m going to close this as “not a bug”. Unfortunately you have some issue with your transpiler and it’d be impossible to test all combinations of those (with their relative settings). Overall I think fast-json-stringify does not like to be bundled, but I don’t know why.

If you figure out and you would like to send a PR, go ahead :).

**Closed by mcollina** 2020-07-07 22:15 UTC
