### ISSUE TITLE
`@types/pino` should not be in `dependencies`

### ISSUE THREAD

**Issue by arniu** [fastify/fastify#1321] opened 2018-12-13 10:03 UTC
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## To Reproduce

Paste your code here:

```js

```

## Expected behavior

Paste the results here:

```js

```

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by mcollina** [comment] 2018-12-13 10:19
Can you please articulate why?

**Comment by corbinu** [comment] 2018-12-14 01:06
@mcollina I don't believe this is true. The fastify types reexport the pino.Logger so it should be a dependency as it is now.

**Comment by evanshortiss** [comment] 2018-12-14 05:00
+1 for @corbinu. This [SO post](https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies) explains it.

**Comment by arniu** [comment] 2018-12-19 00:56
As `abstract-logging` is used as the fallback logger, errors will occur when pino methods applied on the fallback logger. The fastify types should export exact, minimum interfaces.

**Comment by evanshortiss** [comment] 2018-12-19 15:35
@arniu, I see what you mean about `abstract-logging` can you provide an example of the issues this causes? 

I tested using TS and don't see any issue. `abstract-logging` is a noop, so it has no effect if you call it regardless of args. Tested it like so:

```ts
import * as fastify from 'fastify'

const server = fastify()

// Declare a route
server.get('/', (request, reply) => {
    server.log.warn('uh oh')
    reply.send({ hello: 'world' })
})

// Run the server!
server.listen(3000, (err, address) => {
    if (err) throw err
    server.log.info(`server listening on ${address}`)
})
```

**Comment by arniu** [comment] 2018-12-20 01:12
`abstract-logging` only has `fatal`, `error`, `warn`, `info`, `debug` and `trace`, which is only a subset of `pino.Logger`'s. According to the type definition, users may use exclusive methods:

```
server.register((instance, opts, next) => {
    // `pino.Logger` is an instance of `EventEmitter`.
    // Calling `addListener` on `abstract-logging` will break the code
    server.log. addListener('level-change', console.log)
})
```

**Comment by evanshortiss** [comment] 2018-12-20 04:53
@arniu I see what you mean now. This is actually a bigger issue beyond TypeScript.

@fastify/fastify, what are your thoughts on this? If logging is not enabled then `server.log` has a different set of methods. Should this be addressed?

If not we can potentially update the `fastify.d.ts` to provide correct typings if `options.logger` is "falsey"?

**Comment by jsumners** [comment] 2018-12-20 05:35
I really don’t understand what the problem is.

**Comment by nwoltman** [comment] 2018-12-20 05:58
If it's possible to provide the correct typings for the logger when it's not a pino instance, that would probably be the best approach.

**Comment by arniu** [comment] 2018-12-20 07:08
So, the fastify types should not reexport `pino.Logger`. As a result, `@types/pino` can be moved out of `dependencies `.

**Comment by delvedor** [comment] 2018-12-20 09:10
I understand the problem, but it will also happen in js if the logger is disabled.
This is not a TypeScript issue, but a wider one, that can be fixed in various ways, starting from a note in the documentation, to extending the API surface of `abstract-logger`.

I don't see this one as a critical issue since there is no point to interact with the logger so heavily (`log.addListener`) and then disable it, but if someone wants to send a fix I'm happy to review it.

**Comment by mcollina** [comment] 2018-12-20 09:16
I think we have two routes:

1. bundle a subset of the types of `@types/pino` in fastify. This has the added benefit of removing a dependency that we do not maintain, which is not bad.
2. make `abstract-logging` inherit from `EventEmitter`

In theory a user could pass in any logger that matches that abstract-logging interface, so 1 is definitely feasible.

**Comment by evanshortiss** [comment] 2018-12-20 17:47
> If it's possible to provide the correct typings for the logger when it's not a pino instance, that would probably be the best approach.

I was thinking of this, essentially extending how we detect http2 and https, but it's becomes incredibly messy:

```ts
declare function fastify(opts?: fastify.ServerOptionsAsHttp): fastify.FastifyInstance<pino.Logger, http.Server, http.IncomingMessage, http.ServerResponse>;
declare function fastify(opts?: fastify.ServerOptionsAsHttpWithPino): fastify.FastifyInstance<pino.Logger, http.Server, http.IncomingMessage, http.ServerResponse>;
declare function fastify(opts?: fastify.ServerOptionsAsSecureHttp): fastify.FastifyInstance<pino.Logger, https.Server, http.IncomingMessage, http.ServerResponse>;
declare function fastify(opts?: fastify.ServerOptionsAsSecureHttpWithPino): fastify.FastifyInstance<pino.Logger, https.Server, http.IncomingMessage, http.ServerResponse>;
declare function fastify(opts?: fastify.ServerOptionsAsHttp2): fastify.FastifyInstance<pino.Logger, http2.Http2Server, http2.Http2ServerRequest, http2.Http2ServerResponse>;
declare function fastify(opts?: fastify.ServerOptionsAsHttp2WithPino): fastify.FastifyInstance<pino.Logger, http2.Http2Server, http2.Http2ServerRequest, http2.Http2ServerResponse>;
declare function fastify(opts?: fastify.ServerOptionsAsSecureHttp2): fastify.FastifyInstance<pino.Logger, http2.Http2SecureServer, http2.Http2ServerRequest, http2.Http2ServerResponse>;
declare function fastify(opts?: fastify.ServerOptionsAsSecureHttp2WithPino): fastify.FastifyInstance<pino.Logger, http2.Http2SecureServer, http2.Http2ServerRequest, http2.Http2ServerResponse>;
```

That doesn't seem scalable either, but maybe there's a solution I'm not aware of.

@delvedor, I agree it doesn't make sense to interact so heavily. You can just use a global/environment variable to avoid the issue.

@mcollina, for #1 are you suggesting we just expose a simple interface with `trace`, `debug`, etc? It would not include `child`, `addEventListener`? That seems pretty reasonable, but could it lead to issues if someone wants to use the wider pino API?

**Comment by mcollina** [comment] 2018-12-20 19:32
child is part of abstract-logger I think, addEventListener is not.

Typescript users that might want to access the full pino type could always cast it, right?

**Comment by evanshortiss** [comment] 2018-12-21 01:07
@jsumners thanks for the confirmation.

`Typescript` users that might want to access the full pino type could always cast it, right?

@mcollina yep, not ideal, but works. I'd argue it's odd to expose a different set of methods in each scenario, so I lean towards your first proposed option of having `server.log` simply expose a subset of methods. If they need the full range then use a cast.

If we remove TypeScript from the equation what would people think is the correct solution?

**Comment by mcollina** [comment] 2018-12-21 11:43
> @mcollina yep, not ideal, but works. I'd argue it's odd to expose a different set of methods in each scenario, so I lean towards your first proposed option of having server.log simply expose a subset of methods. If they need the full range then use a cast.

I think we should go into that direction and drop the dependency. I like it. Should we include this in 2.0.0, or should we backport in 1.x as well? Seems a major change.

**Closed** 2019-01-10 11:30 UTC
Labels: bug, discussion
