### ISSUE TITLE
Pino. Request context not working when using FastifyAdapter - People are struggling 3 month because programmers have nothing to do

### ISSUE THREAD

**Issue by B5nan** [fastify/fastify#3568] opened 2021-12-22 07:17 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.0.0

### Node.js version

14

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

Request context not working when using FastifyAdapter
https://github.com/iamolegga/nestjs-pino/issues/546

### Steps to Reproduce

I'm using NestJS with Fastify. nestjs-pino works pretty well with HTTP GET requests and with other HTTP requests that doesn't have a body. When requests have a body, the logger does not brings context and only prints the basic log message, even when log is invoked inside the request context.

### Expected Behavior

When logging inside a request context, all log entries should have the correct context.

Correct log entry for request without body:
{"level":30,"time":1631560507217,"pid":448510,"hostname":"host","req":{"id":"req-1","method":"GET","url":"/","headers":{"content-type":"application/json","accept":"*/*","cache-control":"no-cache","host":"localhost:5000","accept-encoding":"gzip, deflate, br","connection":"keep-alive","content-length":"20"},"remoteAddress":"127.0.0.1","remotePort":35350},"context":"AppController","msg":"Hi from getHello"}
Incorrect log entry for request with body:
{"level":30,"time":1631560533607,"pid":448510,"hostname":"host","context":"AppController","msg":"Hi from postHello"}

https://github.com/itheodoro/nestjs-fastify-example/blob/main/src/app.controller.ts#L9

**Comment by climba03003** [comment] 2021-12-22 07:34
I don't know why you repeatedly sending the same issue.
I am glad to help if you can minimize the issue with `fastify` and `pino` only, otherwise it is too wide for debugging and I would consider it as the `nestjs` bug only.

**Comment by climba03003** [comment] 2021-12-22 07:36
And you are spamming the same issue in `fastify`, `nestjs` and `node`. It is not a good habit for seeking help.

**Comment by mcollina** [comment] 2021-12-22 07:53
@B5nan if you continue spamming the Fastify repositories you you'll be blocked.

I'm closing this as it is not a bug or problem with Fastify.

**Closed** 2021-12-22 07:53 UTC

**Comment by jmcdo29** [comment] 2021-12-22 07:55
The "issue" here is that when adding a middleware to a nest application, nest uses middie for nest-fastify applications to have a unified middleware interface, and to keep the middleware path based. However, as fastify passes the unwrapped request and response objects (as documented) to the middleware, when that is saved to an AsyncLocalStorage instance, it's actually fastify's req.raw. 

The solution is for library authors who use middleware to attach properties to the req to use req.raw to retrieve them later. 

This only effects nest-fastify projects, and does not have anything to do with fastify itself. Everything is documented as it should be.

**Comment by climba03003** [comment] 2021-12-22 08:03
Thanks for clarifying.
