### ISSUE TITLE
Incorrect request.params parsing with atypical routing

### ISSUE THREAD

**Issue by kjmph** [fastify/fastify#2261] opened 2020-05-06 04:08 UTC
## 🐛 Bug Report

In a very particular setup of fastify, the routing parameter is evaluated to the empty string. If this routing parameter is validated, this causes a 400 status code. This is fixable by turning off the `ignoreTrailingSlash` option.

## To Reproduce

In services/root.js:

```js
module.exports = function (fastify, opts, next) {
    fastify.get('/:key/self', {
        schema: {
            params: {
                key: {
                    type: 'string',
                    enum: ['goodkey']
                }
            }
        }
    }, function (request, reply) {
        reply.send({ root: true })
    })

    fastify.patch('/goodkey', function (request, reply) {
        reply.send({ root: true })
    })

    fastify.post('/goodkey/post', function (request, reply) {
        reply.send({ root: true })
    })

    next()
}
```

In app.js:

```js
module.exports.options = {
    ignoreTrailingSlash: true
}
```

Modify the fastify startup in package.json to include --options:

```json
{ "start": "fastify start -l info --options app.js" }
```

## Expected behavior

One expects the request.params.key to be evaluated to `goodkey`. Instead, it is evaluated to an empty string. Since the empty string is not a valid parameter for the route, a 400 status is returned to the caller.

## Your Environment

- *node version*: 12
- *fastify version*: >=2.0.0
- *os*: Linux
- Can reproduce with a clean install via `npm init fastify`

**Comment by Eomm** [comment] 2020-05-06 06:21
Did you try the `default` prop?

```
key: {
                    type: 'string',
                    default: 'goodkey',
                    enum: ['goodkey']
                }
```

**Comment by kjmph** [comment] 2020-05-06 12:36
That doesn't work, because the test request is a `GET` of `/goodkey/self`, `key` should be set to `goodkey`. Instead, it is set to the empty string. Thus, even if a default is used, the default is overridden by the empty string, which is still an error when it tests membership in the enum.

**Comment by Eomm** [comment] 2020-05-06 12:46
What is your fastify version? 2.0.0? or the last one?
What is your fastify configuration?

Did you try a minimal reproducible problem?

```
const fastify = require('fastify')({ logger: true })

fastify.get('/:key/self', {
  schema: {
    params: {
      key: {
        type: 'string',
        enum: ['goodkey']
      }
    }
  }
}, function (request, reply) {
  reply.send({ root: request.params })
})

fastify.patch('/goodkey', function (request, reply) {
  reply.send({ root: '/goodkey' })
})

fastify.post('/goodkey/post', function (request, reply) {
  reply.send({ root: '/goodkey/post' })
})

fastify.listen(3000)

// curl http://localhost:3000/goodkey/self
// will print:
// {"root":{"key":"goodkey"}}
```

**Comment by kjmph** [comment] 2020-05-06 13:56
As seen in the bug report, I used `npm init fastify` so it is version `2.0.0`. Let me modify your single file version so it fails. Also, note, that setting a default (even if that worked) isn't ideal, because the code this is lifted from is multiplexing on the route param, and there is no such default.

**Comment by kjmph** [comment] 2020-05-06 13:59
Actually, thanks for that minimal server, one line change to get the failure:

```js
const fastify = require('fastify')({ ignoreTrailingSlash: true, logger: true })

fastify.get('/:key/self', {
  schema: {
    params: {
      key: {
        type: 'string',
        enum: ['goodkey']
      }
    }
  }
}, function (request, reply) {
  reply.send({ root: request.params })
})

fastify.patch('/goodkey', function (request, reply) {
  reply.send({ root: '/goodkey' })
})

fastify.post('/goodkey/post', function (request, reply) {
  reply.send({ root: '/goodkey/post' })
})

fastify.listen(3000)

// curl http://localhost:3000/goodkey/self
// will print:
// {"statusCode":400,"error":"Bad Request","message":"params.key should be equal to one of the allowed values"}
```

**Comment by Eomm** [comment] 2020-05-06 15:04
What is the output of `npm ls find-my-way`?

This bug should be fixed in 2.2.2
Ref https://github.com/delvedor/find-my-way/pull/146

**Comment by kjmph** [comment] 2020-05-06 19:12
```bash
$ npm ls find-my-way
bug@1.0.0 /private/tmp/bug
└─┬ fastify@2.14.0
  └── find-my-way@2.2.2
```

**Comment by kjmph** [comment] 2020-05-06 19:15
I can see that commit in the version of the module installed.

**Comment by Eomm** [comment] 2020-05-06 20:45
I think we have a bug if you comment the patch or the post route, your example works.
Would you like to work on it?

`find-my-way` is ok because this test works, so it must be here in fastify

```
'use strict'

const t = require('tap')
const FindMyWay = require('../')

t.test('issue-???', (t) => {
  t.plan(8)

  const findMyWay = FindMyWay({ ignoreTrailingSlash: true })

  const varPath = function parameterPath () {}
  const fixedPath = function staticPath () {}
  const fixedPathPost = function staticPath () {}
  findMyWay.on('GET', '/:key/self', varPath)
  findMyWay.on('PATCH', '/goodkey', fixedPath)
  findMyWay.on('POST', '/goodkey/post', fixedPathPost)

  t.equals(findMyWay.find('PATCH', '/goodkey').handler, fixedPath)
  t.equals(findMyWay.find('POST', '/goodkey/post').handler, fixedPathPost)
  t.equals(findMyWay.find('GET', '/goodkey/self').handler, varPath)
  t.equals(findMyWay.find('PATCH', '/goodkey/').handler, fixedPath)
  t.equals(findMyWay.find('POST', '/goodkey/post/').handler, fixedPathPost)
  t.equals(findMyWay.find('GET', '/goodkey/self/').handler, varPath)

  t.notOk(findMyWay.find('GET', '/goodkey/c'))
  t.notOk(findMyWay.find('PATCH', '/goodkey/self'))
})

```

**Comment by kjmph** [comment] 2020-05-07 21:26
Hmm, maybe I can simulate the bug in find-my-way via this:

```javascript
'use strict'

const t = require('tap')
const FindMyWay = require('../')

t.test('issue-???', (t) => {
  t.plan(5)

  const findMyWay = FindMyWay({ })

  const varPath = function parameterPath () {}
  const fixedPath = function staticPath () {}
  const fixedPathS = function staticPathS () {}
  const fixedPathPost = function staticPathPost () {}
  findMyWay.on('GET', '/:key/self', varPath)
  findMyWay.on('PATCH', '/goodkey', fixedPath)
  findMyWay.on('PATCH', '/goodkey/something', fixedPathS)
  findMyWay.on('POST', '/goodkey/post', fixedPathPost)

  t.equals(findMyWay.find('PATCH', '/goodkey').handler, fixedPath)
  t.equals(findMyWay.find('POST', '/goodkey/post').handler, fixedPathPost)
  t.equals(findMyWay.find('GET', '/goodkey/self').handler, varPath)
  //t.equals(findMyWay.find('PATCH', '/goodkey/').handler, fixedPath)
  //t.equals(findMyWay.find('POST', '/goodkey/post/').handler, fixedPathPost)
  //t.equals(findMyWay.find('GET', '/goodkey/self/').handler, varPath)

  t.notOk(findMyWay.find('GET', '/goodkey/c'))
  t.notOk(findMyWay.find('PATCH', '/goodkey/self'))
})
```

Because there is a child off the `/goodkey` route?

**Comment by kjmph** [comment] 2020-05-07 21:43
Oh, and now that I understand find-my-way, I can construct a test for it to fail with `ignoreTrailingSlash`:

```javascript
'use strict'

const t = require('tap')
const FindMyWay = require('../')

t.test('issue-???', (t) => {
  t.plan(9)

  const findMyWay = FindMyWay({ ignoreTrailingSlash: true })

  const varPath = function parameterPath () {}
  const fixedPath = function staticPath () {}
  const fixedPathPost = function staticPath () {}
  findMyWay.on('GET', '/:key/self', varPath)
  findMyWay.on('PATCH', '/goodkey', fixedPath)
  findMyWay.on('POST', '/goodkey/post', fixedPathPost)

  t.equals(findMyWay.find('PATCH', '/goodkey').handler, fixedPath)
  t.equals(findMyWay.find('POST', '/goodkey/post').handler, fixedPathPost)
  t.equals(findMyWay.find('GET', '/goodkey/self').handler, varPath)
  t.equals(findMyWay.find('GET', '/goodkey/self').params.key, 'goodkey')
  t.equals(findMyWay.find('PATCH', '/goodkey/').handler, fixedPath)
  t.equals(findMyWay.find('POST', '/goodkey/post/').handler, fixedPathPost)
  t.equals(findMyWay.find('GET', '/goodkey/self/').handler, varPath)
  t.equals(findMyWay.find('GET', '/goodkey/self/').params.key, 'goodkey')

  t.notOk(findMyWay.find('GET', '/goodkey/c'))
  t.notOk(findMyWay.find('PATCH', '/goodkey/self'))
})
```

**Comment by Eomm** [comment] 2020-05-07 21:58
Great!
You have right, the routing is ok but not the parsing!

We should open an issue on that repo

**Comment by mcollina** [comment] 2020-05-07 22:13
If you have bandwidth, sending a PR to fix would be also nice.

**Comment by kjmph** [comment] 2020-05-11 04:05
I found the time to read through the code. One may be able to devise the ability to recognize when the child of the currentNode is a '/' prefix, indicating the optional trailing slash in the radix tree. Then, we can fix up the path to supply `/goodkey/self` to the parametric matching, thusly achieving `goodkey` for the `:key` parameter.

However, we can easily devise a route tree that defeats this patching of the current matched path. For instance, `/a/b/c/d` and `/a/b/c/e` as static paths, with `/:param/b/c/f` as a parametric path. If the testing path is `/a/b/c/f`, the current router matching algorithm wouldn't be able to backtrack from `/a/b/c`, even if optional trailing slashes are supported through this additional `/` test.

I propose two paths forward:

1. Strengthen the documentation to say that the router match is greedy, and will consume static routes if a parameter is identical to a static route. There is a section in there discussing this as an ordering issue, yet doesn't spell out this odd usage.
2. Modify the radix tree matching algorithm to support backtracking. This would break this greedy behavior, as when a static route fails matching, `find-my-way` can backtrack to the earliest matching prefix that introduced a dynamic route, and search going forward again. Looking at the code, it certainly seems doable, and there is good testing in place to get a sense of breakage, yet may not be desirable to maintainers.

Thoughts?

**Comment by mcollina** [comment] 2020-05-11 05:45
I would recommend 1, e.g. the docs path.

The router is greedy because speed and we did not add backtracking because it will definitely cost precious CPU time and memory. If it’s possible to add it without a decrease in throughput, it’s definitely a better fix.

**Comment by kjmph** [comment] 2020-05-11 05:49
Would you like to see a proposed fix for simply catching the additional `/` in the filed bug? I don't win awards for cleanliness, however, it does give you the idea:

```patch
diff --git a/index.js b/index.js
index d386503..82eaa31 100644
--- a/index.js
+++ b/index.js
@@ -417,6 +417,36 @@ Router.prototype.find = function find (method, path, version) {
       ? currentNode.findChild(path, method)
       : currentNode.findVersionChild(version, path, method)
 
+    if (node !== null && this.ignoreTrailingSlash && node.prefix === '/' && pathLen > 0 && path.charCodeAt(0) === 47) {
+      path = path.slice(1)
+      pathLen = path.length
+      idxInOriginalPath += 1
+      if (pathLen === 0 || path === prefix) {
+        const handle = version === undefined
+          ? node.handlers[method]
+          : node.getVersionHandler(version, method)
+        if (handle !== null && handle !== undefined) {
+          const paramsObj = {}
+          if (handle.paramsLength > 0) {
+            const paramNames = handle.params
+
+            for (i = 0; i < handle.paramsLength; i++) {
+              paramsObj[paramNames[i]] = params[i]
+            }
+          }
+
+          return {
+            handler: handle.handler,
+            params: paramsObj,
+            store: handle.store
+          }
+        }
+      }
+      node = version === undefined
+        ? node.findChild(path, method)
+        : node.findVersionChild(version, path, method)
+    }
+
     if (node === null) {
       node = currentNode.parametricBrother
       if (node === null) {
```

**Comment by kjmph** [comment] 2020-05-11 05:51
Note, I'll ponder the backtracking speed, yet no promises I'll find the time to think through it. Do you want to handle the README update? Or, shall I open a pull request for that change in `find-my-way`?

**Comment by mcollina** [comment] 2020-05-11 06:44
If you can send a PR for the README update it would be fantastic. Also here in Fastify. You have a clear understanding of the problem and you would really provide a much better explanation.

**Comment by csvan** [comment] 2021-08-28 15:18
@kjmph did you get anywhere with this and can I help out? Running into the exact same issue:

```
server.get('/:root/documentation', swaggerHandler);
```

The above will always yield

```
req.params.root === ''
```

**Comment by kjmph** [comment] 2021-09-22 14:07
Hmm, I didn't make any forward progress. I reconstructed my routes to eliminate the problem, and while the API looks the same externally, internally there is a little duplication.

**Comment by kjmph** [comment] 2021-10-01 15:14
Sorry, should probably explain with more detail, I had a sub-route like `/:root/documentation` but in my case, I created new route entries for `/abc/documentation` and `/def/documentation`. In short, I was able to enumerate the list of routes in my case, and code split the get handlers. Does this help @csvan?

**Comment by csvan** [comment] 2021-10-01 15:27
@kjmph indeed, that is very helpful! Thanks 🙂

**Comment by jonnyn** [comment] 2021-10-31 04:06
Get exactly the same issue
`server.get("/product/:id", { schema: getProduct }, async (request, reply) => {...})`

I always get
`request.params.id === ''`

**Comment by Eomm** [comment] 2021-11-01 15:55
Closing since this issue is caused by https://github.com/delvedor/find-my-way/issues/149

**Closed by Eomm** 2021-11-01 15:55 UTC
Labels: bug, v2.x
