### ISSUE TITLE
Request hangs using @fastify/multipart plugin

### ISSUE THREAD

**Issue by Jawell** [fastify/fastify#4588] opened 2023-02-19 11:54 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.13.0

### Plugin version

7.4.1

### Node.js version

18.13.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.2.1

### Description

Request hangs every second time when using `@fastify/multipart` and sending a multipart form with file. After success response you can't reload current page

Also, you can find the same issue for GraphQL mercurius
https://github.com/mercurius-js/mercurius/issues/950

A form sends a file to a server after clicking on "test" button. I used 487kb png image and Firefox 111.0b2 (64-bit). There are three states: "SENDING REQUEST" (shows before request), "REQUEST SENT" (shows after success request), "TIMEOUT" (shows on some server error or timeout)
![123](https://user-images.githubusercontent.com/21054523/219945854-d385d5af-e357-4b5b-b3e5-38439d3f9996.gif)

### Steps to Reproduce

Clone https://github.com/Jawell/hangs-request-bug
`$ npm i && npm run start`
Go to http://127.0.0.1:8888

Or [codesandbox](https://codesandbox.io/p/sandbox/kind-benji-nrkj8l?file=%2Ffoo.html&selection=%5B%7B%22endColumn%22%3A22%2C%22endLineNumber%22%3A27%2C%22startColumn%22%3A22%2C%22startLineNumber%22%3A27%7D%5D) (not so quick service, so wait ~10 sec for first "REQUEST SENT" state)

**Comment by climba03003** [comment] 2023-02-19 18:46
I am closing it because the problem is you never consume the stream.
So, it must be hanging there by the nature of stream.

**Closed by climba03003** 2023-02-19 18:46 UTC

**Comment by Uzlopak** [comment] 2023-02-19 19:21
Is it possible to configure so that by default files get streamed into Nirvana?

**Comment by Jawell** [comment] 2023-02-19 19:31
I have a request validation before handling files. Could I close a stream if I didn't pass a validator? And how?

**Comment by Uzlopak** [comment] 2023-02-19 19:54
No. You either store the data of your stream somewhere (memory, file, redis, whatever) or you pipe it to nirvana.

**Comment by climba03003** [comment] 2023-02-20 03:56
Actually, yes. 
stream.resume() can start the stream flowing without any listener or destination. It just discard each chunk.

**Comment by Uzlopak** [comment] 2023-02-20 11:50
The problem is, that the busboy file stream can not be restarted after it has been piped to nirvana. The validation has to be done after all relevant fields are received. Now you dont controle the order of fields and files. So if the client sends the file first and then the fields, the fields will be persisted in memory and then you can validate. And then you realize, that the payload is valid and want to process the file, but it is already gone into oblivion.

**Comment by climba03003** [comment] 2023-02-20 12:26
All the details is written inside `@fastify/multipart`. 
The user should know the limitation before using it.

Anyway, false positive error better than staling request that may result in tcp socket exhaustion.

**Comment by Jawell** [comment] 2023-02-20 13:51
Hmm
I tried to use `graphql-upload` and `mercurius` (GraphQL adapter over `fastify`, I think you know). I'm still facing the problem. But hangs problem [was fixed](https://github.com/jaydenseric/graphql-upload/pull/81) in `graphql-upload` and I didn't have problems using Apollo + Express + `graphql-upload`. So, is it `fastify` "feature"?

**Comment by climba03003** [comment] 2023-02-20 15:47
It probably `mercurius` question more than a `fastify` question.
`graphql-upload` is actually dumping the file into file system but `@fastify/multipart` by default inherit the same behavior from `busboy` which is user must control the behavior explicitly.

As a `graphql` plugin if something is works in one side but not another, I suggest you to file an issue in `mercurius`.
