### ISSUE TITLE
Server-Sent Events for HTTP and HTTP/2

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#1877] opened 2019-09-27 17:43 UTC
## 🚀 Feature Proposal

I would like to see [Server-Sent Events](https://www.html5rocks.com/en/tutorials/eventsource/basics/https://www.html5rocks.com/en/tutorials/eventsource/basics/) in fastify core because it allows to establish a one-way pub/sub connection to the client with native browser capabilites. The SSE api is supported in all browsers. SSE is often a good choice for dashboards to pull data. Therefore it's much easier to run and maintain than WebSockets. With HTTP/2 they become much more efficient. I didn't know any framework which provides that kind of support out of the box.

## Example

```js
app.get('/', (req, reply) => {
  reply.event({ hello: 'world' })
  reply.event(readableStream)
  reply.event(null) // close stream
})
```
In the browser:
```js
const source = new EventSource("/");
source.onmessage = function(event) {
  document.getElementById("result").innerHTML += event.hello + "<br>";
};
```

References:

- https://github.com/chrisdickinson/sse-stream/blob/master/lib/server.js

**Comment by mcollina** [comment] 2019-09-28 07:00
SSE are pretty fantastic. Is https://www.npmjs.com/package/fastify-sse so much out of date? We might want to revamp that and decide based on adoption to add it to core.

**Comment by StarpTech** [comment] 2019-09-28 09:35
Oh, I've never recognized that plugin. I will check it out.

**Comment by StarpTech** [comment] 2019-09-28 10:25
@mcollina The code looks good but the availability of the maintainer seems not.
https://github.com/lolo32/fastify-sse/issues/3#issuecomment-453391460
The plugin can only be used with fastify o.x. Should we moved it to the core?

**Comment by mcollina** [comment] 2019-09-28 10:56
I think we could ask to take maintainance over and move it to the org. What do you think? As long as it is easy to have it in a plugin, it should probably stay there.

**Comment by StarpTech** [comment] 2019-09-28 11:36
I'm fine with that. I will open an issue. Let's have a ETA of 2 weeks before fork it.

**Comment by ekoeryanto** [comment] 2019-10-12 12:29
waiting for this

**Comment by hassler** [comment] 2019-10-30 08:33
Native SSE support in fastify would be great. Or just an example on how to implement efficient SSE. 
Given that the reply "stream" is not visible in fastify, to my knowledge its impossible to write efficient multi client sse, as you would like to multipex sse data on as low level as possible.

**Comment by hassler** [comment] 2019-11-09 17:53
>Native SSE support in fastify would be great. Or just an example on how to implement efficient SSE.
>Given that the reply "stream" is not visible in fastify, to my knowledge its impossible to write >efficient multi client sse, as you would like to multipex sse data on as low level as possible.

Just a comment.

SSE itself is easy. cleanup in fastify when client closes the connection, is not. I resorted to using node http like

```
 reply.sent = true
 reply.res.setHeader('Content-Type', 'text/event-stream')
 reply.res.setHeader('content-encoding', 'identity')
 reply.res.setHeader('Cache-Control', 'no-cache')

...

reply.res.on('close', () => {
    cleanup()
  })
`

**Comment by ekoeryanto** [comment] 2019-11-10 04:31
this is my current work with sse on fastify,
@hassler, I am confused where to put the _cleanup_.

`reply.res.on('close'` or `request.req.on('close'` ?

```js
const StreamSSE = require('ssestream2');
const { onRekairUpdated, onCustUpdated } = require('./binlog-router');

function handler(request, reply) {
  const sse = new StreamSSE(request.raw, {
    'Access-Control-Allow-Origin': '*',
  });

  sse.pipe(reply.res);

  function zoHan(e) {
    const type = e.getEventName();
    const { tableName, parentSchema } = e.tableMap[e.tableId];
    if (type === 'updaterows') {
      if (tableName === 'rekair') {
        onRekairUpdated(parentSchema, e.rows, (msg) => sse.write(msg));
      } else if (tableName === 'cust') {
        onCustUpdated(parentSchema, e.rows, (msg) => sse.write(msg));
      }
    } else if (type === 'writerows') {
      if (tableName === 'cust') {
        sse.write({
          event: 'pelanggan:baru',
          data: e.rows,
          retry: 20000,
        });
      }
    }
  }

  fastify.zongji.on('binlog', zoHan);

  request.req.on('close', () => {
    fastify.zongji.removeListener('binlog', zoHan);
  });
}

fastify.route({
  url: '/stream',
  method: 'GET',
  preValidation: [fastify.verifyIdToken(/* { claim: x => x.pid && x.pad === true }*/)],
  handler,
});

```

**Comment by StarpTech** [comment] 2019-11-10 15:31
@ekoeryanto @hassler this issue is not about to discuss implementation. Please open a separate issue.

**Comment by StarpTech** [comment] 2019-11-10 15:51
According to https://github.com/lolo32/fastify-sse/issues/12 I didn't get any feedback from the maintainer. It also seems there is a need for SSE. Let's create our own package. We can use https://github.com/trade-platform/fastify-sse-plugin or https://www.npmjs.com/package/fastify-sse as base.

**Comment by mcollina** [comment] 2019-11-15 10:22
Would you mind to ask npm to transfer the module to us? https://www.npmjs.com/policies/disputes < feel free to add me in cc.
Il 10 nov 2019, 15:51 +0000, Dustin Deus <notifications@github.com>, ha scritto:

**Comment by delvedor** [comment] 2019-11-24 17:40
Any news on this one?

**Comment by StarpTech** [comment] 2019-11-24 18:53
@delvedor currently no time to work on it.

**Comment by mpetrunic** [comment] 2020-04-09 08:18
We made new plugin:
https://www.npmjs.com/package/fastify-sse-v2

Currently, only AsyncIterables are supported but if there is interest we can provide more options.

**Comment by Eomm** [comment] 2020-05-05 20:20
Would you mind to add it to [Ecosystem](https://www.fastify.io/ecosystem/)?
there is only v1 listed 😀

**Comment by mpetrunic** [comment] 2020-05-06 05:22
> Would you mind to add it to [Ecosystem](https://www.fastify.io/ecosystem/)?
> there is only v1 listed

Yeah, sure :smile:

**Comment by mcollina** [comment] 2020-05-06 08:10
@lolo32 would you mind to add us to fastify-sse so that we can publish an updated version?

**Comment by IljaDaderko** [comment] 2020-07-05 20:55
It is possible to use `sse` in express without middleware i.e. through setting some headers and then just `writing` data (https://stackoverflow.com/a/59041709/911930). Is something like this achievable with fastify as well (without plugins above)?

I looked at examples and there are various cases that use 'stream' package, but if it is possible to achieve this through just setting correct headers and say json stringifying your data, why use plugins or am I missing something? If it is possible to do without any third party software, could I please ask for an example?

**Comment by mcollina** [comment] 2020-07-06 18:44
you can just sidestep this all and use `reply.raw.write()`.

**Comment by Krutsch** [comment] 2020-07-19 16:39
@mpetrunic Thanks for the new plugin, but it does not work with the latest version of fastify.
I implemented it via headers (looks correct, but I am no expert) @IljaDaderko  - https://github.com/Krutsch/sse-node-fastify

I noticed, that the fastify `reply.send` within setInterval is responding way above the 500ms (given timeout). Probably around 1s. Node.js is doing it in 500ms cycles. Ye I know.. its minimum timeout in `setInterval` ..  but still makes me wonder.
So I tried it with `reply.raw.write()` @mcollina but that did not work at all.

**Comment by mcollina** [comment] 2020-07-19 18:45
You should not use reply.send() and use reply.raw.write instead. Also, set the headers directly on rely.raw.

**Comment by mpetrunic** [comment] 2020-07-20 08:23
> @mpetrunic Thanks for the new plugin, but it does not work with the latest version of fastify.
> I implemented it via headers (looks correct, but I am no expert) @IljaDaderko - https://github.com/Krutsch/sse-node-fastify

Haven't tried with fastify@3.x will checkout soon and update

**Comment by mpetrunic** [comment] 2020-07-20 15:05
@Krutsch fastify-sse-v2@2.0.0 has support for fastify@3.x

**Comment by RafaelGSS** [comment] 2021-09-24 20:10
Closing once that `fastify-sse-v2` solves the issue and we don't get an answer about `fastify-sse`.

**Closed by RafaelGSS** 2021-09-24 20:10 UTC
Labels: plugin suggestion

**Comment by mrbrianevans** [comment] 2022-06-02 05:48
This is still something I think would be useful, and is not adequately addressed by current solutions. `fastify-sse` appears to be unmaintained, and `fastify-sse-v2` also hasn't received any substantive update in the last year (other than dependabot updating deps). Its API is very limited (only allows async iterables, but this isn't well suited to some use cases). `fastify-sse` had a much easier API to use, but stopped receiving updates. If this technology is made easily available, I think developers will be more likely to make use of it.

**Comment by climba03003** [comment] 2022-06-02 06:11
> This is still something I think would be useful, and is not adequately addressed by current solutions. `fastify-sse` appears to be unmaintained, and `fastify-sse-v2` also hasn't received any substantive update in the last year (other than dependabot updating deps). Its API is very limited (only allows async iterables, but this isn't well suited to some use cases). `fastify-sse` had a much easier API to use, but stopped receiving updates. If this technology is made easily available, I think developers will be more likely to make use of it.

I think you can consider to create the community package your own.
Both package seems incomplete for me, `SSE` need to be an event emitter. And it require a central management so the other route or action can send the appropriate event to the user.
The currently implementation for both packages is limited to the single route.

I think the plugin should be similar to `websocket` but it leaks of receiving user data only.

**Comment by mpetrunic** [comment] 2022-06-02 08:05
> This is still something I think would be useful, and is not adequately addressed by current solutions. `fastify-sse` appears to be unmaintained, and `fastify-sse-v2` also hasn't received any substantive update in the last year (other than dependabot updating deps). Its API is very limited (only allows async iterables, but this isn't well suited to some use cases). `fastify-sse` had a much easier API to use, but stopped receiving updates. If this technology is made easily available, I think developers will be more likely to make use of it.

What kind of API would you like to see? I would consider implementing it if you open an issue on fastify-sse-v2. Only reason why it isn't receiving updates is because it works for us.
Also, Fastify-sse-v2 can be used with eventEmitter: https://github.com/NodeFactoryIo/fastify-sse-v2#sending-events-from-eventemmiters

**Comment by mpetrunic** [comment] 2022-06-06 18:04
> Okay. I've just looked into that 'event-iterator' package, and it looks very useful in this case. The reason I say async iterables aren't appropriate in some use cases, is I am imagining a scenario where a client web app wants to listen for changes in a database. So it opens a SSE connection with the server, and the server watches the database, and on update it sends an event to the client. This doesn't seem like it logically fits the use of an AsyncIterator. Its not iterating over a collection, its just waiting for an event. `event-iterator` does seem to solve this problem though, by converting the event emitter into an async iterator. The kind of API that I think would be most suitable to this use case would look something like this:
> 
> ```js
> fastify.get('/listenForChanges', {}, (request, reply) => {
>     const listenStream = fastify.db.watch('doc-uuid')
>         .on('data', (data)=>reply.sse({ data: JSON.stringify(data) }))
>         .on('delete', () => reply.sse({ event: 'close' })
>     request.socket.on('close', ()=>listenStream.end())
> })
> ```
> 
> Even better would be to automatically `JSON.stringify` objects, like `fastify-sse` does using `"fast-safe-stringify"`. The API I'm describing is very similar (if not the same) as [`fastify-sse`](https://github.com/lolo32/fastify-sse), but that project is now unmaintained and was designed for older versions of fastify.
> 
> I've also noticed some bugs in the implementation of `fastify-sse-v2` such as changing the order of parameters can cause events to not be sent correctly. The `event` parameter needs to be before the `data` parameter when calling `reply.sse({event, data})` otherwise the event is not correctly labelled.

Here you go: https://github.com/NodeFactoryIo/fastify-sse-v2/releases/tag/v2.2.0 fastify-sse style API in addition to current API. 

I really don't wanna handle serialization and add dependency as this can be handled differently between each developer.

Afaik, according to sse spec, order of fields is irrelevant. In my test case I have changed order and it still works with eventsource. Maybe it's your client implementation?!

**Comment by mrbrianevans** [comment] 2022-06-06 21:59
Thank you so much for adding that API! I really appreciate it. @mpetrunic 

I will have to do more testing wrt. the order of fields.

**Comment by xtianus79** [comment] 2022-09-28 13:33
@mcollina My issue, is that with fastify it is very direct but a very "promise" way of doing things. When using an event stream such as SSE this abstraction takes the ability to know exactly what you would do "normally" and then how you are going to do it through a plugin such as the v2 one listed above. Natural/normal closeness is preferred on abstractions like these and I can't determine what is going on here well enough to make a production level decision to use this. As a result, I will have to go to express. 

What could help tremendously is documentation. In the documentation a compare and contrast and a clear list of limitations and extra-features would be greatly appreciated. This would make the learning curve less and also make the trust and understanding more.

**Comment by Eomm** [comment] 2022-09-29 16:23
Please, take a moment to read ["Why you should not say _«I will use X»_ to a Fastify maintainer"](https://gist.github.com/Eomm/4b72531ed9e2bdaefccf144ff9d7ce9a).

Thank you

**Comment by JenyaFTW** [comment] 2023-01-03 14:03
> Okay. I've just looked into that 'event-iterator' package, and it looks very useful in this case. The reason I say async iterables aren't appropriate in some use cases, is I am imagining a scenario where a client web app wants to listen for changes in a database. So it opens a SSE connection with the server, and the server watches the database, and on update it sends an event to the client. This doesn't seem like it logically fits the use of an AsyncIterator. Its not iterating over a collection, its just waiting for an event. `event-iterator` does seem to solve this problem though, by converting the event emitter into an async iterator. The kind of API that I think would be most suitable to this use case would look something like this:
> 
> ```js
> fastify.get('/listenForChanges', {}, (request, reply) => {
>     const listenStream = fastify.db.watch('doc-uuid')
>         .on('data', (data)=>reply.sse({ data: JSON.stringify(data) }))
>         .on('delete', () => reply.sse({ event: 'close' })
>     request.socket.on('close', ()=>listenStream.end())
> })
> ```
> 
> Even better would be to automatically `JSON.stringify` objects, like `fastify-sse` does using `"fast-safe-stringify"`. The API I'm describing is very similar (if not the same) as [`fastify-sse`](https://github.com/lolo32/fastify-sse), but that project is now unmaintained and was designed for older versions of fastify.
> 
> I've also noticed some bugs in the implementation of `fastify-sse-v2` such as changing the order of parameters can cause events to not be sent correctly. The `event` parameter needs to be before the `data` parameter when calling `reply.sse({event, data})` otherwise the event is not correctly labelled.

This API doesn't work anymore :/

**Comment by Eomm** [comment] 2023-01-06 08:51
Please open a new detailed issue adding a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
