### ISSUE TITLE
Why dont exclude docs, examples

### ISSUE THREAD

**Issue by dauletbaev** [fastify/fastify#4071] opened 2022-06-22 10:53 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

<img width="360" alt="Screen Shot 2022-06-22 at 3 47 22 pm" src="https://user-images.githubusercontent.com/83906251/175011591-54f5714e-91d1-4b95-acb7-7612181a0b86.png">

When I install fastify it includes **docs**, **examples** and **test** folders in **node_modules** folder. I think best don't include them or they included on purpose?

**Comment by jsumners** [comment] 2022-06-22 11:35
Duplicate of several past issues. Use the search feature.

**Closed by jsumners** 2022-06-22 11:35 UTC
