### ISSUE TITLE
Error thrown from a hook is not propagating to custom error handler

### ISSUE THREAD

**Issue by pushpa446** [fastify/fastify#1680] opened 2019-05-30 14:33 UTC
If you throw an error from a hook it is not propagated to the custom error handler.

## To Reproduce

```js
const fastify = require('fastify')();

fastify.setErrorHandler(async (error, request, reply) => {
  console.log("Im in error handler", error);
  reply.code(401).send({ error });
});

fastify.addHook("preValidation",   async (request) => {
  console.log("Im in pre validation");
  throw { detail: "Token is not valid" };
});

fastify.get('/', (req, reply) => {
  reply.send({ hello: 'world' })
});

fastify.listen(3000, err => {
  if (err) throw err;
  const port = fastify.server.address().port;
  console.log(`server listening on ${port}`)
});
```
```curl --request GET --url http://localhost:3000/```
## Expected behavior
The error should propagate to custom `errorHandler` and respond with 401 in this case.

## Current behavior
Not propagated error handler and responding with 200 `{ detail: "Token is not valid" }` as the body.

## Environment

- *node version*: 10
- *fastify version*: 2.4.1
- *os*: Mac

**Comment by Ethan-Arrowood** [comment] 2019-05-30 14:45
Based on the [docs](https://www.fastify.io/docs/latest/Hooks/#the-onerror-hook) I believe this is intended:

> This hook is useful if you need to do some custom error logging or add some specific header in case of error.
It is not intended for changing the error, and calling reply.send will throw an exception.

**Comment by pushpa446** [comment] 2019-05-30 17:57
I guess, the above is only for `onError` hook.

**Comment by delvedor** [comment] 2019-05-31 08:14
The error should be an instance of Error :)
https://github.com/fastify/fastify/blob/7f274d1be8ed27e32662a29a5940194b602086e8/lib/reply.js#L98-L101

**Comment by pushpa446** [comment] 2019-06-03 12:18
Thanks @delvedor. Got it.
But, if I throw from any place other than hook using this `throw { detail: "Token is not valid" }`  it is going to `errorHandler`. That's where my confusion started.

**Comment by mcollina** [comment] 2019-06-03 13:39
I think the confusion is something that we should address. IMHO it's either enabled somewhere or not. 

I _think_ we should only support throwing actual `Error` objects, however I see why developers tend to not do that. What do you think folks?

**Comment by Eomm** [comment] 2019-06-03 20:08
The custom error works only in `preSerialization` and `onSend` hooks for what I tested.
Maybe new tests should be added after the discussion.

I think that `Error` is less confusing for the reader and can be easily extended but, if ECMAScript admits it, we should support it. (checking the code it should not be painful, we already know if the handler has been rejected or not, we must provide that info to `reply.js`)

**Comment by Eomm** [comment] 2019-07-15 19:22
I think we should support it because [`throws`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw) accepts any kind of types, so the users expect correctly to manage an error throwing "something".

WDYT?

**Comment by yuchi** [comment] 2020-03-05 11:56
I don‘t know what you think about a change in semantics in order to support thrown plain objects, but for sure [there’s an error in the documentation](https://www.fastify.io/docs/latest/Reply/#async-await-and-promises) (in bold the relevant parts):

> Rejected promises default to a `500` HTTP status code. Reject the promise, or `throw` in an `async function`, with ***an object that has `statusCode` (or `status`) and `message` properties*** to modify the reply.

The terms “an object” **does not** imply that an instance of _Error_ or of a subclass of _Error_ is required.

**Comment by yuchi** [comment] 2020-03-06 16:22
Made a PR to propose a docs improvement.
Just let me state that this issue got me too and I checked the docs twice to make sure I could send custom errors. Since I had a custom `HTTPError` class the solution for my case was as simple as `extend Error`.

**Comment by Eomm** [comment] 2020-04-10 22:10
Feature ready in v3
Stay tuned for the release!

Closing

**Closed by Eomm** 2020-04-10 22:10 UTC
Labels: discussion, enhancement, v3.x

**Comment by Javarome** [comment] 2022-06-01 08:05
I still have this problem while using fastify 3.29.0:
```ts
 const errorHandler = async (error: Error, req, res) {
   console.error(error)
 }
  
fastify(options)
  .setErrorHandler(errorHandler)
  .delete("/:userId", {
      preHandler: async (req, res) => {
        throw new Error()
      },
      handler: async (req, res) => {
         ...
      })

```
When the `Error` is raised, `errorHandler` is *not* called. Instead it ends up as a 500.

**Comment by Fdawgs** [comment] 2022-06-01 08:12
> I still have this problem while using fastify 3.29.0:
> 
> ```ts
>  const errorHandler = async (error: Error, req, res) {
>    console.error(error)
>  }
>   
> fastify(options)
>   .setErrorHandler(errorHandler)
>   .delete("/:userId", {
>       preHandler: async (req, res) => {
>         throw new Error()
>       },
>       handler: async (req, res) => {
>          ...
>       })
> ```
> 
> When the `Error` is raised, `errorHandler` is _not_ called. Instead it ends up with a 500.

Can you please open a new Issue, with a reproduction?
