### ISSUE TITLE
Root route with prefix does not work

### ISSUE THREAD

**Issue by kromol** [fastify/fastify#1338] opened 2018-12-20 08:48 UTC
Root route with prefix does not work.
It works in fastify2 so maybe it would be possible to re-use the fix.

## To Reproduce

Create the root route / and register it with prefix:

```js
function fastifyRoutes (fastify, opts, next) {
    fastify.route({
        url: '/',
        method: 'GET',
        handler (req, reply) {
            reply.send({ result: 1 });
        }
    });

    next();
}

fastify.register(fastifyRoutes, { prefix: '/abc' });
```

## Expected behavior

`GET /abc/` should work and return `{ result: 1 }`

## Actual behavior
It returns 404

## Your Environment

- *node version*: 10
- *fastify version*: 1.13.2
- *os*: Mac

**Comment by mcollina** [comment] 2018-12-20 09:03
Thanks for reporting. This is a known issue in Fastify v1, which was fixed in Fastify v2 in https://github.com/fastify/fastify/pull/1228. We deemed the change semver-major, because it would be exposing one more route.

You can try `npm install fastify@next` while we finish the RC phase.

**Closed by mcollina** 2018-12-20 09:03 UTC

**Comment by kromol** [comment] 2018-12-20 09:20
It might be useful for other people.

One possible workaround would be to create wildcard route like this:
```js
function fastifyRoutes (fastify, opts, next) {
    fastify.route({
        url: '/',
        method: 'GET',
        handler (req, reply) {
            reply.send({ result: 1 });
        }
    });

    fastify.route({
        url: '/*',
        method: 'GET',
        handler (req, reply) {
            reply.send({ result: 10 });
        }
    });

    next();
}

fastify.register(fastifyRoutes, { prefix: '/abc' });
```
However it will not work if there is regex route (it would work with other static routes and with routes with params):
```js
// In this case GET /abc/ returns 404 due to regex route
function fastifyRoutes (fastify, opts, next) {
    fastify.route({
        url: '/',
        method: 'GET',
        handler (req, reply) {
            reply.send({ result: 1 });
        }
    });

    fastify.route({
        url: '/:f(^[0-9]+)',
        method: 'GET',
        handler (req, reply) {
            reply.send({ result: 20 });
        }
    });

    fastify.route({
        url: '/*',
        method: 'GET',
        handler (req, reply) {
            reply.send({ result: 10 });
        }
    });

    next();
}

fastify.register(fastifyRoutes, { prefix: '/abc' });
```

**Comment by limeandcoconut** [comment] 2019-03-19 22:22
I'm getting a similar issue in v2.0.0-rc6 and v2.1.0. Any movement on this?

**Comment by mcollina** [comment] 2019-03-19 23:06
@limeandcoconut I would recommend to open a new issue. This was definitely fixed in Fastify v2, so it’s something else.

**Comment by usersina** [comment] 2023-04-25 19:45
From the future (and using [autoload](https://github.com/fastify/fastify-autoload#global-configuration))

```typescript
const app = fastify({
  logger: true,
})

app.register(AutoLoad, {
  dir: join(__dirname, 'routes'),
  options: {
    prefix: '/api',
  },
})
```

**Comment by ualiusman** [comment] 2024-11-18 12:40
I'm using v5.1.0 and it have this issue.

**Comment by jsumners** [comment] 2024-11-18 16:36
Open a new issue with a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example), written in JavaScript. Doing so will help us diagnose your issue. It should be the bare minimum code needed to trigger the issue, and easily runnable without any changes or extra code.

You may use a GitHub repository to host the code if it is too much to fit in a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) (or two).
