### ISSUE TITLE
Lots of broken links in the docs

### ISSUE THREAD

**Issue by theneva** [fastify/fastify#5074] opened 2023-10-04 11:25 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi! :wave:

I was browsing the latest docs on Routes (https://fastify.dev/docs/latest/Reference/Routes/), and noticed that a bunch of the links seem to be broken. I first noticed it by trying to click the `Hooks` link in the "*Notice*: The documentation of […] are described in more detail in [Hooks]" paragraph.

When I went to fix that one broken link in the docs, I realised that it also affects several other links that point in the same way (linked with `./<Page>.md`), such as the `request` and `reply` bullets immediately above the notice:

<img width="907" alt="image" src="https://github.com/fastify/fastify/assets/1404650/428e992f-dce1-433b-b4b2-fc714d8e7a38">

For the record, they all lead to various paths resulting in this page:

<img width="1081" alt="image" src="https://github.com/fastify/fastify/assets/1404650/6ad25885-c05a-4ffc-9aa0-ed05a68a84d2">

It seems to me like the links are pointing to (for example) `/Reference/Routes/Request`, while they _should_ be pointing to `/Reference/Request` (without the `/Routes` part).

Since this seems to be a bigger issue than a single broken link, I decided to just let you know instead of trying to figure out how it works 😅 

Please forgive me if this has already been reported – I'm not too familiar with the project/GitHub org/repo, but I promise I did try to search the open issues.

Thanks for building a great product :smile:

**Comment by Zyzer01** [comment] 2023-10-04 11:54
Hi, I will love to work on this.
Kindly assign to me, Thanks

**Comment by Eomm** [comment] 2023-10-04 11:55
Duplicated in the website repo https://github.com/fastify/website/issues/157

Still not found the issue, actually some links work and other do not for no reason

PS: the issue is on our docusaurus build

**Closed by Eomm** 2023-10-04 11:55 UTC
