### ISSUE TITLE
app.close only triggers when a new request comes, resulting in 503 error

### ISSUE THREAD

**Issue by Dileep9999** [fastify/fastify#5524] opened 2024-06-17 08:10 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.28.0

### Node.js version

20.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.5 (23F79)

### Description

When invoking `app.close()` to gracefully shut down a Fastify server, the server does not close immediately. Instead, it waits for the existing requests to complete and no new req are allowed (This works as expected),  After all requests are complete when I pass a SIGINT (pm2 or ctrl + c) the closes when a new request to comes, which results in 503 errors for those new requests. This behavior causes issues in achieving a proper graceful shutdown.

Steps to Reproduce:

1. Create a Fastify server with a simple route that includes a delay.
2. Start the server and make a request to the route.
3. While the request is being processed, trigger app.close.
4. Observe that the server does not close immediately.
5. Make a new request to the server.
6. Observe that the new request returns a 503 error, and the server then closes.

```typescript
import fastify from 'fastify';

// Create a Fastify server
const app = fastify();

// Define a route with a delay
app.get('/delay', async (request, reply) => {
    await new Promise(resolve => setTimeout(resolve, 10000));
    reply.send({ message: 'Done' });
});

// Start the server
app.listen({port : 3000}, (err, address) => {
    if (err) {
        console.error(err);
        process.exit(1);
    }
    console.log(`Server listening at ${address}`);
});

// Handle graceful shutdown
process.on('SIGINT', async () => {
    console.log('SIGINT received. Closing server...');
    await app.close();
    console.log('Server closed');
    process.exit(0);
});

``` 

<img width="1021" alt="image" src="https://github.com/fastify/fastify/assets/35600193/3a4f3713-9f01-420b-b186-0e09c10f1fa7">

### Expected Behavior

When `app.close()` is called, the server should gracefully close when all existing requests are complete without requiring a new request to come and should not return 503 errors for any incoming requests after `app.close()` is triggered.

**Comment by climba03003** [comment] 2024-06-17 08:27
`.close` do not force closing the existing socket.
I believe it is waiting the existing socket to be timeout (keep-alive timeout) before actual close.

**Comment by metcoder95** [comment] 2024-06-18 08:58
Have you tried passing `forceCloseConnections`?
Given that the flag is not passed, I expect the current behaviour as its waiting until connections are closed on the other side or went `idle` until timeout

**Comment by jsumners** [comment] 2024-06-19 10:32
This is working as intended. Once the server is stopped, and it has not been configured to force close connections, it will return 503 for new connections. This is accepted industry practice and is necessary for reverse proxies to rebalance connections. See https://github.com/fastify/fastify/blob/6514dc7563d6d4401f8902ce5f333999a6058776/docs/Guides/Recommendations.md#use-a-reverse-proxy

**Comment by Dileep9999** [comment] 2024-06-19 12:13
@jsumners @metcoder95 

The issue isn't with returning a 503 status code—this works as expected. The problem arises after the initial request completes in 10 seconds. During this time, I receive a 503 status code, which is fine. However, after the initial request completes, the app.close() method hangs and does not terminate. No matter how many times I send the SIGINT signal, the application does not close.

I waited for about 3 minutes with no additional requests, and the server remained idle. When I finally sent another API request, I received a 503 status code, and only then did app.close() terminate the process.

I replaced the exact same code with Express, and after the initial 10-second request completed, sending a SIGINT signal successfully closed the app immediately.

For I express I don't even have to send SIGINT signal multiple times.

Let me know if I am still missing something.

Logs SS for express and Fastify:

<img width="1104" alt="image" src="https://github.com/fastify/fastify/assets/35600193/920109c1-5b47-400f-824c-76bfb310ccaa">


Fastify
```
const fastify = require('fastify')({ logger: true });
const port = 3000;

fastify.get('/delay', async (request, reply) => {
  await new Promise(resolve => setTimeout(resolve, 10000));
  console.log('Request completed after 10 seconds');
  return 'Request completed after 10 seconds';
});

const start = async () => {
  try {
    await fastify.listen({ port });
    console.log(`Fastify server listening on port ${port}`);
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};

start();

const gracefulShutdown = () => {
  console.log('Received SIGINT. Shutting down gracefully...');
  fastify.close(() => {
    console.log('Fastify server closed');
    process.exit(0);
  });
};

process.on('SIGINT', gracefulShutdown);
process.on('SIGTERM', gracefulShutdown);
```

Express

```
const express = require('express');
const http = require('http');
const app = express();
const port = 3000;

app.get('/delay', (req, res) => {
  setTimeout(() => {
    console.log('Request completed after 10 seconds');
    res.send('Request completed after 10 seconds');
  }, 10000);
});

const server = http.createServer(app);

server.listen(port, () => {
  console.log(`Express server listening on port ${port}`);
});

const gracefulShutdown = () => {
  console.log('Received SIGINT. Shutting down gracefully...');
  server.close(() => {
    console.log('Express server closed');
    process.exit(0);
  });
};

process.on('SIGINT', gracefulShutdown);
process.on('SIGTERM', gracefulShutdown);
```

**Comment by climba03003** [comment] 2024-06-19 12:55
I cannot reproduce the problem with cURL, but able to with browser.
It actually indicate the problem is related to keepalive connection as mention before.

**Comment by Dileep9999** [comment] 2024-06-19 17:13
@climba03003 Thanks for the input, I see that keepAliveTimeout is 72000 by default,  In Express, the default keepAliveTimeout is determined by the underlying Node.js HTTP server which is 5000.

 I will adjust per my use case. I think fastify should also reduce to Node.js HTTP server timeout by default to keep consistency with node http module.
 
Thanks 🤝

**Comment by climba03003** [comment] 2024-06-19 19:47
The reason of increasing `keepAliveTimeout` is based on the decision of better fit behind reverse proxy and performance.
We always recommend to deploy behind reverse proxy.

see #3282

**Closed by climba03003** 2024-06-19 19:47 UTC
Labels: need info
